/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.mef.geco.intranet.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the supportData service. Represents a row in the &quot;MEFGECO_supportData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.mef.geco.intranet.model.impl.supportDataModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.mef.geco.intranet.model.impl.supportDataImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see supportData
 * @see com.mef.geco.intranet.model.impl.supportDataImpl
 * @see com.mef.geco.intranet.model.impl.supportDataModelImpl
 * @generated
 */
@ProviderType
public interface supportDataModel extends BaseModel<supportData> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a support data model instance should use the {@link supportData} interface instead.
	 */

	/**
	 * Returns the primary key of this support data.
	 *
	 * @return the primary key of this support data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this support data.
	 *
	 * @param primaryKey the primary key of this support data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this support data.
	 *
	 * @return the uuid of this support data
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this support data.
	 *
	 * @param uuid the uuid of this support data
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ID of this support data.
	 *
	 * @return the ID of this support data
	 */
	public long getId();

	/**
	 * Sets the ID of this support data.
	 *
	 * @param id the ID of this support data
	 */
	public void setId(long id);

	/**
	 * Returns the data of this support data.
	 *
	 * @return the data of this support data
	 */
	@AutoEscape
	public String getData();

	/**
	 * Sets the data of this support data.
	 *
	 * @param data the data of this support data
	 */
	public void setData(String data);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(com.mef.geco.intranet.model.supportData supportData);

	@Override
	public int hashCode();

	@Override
	public CacheModel<com.mef.geco.intranet.model.supportData> toCacheModel();

	@Override
	public com.mef.geco.intranet.model.supportData toEscapedModel();

	@Override
	public com.mef.geco.intranet.model.supportData toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}