
package it.intranetdag.rubrica.services;

import com.liferay.portal.kernel.log.Log;
import com.liferay.portal.kernel.log.LogFactoryUtil;

import javax.xml.ws.Endpoint;

/**
 * This class was generated by Apache CXF 3.1.12
 * 2017-07-24T18:02:54.742+02:00
 * Generated source version: 3.1.12
 * 
 */
 
public class AnagraficaWSPortType_AnagraficaWSHttpEndpoint_Server{
	
	final Log _log = LogFactoryUtil.getLog(AnagraficaWSPortType_AnagraficaWSHttpEndpoint_Server.class);
	
    protected AnagraficaWSPortType_AnagraficaWSHttpEndpoint_Server() {
    	try {
            System.out.println("Starting Server");
            Object implementor = new AnagraficaWSHttpEndpointImpl();
            String address = "CHANGE_ME";
            Endpoint.publish(address, implementor);
    		
    	} catch(Exception e) {
    		_log.warn(e);
    	}

    }
    
    public static void main(String args[]) throws java.lang.Exception { 
        new AnagraficaWSPortType_AnagraficaWSHttpEndpoint_Server();
        System.out.println("Server ready..."); 
        
        Thread.sleep(5000L * 60); 
        System.out.println("Server exiting");
        System.exit(0);
    }
}
