/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the BeneInvRichiesto service. Represents a row in the &quot;MFORM_BeneInvRichiesto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link service.intranet.mef.model.impl.BeneInvRichiestoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link service.intranet.mef.model.impl.BeneInvRichiestoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BeneInvRichiesto
 * @see service.intranet.mef.model.impl.BeneInvRichiestoImpl
 * @see service.intranet.mef.model.impl.BeneInvRichiestoModelImpl
 * @generated
 */
@ProviderType
public interface BeneInvRichiestoModel extends BaseModel<BeneInvRichiesto> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bene inv richiesto model instance should use the {@link BeneInvRichiesto} interface instead.
	 */

	/**
	 * Returns the primary key of this bene inv richiesto.
	 *
	 * @return the primary key of this bene inv richiesto
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bene inv richiesto.
	 *
	 * @param primaryKey the primary key of this bene inv richiesto
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_bene_rich of this bene inv richiesto.
	 *
	 * @return the id_bene_rich of this bene inv richiesto
	 */
	public long getId_bene_rich();

	/**
	 * Sets the id_bene_rich of this bene inv richiesto.
	 *
	 * @param id_bene_rich the id_bene_rich of this bene inv richiesto
	 */
	public void setId_bene_rich(long id_bene_rich);

	/**
	 * Returns the tipologia of this bene inv richiesto.
	 *
	 * @return the tipologia of this bene inv richiesto
	 */
	@AutoEscape
	public String getTipologia();

	/**
	 * Sets the tipologia of this bene inv richiesto.
	 *
	 * @param tipologia the tipologia of this bene inv richiesto
	 */
	public void setTipologia(String tipologia);

	/**
	 * Returns the descrizione of this bene inv richiesto.
	 *
	 * @return the descrizione of this bene inv richiesto
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this bene inv richiesto.
	 *
	 * @param descrizione the descrizione of this bene inv richiesto
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the quantita of this bene inv richiesto.
	 *
	 * @return the quantita of this bene inv richiesto
	 */
	public int getQuantita();

	/**
	 * Sets the quantita of this bene inv richiesto.
	 *
	 * @param quantita the quantita of this bene inv richiesto
	 */
	public void setQuantita(int quantita);

	/**
	 * Returns the dettagli of this bene inv richiesto.
	 *
	 * @return the dettagli of this bene inv richiesto
	 */
	@AutoEscape
	public String getDettagli();

	/**
	 * Sets the dettagli of this bene inv richiesto.
	 *
	 * @param dettagli the dettagli of this bene inv richiesto
	 */
	public void setDettagli(String dettagli);

	/**
	 * Returns the in_elenco of this bene inv richiesto.
	 *
	 * @return the in_elenco of this bene inv richiesto
	 */
	public boolean getIn_elenco();

	/**
	 * Returns <code>true</code> if this bene inv richiesto is in_elenco.
	 *
	 * @return <code>true</code> if this bene inv richiesto is in_elenco; <code>false</code> otherwise
	 */
	public boolean isIn_elenco();

	/**
	 * Sets whether this bene inv richiesto is in_elenco.
	 *
	 * @param in_elenco the in_elenco of this bene inv richiesto
	 */
	public void setIn_elenco(boolean in_elenco);

	/**
	 * Returns the id_richiesta of this bene inv richiesto.
	 *
	 * @return the id_richiesta of this bene inv richiesto
	 */
	public long getId_richiesta();

	/**
	 * Sets the id_richiesta of this bene inv richiesto.
	 *
	 * @param id_richiesta the id_richiesta of this bene inv richiesto
	 */
	public void setId_richiesta(long id_richiesta);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		service.intranet.mef.model.BeneInvRichiesto beneInvRichiesto);

	@Override
	public int hashCode();

	@Override
	public CacheModel<service.intranet.mef.model.BeneInvRichiesto> toCacheModel();

	@Override
	public service.intranet.mef.model.BeneInvRichiesto toEscapedModel();

	@Override
	public service.intranet.mef.model.BeneInvRichiesto toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}