/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the BeneInv service. Represents a row in the &quot;MFORM_BeneInv&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link service.intranet.mef.model.impl.BeneInvModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link service.intranet.mef.model.impl.BeneInvImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BeneInv
 * @see service.intranet.mef.model.impl.BeneInvImpl
 * @see service.intranet.mef.model.impl.BeneInvModelImpl
 * @generated
 */
@ProviderType
public interface BeneInvModel extends BaseModel<BeneInv> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a bene inv model instance should use the {@link BeneInv} interface instead.
	 */

	/**
	 * Returns the primary key of this bene inv.
	 *
	 * @return the primary key of this bene inv
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this bene inv.
	 *
	 * @param primaryKey the primary key of this bene inv
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this bene inv.
	 *
	 * @return the ID of this bene inv
	 */
	public long getId();

	/**
	 * Sets the ID of this bene inv.
	 *
	 * @param id the ID of this bene inv
	 */
	public void setId(long id);

	/**
	 * Returns the bene of this bene inv.
	 *
	 * @return the bene of this bene inv
	 */
	@AutoEscape
	public String getBene();

	/**
	 * Sets the bene of this bene inv.
	 *
	 * @param bene the bene of this bene inv
	 */
	public void setBene(String bene);

	/**
	 * Returns the id_tipo of this bene inv.
	 *
	 * @return the id_tipo of this bene inv
	 */
	public long getId_tipo();

	/**
	 * Sets the id_tipo of this bene inv.
	 *
	 * @param id_tipo the id_tipo of this bene inv
	 */
	public void setId_tipo(long id_tipo);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(service.intranet.mef.model.BeneInv beneInv);

	@Override
	public int hashCode();

	@Override
	public CacheModel<service.intranet.mef.model.BeneInv> toCacheModel();

	@Override
	public service.intranet.mef.model.BeneInv toEscapedModel();

	@Override
	public service.intranet.mef.model.BeneInv toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}