/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the LogisticaStato service. Represents a row in the &quot;MFORM_LogisticaStato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link service.intranet.mef.model.impl.LogisticaStatoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link service.intranet.mef.model.impl.LogisticaStatoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LogisticaStato
 * @see service.intranet.mef.model.impl.LogisticaStatoImpl
 * @see service.intranet.mef.model.impl.LogisticaStatoModelImpl
 * @generated
 */
@ProviderType
public interface LogisticaStatoModel extends BaseModel<LogisticaStato> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a logistica stato model instance should use the {@link LogisticaStato} interface instead.
	 */

	/**
	 * Returns the primary key of this logistica stato.
	 *
	 * @return the primary key of this logistica stato
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this logistica stato.
	 *
	 * @param primaryKey the primary key of this logistica stato
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this logistica stato.
	 *
	 * @return the ID of this logistica stato
	 */
	public long getId();

	/**
	 * Sets the ID of this logistica stato.
	 *
	 * @param id the ID of this logistica stato
	 */
	public void setId(long id);

	/**
	 * Returns the descrizione of this logistica stato.
	 *
	 * @return the descrizione of this logistica stato
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this logistica stato.
	 *
	 * @param descrizione the descrizione of this logistica stato
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the utente of this logistica stato.
	 *
	 * @return the utente of this logistica stato
	 */
	@AutoEscape
	public String getUtente();

	/**
	 * Sets the utente of this logistica stato.
	 *
	 * @param utente the utente of this logistica stato
	 */
	public void setUtente(String utente);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		service.intranet.mef.model.LogisticaStato logisticaStato);

	@Override
	public int hashCode();

	@Override
	public CacheModel<service.intranet.mef.model.LogisticaStato> toCacheModel();

	@Override
	public service.intranet.mef.model.LogisticaStato toEscapedModel();

	@Override
	public service.intranet.mef.model.LogisticaStato toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}