/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the LogisticaRichieste service. Represents a row in the &quot;MFORM_LogisticaRichieste&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link service.intranet.mef.model.impl.LogisticaRichiesteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link service.intranet.mef.model.impl.LogisticaRichiesteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LogisticaRichieste
 * @see service.intranet.mef.model.impl.LogisticaRichiesteImpl
 * @see service.intranet.mef.model.impl.LogisticaRichiesteModelImpl
 * @generated
 */
@ProviderType
public interface LogisticaRichiesteModel extends BaseModel<LogisticaRichieste> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a logistica richieste model instance should use the {@link LogisticaRichieste} interface instead.
	 */

	/**
	 * Returns the primary key of this logistica richieste.
	 *
	 * @return the primary key of this logistica richieste
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this logistica richieste.
	 *
	 * @param primaryKey the primary key of this logistica richieste
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this logistica richieste.
	 *
	 * @return the ID of this logistica richieste
	 */
	public long getId();

	/**
	 * Sets the ID of this logistica richieste.
	 *
	 * @param id the ID of this logistica richieste
	 */
	public void setId(long id);

	/**
	 * Returns the oggetto of this logistica richieste.
	 *
	 * @return the oggetto of this logistica richieste
	 */
	@AutoEscape
	public String getOggetto();

	/**
	 * Sets the oggetto of this logistica richieste.
	 *
	 * @param oggetto the oggetto of this logistica richieste
	 */
	public void setOggetto(String oggetto);

	/**
	 * Returns the utente of this logistica richieste.
	 *
	 * @return the utente of this logistica richieste
	 */
	@AutoEscape
	public String getUtente();

	/**
	 * Sets the utente of this logistica richieste.
	 *
	 * @param utente the utente of this logistica richieste
	 */
	public void setUtente(String utente);

	/**
	 * Returns the dipartimento of this logistica richieste.
	 *
	 * @return the dipartimento of this logistica richieste
	 */
	@AutoEscape
	public String getDipartimento();

	/**
	 * Sets the dipartimento of this logistica richieste.
	 *
	 * @param dipartimento the dipartimento of this logistica richieste
	 */
	public void setDipartimento(String dipartimento);

	/**
	 * Returns the data_richiesta of this logistica richieste.
	 *
	 * @return the data_richiesta of this logistica richieste
	 */
	public Date getData_richiesta();

	/**
	 * Sets the data_richiesta of this logistica richieste.
	 *
	 * @param data_richiesta the data_richiesta of this logistica richieste
	 */
	public void setData_richiesta(Date data_richiesta);

	/**
	 * Returns the dettaglio_richiedente of this logistica richieste.
	 *
	 * @return the dettaglio_richiedente of this logistica richieste
	 */
	@AutoEscape
	public String getDettaglio_richiedente();

	/**
	 * Sets the dettaglio_richiedente of this logistica richieste.
	 *
	 * @param dettaglio_richiedente the dettaglio_richiedente of this logistica richieste
	 */
	public void setDettaglio_richiedente(String dettaglio_richiedente);

	/**
	 * Returns the dettaglio_richieste of this logistica richieste.
	 *
	 * @return the dettaglio_richieste of this logistica richieste
	 */
	@AutoEscape
	public String getDettaglio_richieste();

	/**
	 * Sets the dettaglio_richieste of this logistica richieste.
	 *
	 * @param dettaglio_richieste the dettaglio_richieste of this logistica richieste
	 */
	public void setDettaglio_richieste(String dettaglio_richieste);

	/**
	 * Returns the note_gestore of this logistica richieste.
	 *
	 * @return the note_gestore of this logistica richieste
	 */
	@AutoEscape
	public String getNote_gestore();

	/**
	 * Sets the note_gestore of this logistica richieste.
	 *
	 * @param note_gestore the note_gestore of this logistica richieste
	 */
	public void setNote_gestore(String note_gestore);

	/**
	 * Returns the id_valutazione of this logistica richieste.
	 *
	 * @return the id_valutazione of this logistica richieste
	 */
	public long getId_valutazione();

	/**
	 * Sets the id_valutazione of this logistica richieste.
	 *
	 * @param id_valutazione the id_valutazione of this logistica richieste
	 */
	public void setId_valutazione(long id_valutazione);

	/**
	 * Returns the id_stato of this logistica richieste.
	 *
	 * @return the id_stato of this logistica richieste
	 */
	public long getId_stato();

	/**
	 * Sets the id_stato of this logistica richieste.
	 *
	 * @param id_stato the id_stato of this logistica richieste
	 */
	public void setId_stato(long id_stato);

	/**
	 * Returns the note of this logistica richieste.
	 *
	 * @return the note of this logistica richieste
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this logistica richieste.
	 *
	 * @param note the note of this logistica richieste
	 */
	public void setNote(String note);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		service.intranet.mef.model.LogisticaRichieste logisticaRichieste);

	@Override
	public int hashCode();

	@Override
	public CacheModel<service.intranet.mef.model.LogisticaRichieste> toCacheModel();

	@Override
	public service.intranet.mef.model.LogisticaRichieste toEscapedModel();

	@Override
	public service.intranet.mef.model.LogisticaRichieste toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}