/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the ModuloTrasporti service. Represents a row in the &quot;MFORM_ModuloTrasporti&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link service.intranet.mef.model.impl.ModuloTrasportiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link service.intranet.mef.model.impl.ModuloTrasportiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ModuloTrasporti
 * @see service.intranet.mef.model.impl.ModuloTrasportiImpl
 * @see service.intranet.mef.model.impl.ModuloTrasportiModelImpl
 * @generated
 */
@ProviderType
public interface ModuloTrasportiModel extends BaseModel<ModuloTrasporti> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a modulo trasporti model instance should use the {@link ModuloTrasporti} interface instead.
	 */

	/**
	 * Returns the primary key of this modulo trasporti.
	 *
	 * @return the primary key of this modulo trasporti
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this modulo trasporti.
	 *
	 * @param primaryKey the primary key of this modulo trasporti
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_modulo_trasporti of this modulo trasporti.
	 *
	 * @return the id_modulo_trasporti of this modulo trasporti
	 */
	public long getId_modulo_trasporti();

	/**
	 * Sets the id_modulo_trasporti of this modulo trasporti.
	 *
	 * @param id_modulo_trasporti the id_modulo_trasporti of this modulo trasporti
	 */
	public void setId_modulo_trasporti(long id_modulo_trasporti);

	/**
	 * Returns the cognome of this modulo trasporti.
	 *
	 * @return the cognome of this modulo trasporti
	 */
	@AutoEscape
	public String getCognome();

	/**
	 * Sets the cognome of this modulo trasporti.
	 *
	 * @param cognome the cognome of this modulo trasporti
	 */
	public void setCognome(String cognome);

	/**
	 * Returns the nome of this modulo trasporti.
	 *
	 * @return the nome of this modulo trasporti
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this modulo trasporti.
	 *
	 * @param nome the nome of this modulo trasporti
	 */
	public void setNome(String nome);

	/**
	 * Returns the codice_fiscale of this modulo trasporti.
	 *
	 * @return the codice_fiscale of this modulo trasporti
	 */
	@AutoEscape
	public String getCodice_fiscale();

	/**
	 * Sets the codice_fiscale of this modulo trasporti.
	 *
	 * @param codice_fiscale the codice_fiscale of this modulo trasporti
	 */
	public void setCodice_fiscale(String codice_fiscale);

	/**
	 * Returns the utente_inserimento of this modulo trasporti.
	 *
	 * @return the utente_inserimento of this modulo trasporti
	 */
	@AutoEscape
	public String getUtente_inserimento();

	/**
	 * Sets the utente_inserimento of this modulo trasporti.
	 *
	 * @param utente_inserimento the utente_inserimento of this modulo trasporti
	 */
	public void setUtente_inserimento(String utente_inserimento);

	/**
	 * Returns the data_inserimento of this modulo trasporti.
	 *
	 * @return the data_inserimento of this modulo trasporti
	 */
	public Date getData_inserimento();

	/**
	 * Sets the data_inserimento of this modulo trasporti.
	 *
	 * @param data_inserimento the data_inserimento of this modulo trasporti
	 */
	public void setData_inserimento(Date data_inserimento);

	/**
	 * Returns the flag_tipospesa of this modulo trasporti.
	 *
	 * @return the flag_tipospesa of this modulo trasporti
	 */
	@AutoEscape
	public String getFlag_tipospesa();

	/**
	 * Sets the flag_tipospesa of this modulo trasporti.
	 *
	 * @param flag_tipospesa the flag_tipospesa of this modulo trasporti
	 */
	public void setFlag_tipospesa(String flag_tipospesa);

	/**
	 * Returns the iban of this modulo trasporti.
	 *
	 * @return the iban of this modulo trasporti
	 */
	@AutoEscape
	public String getIban();

	/**
	 * Sets the iban of this modulo trasporti.
	 *
	 * @param iban the iban of this modulo trasporti
	 */
	public void setIban(String iban);

	/**
	 * Returns the importo of this modulo trasporti.
	 *
	 * @return the importo of this modulo trasporti
	 */
	@AutoEscape
	public String getImporto();

	/**
	 * Sets the importo of this modulo trasporti.
	 *
	 * @param importo the importo of this modulo trasporti
	 */
	public void setImporto(String importo);

	/**
	 * Returns the data_titolo_annuale of this modulo trasporti.
	 *
	 * @return the data_titolo_annuale of this modulo trasporti
	 */
	public Date getData_titolo_annuale();

	/**
	 * Sets the data_titolo_annuale of this modulo trasporti.
	 *
	 * @param data_titolo_annuale the data_titolo_annuale of this modulo trasporti
	 */
	public void setData_titolo_annuale(Date data_titolo_annuale);

	/**
	 * Returns the nr_titoli_mensili of this modulo trasporti.
	 *
	 * @return the nr_titoli_mensili of this modulo trasporti
	 */
	@AutoEscape
	public String getNr_titoli_mensili();

	/**
	 * Sets the nr_titoli_mensili of this modulo trasporti.
	 *
	 * @param nr_titoli_mensili the nr_titoli_mensili of this modulo trasporti
	 */
	public void setNr_titoli_mensili(String nr_titoli_mensili);

	/**
	 * Returns the figlio_nome of this modulo trasporti.
	 *
	 * @return the figlio_nome of this modulo trasporti
	 */
	@AutoEscape
	public String getFiglio_nome();

	/**
	 * Sets the figlio_nome of this modulo trasporti.
	 *
	 * @param figlio_nome the figlio_nome of this modulo trasporti
	 */
	public void setFiglio_nome(String figlio_nome);

	/**
	 * Returns the figlio_cognome of this modulo trasporti.
	 *
	 * @return the figlio_cognome of this modulo trasporti
	 */
	@AutoEscape
	public String getFiglio_cognome();

	/**
	 * Sets the figlio_cognome of this modulo trasporti.
	 *
	 * @param figlio_cognome the figlio_cognome of this modulo trasporti
	 */
	public void setFiglio_cognome(String figlio_cognome);

	/**
	 * Returns the figlio_data_nascita of this modulo trasporti.
	 *
	 * @return the figlio_data_nascita of this modulo trasporti
	 */
	public Date getFiglio_data_nascita();

	/**
	 * Sets the figlio_data_nascita of this modulo trasporti.
	 *
	 * @param figlio_data_nascita the figlio_data_nascita of this modulo trasporti
	 */
	public void setFiglio_data_nascita(Date figlio_data_nascita);

	/**
	 * Returns the figlio_luogo_data of this modulo trasporti.
	 *
	 * @return the figlio_luogo_data of this modulo trasporti
	 */
	@AutoEscape
	public String getFiglio_luogo_data();

	/**
	 * Sets the figlio_luogo_data of this modulo trasporti.
	 *
	 * @param figlio_luogo_data the figlio_luogo_data of this modulo trasporti
	 */
	public void setFiglio_luogo_data(String figlio_luogo_data);

	/**
	 * Returns the figlio_codicefiscale of this modulo trasporti.
	 *
	 * @return the figlio_codicefiscale of this modulo trasporti
	 */
	@AutoEscape
	public String getFiglio_codicefiscale();

	/**
	 * Sets the figlio_codicefiscale of this modulo trasporti.
	 *
	 * @param figlio_codicefiscale the figlio_codicefiscale of this modulo trasporti
	 */
	public void setFiglio_codicefiscale(String figlio_codicefiscale);

	/**
	 * Returns the note of this modulo trasporti.
	 *
	 * @return the note of this modulo trasporti
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this modulo trasporti.
	 *
	 * @param note the note of this modulo trasporti
	 */
	public void setNote(String note);

	/**
	 * Returns the flag_inviato of this modulo trasporti.
	 *
	 * @return the flag_inviato of this modulo trasporti
	 */
	@AutoEscape
	public String getFlag_inviato();

	/**
	 * Sets the flag_inviato of this modulo trasporti.
	 *
	 * @param flag_inviato the flag_inviato of this modulo trasporti
	 */
	public void setFlag_inviato(String flag_inviato);

	/**
	 * Returns the telefono of this modulo trasporti.
	 *
	 * @return the telefono of this modulo trasporti
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this modulo trasporti.
	 *
	 * @param telefono the telefono of this modulo trasporti
	 */
	public void setTelefono(String telefono);

	/**
	 * Returns the allegato uuid of this modulo trasporti.
	 *
	 * @return the allegato uuid of this modulo trasporti
	 */
	@AutoEscape
	public String getAllegatoUuid();

	/**
	 * Sets the allegato uuid of this modulo trasporti.
	 *
	 * @param allegatoUuid the allegato uuid of this modulo trasporti
	 */
	public void setAllegatoUuid(String allegatoUuid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		service.intranet.mef.model.ModuloTrasporti moduloTrasporti);

	@Override
	public int hashCode();

	@Override
	public CacheModel<service.intranet.mef.model.ModuloTrasporti> toCacheModel();

	@Override
	public service.intranet.mef.model.ModuloTrasporti toEscapedModel();

	@Override
	public service.intranet.mef.model.ModuloTrasporti toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}