/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RichiestaPubblicSiti service. Represents a row in the &quot;MFORM_RichiestaPubblicSiti&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link service.intranet.mef.model.impl.RichiestaPubblicSitiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link service.intranet.mef.model.impl.RichiestaPubblicSitiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RichiestaPubblicSiti
 * @see service.intranet.mef.model.impl.RichiestaPubblicSitiImpl
 * @see service.intranet.mef.model.impl.RichiestaPubblicSitiModelImpl
 * @generated
 */
@ProviderType
public interface RichiestaPubblicSitiModel extends BaseModel<RichiestaPubblicSiti> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a richiesta pubblic siti model instance should use the {@link RichiestaPubblicSiti} interface instead.
	 */

	/**
	 * Returns the primary key of this richiesta pubblic siti.
	 *
	 * @return the primary key of this richiesta pubblic siti
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this richiesta pubblic siti.
	 *
	 * @param primaryKey the primary key of this richiesta pubblic siti
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_rich_pubblic of this richiesta pubblic siti.
	 *
	 * @return the id_rich_pubblic of this richiesta pubblic siti
	 */
	public long getId_rich_pubblic();

	/**
	 * Sets the id_rich_pubblic of this richiesta pubblic siti.
	 *
	 * @param id_rich_pubblic the id_rich_pubblic of this richiesta pubblic siti
	 */
	public void setId_rich_pubblic(long id_rich_pubblic);

	/**
	 * Returns the dati_richiedente of this richiesta pubblic siti.
	 *
	 * @return the dati_richiedente of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getDati_richiedente();

	/**
	 * Sets the dati_richiedente of this richiesta pubblic siti.
	 *
	 * @param dati_richiedente the dati_richiedente of this richiesta pubblic siti
	 */
	public void setDati_richiedente(String dati_richiedente);

	/**
	 * Returns the dati_docum of this richiesta pubblic siti.
	 *
	 * @return the dati_docum of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getDati_docum();

	/**
	 * Sets the dati_docum of this richiesta pubblic siti.
	 *
	 * @param dati_docum the dati_docum of this richiesta pubblic siti
	 */
	public void setDati_docum(String dati_docum);

	/**
	 * Returns the titolo of this richiesta pubblic siti.
	 *
	 * @return the titolo of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getTitolo();

	/**
	 * Sets the titolo of this richiesta pubblic siti.
	 *
	 * @param titolo the titolo of this richiesta pubblic siti
	 */
	public void setTitolo(String titolo);

	/**
	 * Returns the sottotitolo of this richiesta pubblic siti.
	 *
	 * @return the sottotitolo of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getSottotitolo();

	/**
	 * Sets the sottotitolo of this richiesta pubblic siti.
	 *
	 * @param sottotitolo the sottotitolo of this richiesta pubblic siti
	 */
	public void setSottotitolo(String sottotitolo);

	/**
	 * Returns the novita_abstract of this richiesta pubblic siti.
	 *
	 * @return the novita_abstract of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getNovita_abstract();

	/**
	 * Sets the novita_abstract of this richiesta pubblic siti.
	 *
	 * @param novita_abstract the novita_abstract of this richiesta pubblic siti
	 */
	public void setNovita_abstract(String novita_abstract);

	/**
	 * Returns the note_riferim of this richiesta pubblic siti.
	 *
	 * @return the note_riferim of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getNote_riferim();

	/**
	 * Sets the note_riferim of this richiesta pubblic siti.
	 *
	 * @param note_riferim the note_riferim of this richiesta pubblic siti
	 */
	public void setNote_riferim(String note_riferim);

	/**
	 * Returns the dati_stampa_carta of this richiesta pubblic siti.
	 *
	 * @return the dati_stampa_carta of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getDati_stampa_carta();

	/**
	 * Sets the dati_stampa_carta of this richiesta pubblic siti.
	 *
	 * @param dati_stampa_carta the dati_stampa_carta of this richiesta pubblic siti
	 */
	public void setDati_stampa_carta(String dati_stampa_carta);

	/**
	 * Returns the dati_altro of this richiesta pubblic siti.
	 *
	 * @return the dati_altro of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getDati_altro();

	/**
	 * Sets the dati_altro of this richiesta pubblic siti.
	 *
	 * @param dati_altro the dati_altro of this richiesta pubblic siti
	 */
	public void setDati_altro(String dati_altro);

	/**
	 * Returns the dati_autorizzaz of this richiesta pubblic siti.
	 *
	 * @return the dati_autorizzaz of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getDati_autorizzaz();

	/**
	 * Sets the dati_autorizzaz of this richiesta pubblic siti.
	 *
	 * @param dati_autorizzaz the dati_autorizzaz of this richiesta pubblic siti
	 */
	public void setDati_autorizzaz(String dati_autorizzaz);

	/**
	 * Returns the note_autorizzaz of this richiesta pubblic siti.
	 *
	 * @return the note_autorizzaz of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getNote_autorizzaz();

	/**
	 * Sets the note_autorizzaz of this richiesta pubblic siti.
	 *
	 * @param note_autorizzaz the note_autorizzaz of this richiesta pubblic siti
	 */
	public void setNote_autorizzaz(String note_autorizzaz);

	/**
	 * Returns the lista_allegati of this richiesta pubblic siti.
	 *
	 * @return the lista_allegati of this richiesta pubblic siti
	 */
	@AutoEscape
	public String getLista_allegati();

	/**
	 * Sets the lista_allegati of this richiesta pubblic siti.
	 *
	 * @param lista_allegati the lista_allegati of this richiesta pubblic siti
	 */
	public void setLista_allegati(String lista_allegati);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		service.intranet.mef.model.RichiestaPubblicSiti richiestaPubblicSiti);

	@Override
	public int hashCode();

	@Override
	public CacheModel<service.intranet.mef.model.RichiestaPubblicSiti> toCacheModel();

	@Override
	public service.intranet.mef.model.RichiestaPubblicSiti toEscapedModel();

	@Override
	public service.intranet.mef.model.RichiestaPubblicSiti toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}