/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the RichiesteHW service. Represents a row in the &quot;MFORM_RichiesteHW&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link service.intranet.mef.model.impl.RichiesteHWModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link service.intranet.mef.model.impl.RichiesteHWImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RichiesteHW
 * @see service.intranet.mef.model.impl.RichiesteHWImpl
 * @see service.intranet.mef.model.impl.RichiesteHWModelImpl
 * @generated
 */
@ProviderType
public interface RichiesteHWModel extends BaseModel<RichiesteHW> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a richieste h w model instance should use the {@link RichiesteHW} interface instead.
	 */

	/**
	 * Returns the primary key of this richieste h w.
	 *
	 * @return the primary key of this richieste h w
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this richieste h w.
	 *
	 * @param primaryKey the primary key of this richieste h w
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_richieste_hw of this richieste h w.
	 *
	 * @return the id_richieste_hw of this richieste h w
	 */
	public long getId_richieste_hw();

	/**
	 * Sets the id_richieste_hw of this richieste h w.
	 *
	 * @param id_richieste_hw the id_richieste_hw of this richieste h w
	 */
	public void setId_richieste_hw(long id_richieste_hw);

	/**
	 * Returns the utente of this richieste h w.
	 *
	 * @return the utente of this richieste h w
	 */
	@AutoEscape
	public String getUtente();

	/**
	 * Sets the utente of this richieste h w.
	 *
	 * @param utente the utente of this richieste h w
	 */
	public void setUtente(String utente);

	/**
	 * Returns the dettaglio of this richieste h w.
	 *
	 * @return the dettaglio of this richieste h w
	 */
	@AutoEscape
	public String getDettaglio();

	/**
	 * Sets the dettaglio of this richieste h w.
	 *
	 * @param dettaglio the dettaglio of this richieste h w
	 */
	public void setDettaglio(String dettaglio);

	/**
	 * Returns the data_richiesta of this richieste h w.
	 *
	 * @return the data_richiesta of this richieste h w
	 */
	public Date getData_richiesta();

	/**
	 * Sets the data_richiesta of this richieste h w.
	 *
	 * @param data_richiesta the data_richiesta of this richieste h w
	 */
	public void setData_richiesta(Date data_richiesta);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(service.intranet.mef.model.RichiesteHW richiesteHW);

	@Override
	public int hashCode();

	@Override
	public CacheModel<service.intranet.mef.model.RichiesteHW> toCacheModel();

	@Override
	public service.intranet.mef.model.RichiesteHW toEscapedModel();

	@Override
	public service.intranet.mef.model.RichiesteHW toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}