/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the TipologiaDispositivi service. Represents a row in the &quot;MFORM_TipologiaDispositivi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link service.intranet.mef.model.impl.TipologiaDispositiviModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link service.intranet.mef.model.impl.TipologiaDispositiviImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TipologiaDispositivi
 * @see service.intranet.mef.model.impl.TipologiaDispositiviImpl
 * @see service.intranet.mef.model.impl.TipologiaDispositiviModelImpl
 * @generated
 */
@ProviderType
public interface TipologiaDispositiviModel extends BaseModel<TipologiaDispositivi> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipologia dispositivi model instance should use the {@link TipologiaDispositivi} interface instead.
	 */

	/**
	 * Returns the primary key of this tipologia dispositivi.
	 *
	 * @return the primary key of this tipologia dispositivi
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tipologia dispositivi.
	 *
	 * @param primaryKey the primary key of this tipologia dispositivi
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_tipologia_dispositivi of this tipologia dispositivi.
	 *
	 * @return the id_tipologia_dispositivi of this tipologia dispositivi
	 */
	public long getId_tipologia_dispositivi();

	/**
	 * Sets the id_tipologia_dispositivi of this tipologia dispositivi.
	 *
	 * @param id_tipologia_dispositivi the id_tipologia_dispositivi of this tipologia dispositivi
	 */
	public void setId_tipologia_dispositivi(long id_tipologia_dispositivi);

	/**
	 * Returns the descrizione of this tipologia dispositivi.
	 *
	 * @return the descrizione of this tipologia dispositivi
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this tipologia dispositivi.
	 *
	 * @param descrizione the descrizione of this tipologia dispositivi
	 */
	public void setDescrizione(String descrizione);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		service.intranet.mef.model.TipologiaDispositivi tipologiaDispositivi);

	@Override
	public int hashCode();

	@Override
	public CacheModel<service.intranet.mef.model.TipologiaDispositivi> toCacheModel();

	@Override
	public service.intranet.mef.model.TipologiaDispositivi toEscapedModel();

	@Override
	public service.intranet.mef.model.TipologiaDispositivi toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}