package it.tesoro.geco.geco_webservice.services.richiestabfcservice;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.0
 * 2017-12-05T18:47:07.801+01:00
 * Generated source version: 3.2.0
 * 
 */
@WebServiceClient(name = "RichiestaBFCServiceService", 
                  wsdlLocation = "http://geco.tesoro.it/geco-webservice/services/RichiestaBFCService?wsdl",
                  targetNamespace = "http://geco.tesoro.it/geco-webservice/services/RichiestaBFCService") 
public class RichiestaBFCServiceService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://geco.tesoro.it/geco-webservice/services/RichiestaBFCService", "RichiestaBFCServiceService");
    public final static QName RichiestaBFCService = new QName("http://geco.tesoro.it/geco-webservice/services/RichiestaBFCService", "RichiestaBFCService");
    static {
        URL url = null;
        try {
            url = new URL("http://geco.tesoro.it/geco-webservice/services/RichiestaBFCService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(RichiestaBFCServiceService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://geco.tesoro.it/geco-webservice/services/RichiestaBFCService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public RichiestaBFCServiceService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public RichiestaBFCServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RichiestaBFCServiceService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public RichiestaBFCServiceService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public RichiestaBFCServiceService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public RichiestaBFCServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns RichiestaBFCService
     */
    @WebEndpoint(name = "RichiestaBFCService")
    public RichiestaBFCService getRichiestaBFCService() {
        return super.getPort(RichiestaBFCService, RichiestaBFCService.class);
    }
    
    @WebEndpoint(name = "RichiestaBFCService")
    public RichiestaBFCService getRichiestaBFCService(QName RichiestaBFCService) {
        return super.getPort(RichiestaBFCService, RichiestaBFCService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RichiestaBFCService
     */
    @WebEndpoint(name = "RichiestaBFCService")
    public RichiestaBFCService getRichiestaBFCService(WebServiceFeature... features) {
        return super.getPort(RichiestaBFCService, RichiestaBFCService.class, features);
    }

}
