/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.job.siap.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ClassificationLevel service. Represents a row in the &quot;LF_LIVELLO_INQ&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.job.siap.model.impl.ClassificationLevelModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.job.siap.model.impl.ClassificationLevelImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ClassificationLevel
 * @see com.intranet.mef.job.siap.model.impl.ClassificationLevelImpl
 * @see com.intranet.mef.job.siap.model.impl.ClassificationLevelModelImpl
 * @generated
 */
@ProviderType
public interface ClassificationLevelModel extends BaseModel<ClassificationLevel> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a classification level model instance should use the {@link ClassificationLevel} interface instead.
	 */

	/**
	 * Returns the primary key of this classification level.
	 *
	 * @return the primary key of this classification level
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this classification level.
	 *
	 * @param primaryKey the primary key of this classification level
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the level i d of this classification level.
	 *
	 * @return the level i d of this classification level
	 */
	public long getLevelID();

	/**
	 * Sets the level i d of this classification level.
	 *
	 * @param levelID the level i d of this classification level
	 */
	public void setLevelID(long levelID);

	/**
	 * Returns the cod legal pos of this classification level.
	 *
	 * @return the cod legal pos of this classification level
	 */
	@AutoEscape
	public String getCodLegalPos();

	/**
	 * Sets the cod legal pos of this classification level.
	 *
	 * @param codLegalPos the cod legal pos of this classification level
	 */
	public void setCodLegalPos(String codLegalPos);

	/**
	 * Returns the desc legal pos of this classification level.
	 *
	 * @return the desc legal pos of this classification level
	 */
	@AutoEscape
	public String getDescLegalPos();

	/**
	 * Sets the desc legal pos of this classification level.
	 *
	 * @param descLegalPos the desc legal pos of this classification level
	 */
	public void setDescLegalPos(String descLegalPos);

	/**
	 * Returns the cod economic pos of this classification level.
	 *
	 * @return the cod economic pos of this classification level
	 */
	@AutoEscape
	public String getCodEconomicPos();

	/**
	 * Sets the cod economic pos of this classification level.
	 *
	 * @param codEconomicPos the cod economic pos of this classification level
	 */
	public void setCodEconomicPos(String codEconomicPos);

	/**
	 * Returns the desc economic pos of this classification level.
	 *
	 * @return the desc economic pos of this classification level
	 */
	@AutoEscape
	public String getDescEconomicPos();

	/**
	 * Sets the desc economic pos of this classification level.
	 *
	 * @param descEconomicPos the desc economic pos of this classification level
	 */
	public void setDescEconomicPos(String descEconomicPos);

	/**
	 * Returns the area of this classification level.
	 *
	 * @return the area of this classification level
	 */
	@AutoEscape
	public String getArea();

	/**
	 * Sets the area of this classification level.
	 *
	 * @param area the area of this classification level
	 */
	public void setArea(String area);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ClassificationLevel classificationLevel);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ClassificationLevel> toCacheModel();

	@Override
	public ClassificationLevel toEscapedModel();

	@Override
	public ClassificationLevel toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}