/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.job.siap.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the OvertimePrevMonthPayOff service. Represents a row in the &quot;LF_VIEW_LIQUIDATO_MESE_PREC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.job.siap.model.impl.OvertimePrevMonthPayOffModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.job.siap.model.impl.OvertimePrevMonthPayOffImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OvertimePrevMonthPayOff
 * @see com.intranet.mef.job.siap.model.impl.OvertimePrevMonthPayOffImpl
 * @see com.intranet.mef.job.siap.model.impl.OvertimePrevMonthPayOffModelImpl
 * @generated
 */
@ProviderType
public interface OvertimePrevMonthPayOffModel extends BaseModel<OvertimePrevMonthPayOff> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a overtime prev month pay off model instance should use the {@link OvertimePrevMonthPayOff} interface instead.
	 */

	/**
	 * Returns the primary key of this overtime prev month pay off.
	 *
	 * @return the primary key of this overtime prev month pay off
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this overtime prev month pay off.
	 *
	 * @param primaryKey the primary key of this overtime prev month pay off
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the person ID of this overtime prev month pay off.
	 *
	 * @return the person ID of this overtime prev month pay off
	 */
	public long getPersonId();

	/**
	 * Sets the person ID of this overtime prev month pay off.
	 *
	 * @param personId the person ID of this overtime prev month pay off
	 */
	public void setPersonId(long personId);

	/**
	 * Returns the overtime hours curr pay off of this overtime prev month pay off.
	 *
	 * @return the overtime hours curr pay off of this overtime prev month pay off
	 */
	public int getOvertimeHoursCurrPayOff();

	/**
	 * Sets the overtime hours curr pay off of this overtime prev month pay off.
	 *
	 * @param overtimeHoursCurrPayOff the overtime hours curr pay off of this overtime prev month pay off
	 */
	public void setOvertimeHoursCurrPayOff(int overtimeHoursCurrPayOff);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(OvertimePrevMonthPayOff overtimePrevMonthPayOff);

	@Override
	public int hashCode();

	@Override
	public CacheModel<OvertimePrevMonthPayOff> toCacheModel();

	@Override
	public OvertimePrevMonthPayOff toEscapedModel();

	@Override
	public OvertimePrevMonthPayOff toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}