/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.job.siap.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.sql.Blob;

/**
 * The base model interface for the ProfilePicture service. Represents a row in the &quot;LF_PHOTO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.job.siap.model.impl.ProfilePictureModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.job.siap.model.impl.ProfilePictureImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProfilePicture
 * @see com.intranet.mef.job.siap.model.impl.ProfilePictureImpl
 * @see com.intranet.mef.job.siap.model.impl.ProfilePictureModelImpl
 * @generated
 */
@ProviderType
public interface ProfilePictureModel extends BaseModel<ProfilePicture> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a profile picture model instance should use the {@link ProfilePicture} interface instead.
	 */

	/**
	 * Returns the primary key of this profile picture.
	 *
	 * @return the primary key of this profile picture
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this profile picture.
	 *
	 * @param primaryKey the primary key of this profile picture
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the person i d of this profile picture.
	 *
	 * @return the person i d of this profile picture
	 */
	public long getPersonID();

	/**
	 * Sets the person i d of this profile picture.
	 *
	 * @param personID the person i d of this profile picture
	 */
	public void setPersonID(long personID);

	/**
	 * Returns the file of this profile picture.
	 *
	 * @return the file of this profile picture
	 */
	public Blob getFile();

	/**
	 * Sets the file of this profile picture.
	 *
	 * @param file the file of this profile picture
	 */
	public void setFile(Blob file);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(ProfilePicture profilePicture);

	@Override
	public int hashCode();

	@Override
	public CacheModel<ProfilePicture> toCacheModel();

	@Override
	public ProfilePicture toEscapedModel();

	@Override
	public ProfilePicture toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}