/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.richieste.badge.mef.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import servizio.richieste.badge.mef.model.OggettoRichiesta;
import servizio.richieste.badge.mef.model.OggettoRichiestaModel;
import servizio.richieste.badge.mef.model.OggettoRichiestaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the OggettoRichiesta service. Represents a row in the &quot;MBADGE_OggettoRichiesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link OggettoRichiestaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link OggettoRichiestaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see OggettoRichiestaImpl
 * @see OggettoRichiesta
 * @see OggettoRichiestaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class OggettoRichiestaModelImpl extends BaseModelImpl<OggettoRichiesta>
	implements OggettoRichiestaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a oggetto richiesta model instance should use the {@link OggettoRichiesta} interface instead.
	 */
	public static final String TABLE_NAME = "MBADGE_OggettoRichiesta";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_oggetto", Types.BIGINT },
			{ "descrizione_oggetto", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_oggetto", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("descrizione_oggetto", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MBADGE_OggettoRichiesta (id_oggetto LONG not null primary key,descrizione_oggetto VARCHAR(100) null)";
	public static final String TABLE_SQL_DROP = "drop table MBADGE_OggettoRichiesta";
	public static final String ORDER_BY_JPQL = " ORDER BY oggettoRichiesta.id_oggetto ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MBADGE_OggettoRichiesta.id_oggetto ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(servizio.richieste.badge.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.servizio.richieste.badge.mef.model.OggettoRichiesta"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(servizio.richieste.badge.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.servizio.richieste.badge.mef.model.OggettoRichiesta"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static OggettoRichiesta toModel(OggettoRichiestaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		OggettoRichiesta model = new OggettoRichiestaImpl();

		model.setId_oggetto(soapModel.getId_oggetto());
		model.setDescrizione_oggetto(soapModel.getDescrizione_oggetto());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<OggettoRichiesta> toModels(
		OggettoRichiestaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<OggettoRichiesta> models = new ArrayList<OggettoRichiesta>(soapModels.length);

		for (OggettoRichiestaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(servizio.richieste.badge.mef.service.util.PropsUtil.get(
				"lock.expiration.time.servizio.richieste.badge.mef.model.OggettoRichiesta"));

	public OggettoRichiestaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_oggetto;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_oggetto(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_oggetto;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return OggettoRichiesta.class;
	}

	@Override
	public String getModelClassName() {
		return OggettoRichiesta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_oggetto", getId_oggetto());
		attributes.put("descrizione_oggetto", getDescrizione_oggetto());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_oggetto = (Long)attributes.get("id_oggetto");

		if (id_oggetto != null) {
			setId_oggetto(id_oggetto);
		}

		String descrizione_oggetto = (String)attributes.get(
				"descrizione_oggetto");

		if (descrizione_oggetto != null) {
			setDescrizione_oggetto(descrizione_oggetto);
		}
	}

	@JSON
	@Override
	public long getId_oggetto() {
		return _id_oggetto;
	}

	@Override
	public void setId_oggetto(long id_oggetto) {
		_id_oggetto = id_oggetto;
	}

	@JSON
	@Override
	public String getDescrizione_oggetto() {
		if (_descrizione_oggetto == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizione_oggetto;
		}
	}

	@Override
	public void setDescrizione_oggetto(String descrizione_oggetto) {
		_descrizione_oggetto = descrizione_oggetto;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			OggettoRichiesta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public OggettoRichiesta toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (OggettoRichiesta)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		OggettoRichiestaImpl oggettoRichiestaImpl = new OggettoRichiestaImpl();

		oggettoRichiestaImpl.setId_oggetto(getId_oggetto());
		oggettoRichiestaImpl.setDescrizione_oggetto(getDescrizione_oggetto());

		oggettoRichiestaImpl.resetOriginalValues();

		return oggettoRichiestaImpl;
	}

	@Override
	public int compareTo(OggettoRichiesta oggettoRichiesta) {
		long primaryKey = oggettoRichiesta.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof OggettoRichiesta)) {
			return false;
		}

		OggettoRichiesta oggettoRichiesta = (OggettoRichiesta)obj;

		long primaryKey = oggettoRichiesta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<OggettoRichiesta> toCacheModel() {
		OggettoRichiestaCacheModel oggettoRichiestaCacheModel = new OggettoRichiestaCacheModel();

		oggettoRichiestaCacheModel.id_oggetto = getId_oggetto();

		oggettoRichiestaCacheModel.descrizione_oggetto = getDescrizione_oggetto();

		String descrizione_oggetto = oggettoRichiestaCacheModel.descrizione_oggetto;

		if ((descrizione_oggetto != null) &&
				(descrizione_oggetto.length() == 0)) {
			oggettoRichiestaCacheModel.descrizione_oggetto = null;
		}

		return oggettoRichiestaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id_oggetto=");
		sb.append(getId_oggetto());
		sb.append(", descrizione_oggetto=");
		sb.append(getDescrizione_oggetto());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("servizio.richieste.badge.mef.model.OggettoRichiesta");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_oggetto</column-name><column-value><![CDATA[");
		sb.append(getId_oggetto());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizione_oggetto</column-name><column-value><![CDATA[");
		sb.append(getDescrizione_oggetto());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = OggettoRichiesta.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			OggettoRichiesta.class
		};
	private long _id_oggetto;
	private String _descrizione_oggetto;
	private OggettoRichiesta _escapedModel;
}