/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.richieste.badge.mef.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import servizio.richieste.badge.mef.model.StatoRichiesta;
import servizio.richieste.badge.mef.model.StatoRichiestaModel;
import servizio.richieste.badge.mef.model.StatoRichiestaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the StatoRichiesta service. Represents a row in the &quot;MBADGE_StatoRichiesta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link StatoRichiestaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatoRichiestaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StatoRichiestaImpl
 * @see StatoRichiesta
 * @see StatoRichiestaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class StatoRichiestaModelImpl extends BaseModelImpl<StatoRichiesta>
	implements StatoRichiestaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a stato richiesta model instance should use the {@link StatoRichiesta} interface instead.
	 */
	public static final String TABLE_NAME = "MBADGE_StatoRichiesta";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_stato", Types.BIGINT },
			{ "descrizione_stato", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_stato", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("descrizione_stato", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MBADGE_StatoRichiesta (id_stato LONG not null primary key,descrizione_stato VARCHAR(100) null)";
	public static final String TABLE_SQL_DROP = "drop table MBADGE_StatoRichiesta";
	public static final String ORDER_BY_JPQL = " ORDER BY statoRichiesta.id_stato ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MBADGE_StatoRichiesta.id_stato ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(servizio.richieste.badge.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.servizio.richieste.badge.mef.model.StatoRichiesta"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(servizio.richieste.badge.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.servizio.richieste.badge.mef.model.StatoRichiesta"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(servizio.richieste.badge.mef.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.servizio.richieste.badge.mef.model.StatoRichiesta"),
			true);
	public static final long DESCRIZIONE_STATO_COLUMN_BITMASK = 1L;
	public static final long ID_STATO_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static StatoRichiesta toModel(StatoRichiestaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		StatoRichiesta model = new StatoRichiestaImpl();

		model.setId_stato(soapModel.getId_stato());
		model.setDescrizione_stato(soapModel.getDescrizione_stato());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<StatoRichiesta> toModels(StatoRichiestaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<StatoRichiesta> models = new ArrayList<StatoRichiesta>(soapModels.length);

		for (StatoRichiestaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(servizio.richieste.badge.mef.service.util.PropsUtil.get(
				"lock.expiration.time.servizio.richieste.badge.mef.model.StatoRichiesta"));

	public StatoRichiestaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_stato;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_stato(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_stato;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StatoRichiesta.class;
	}

	@Override
	public String getModelClassName() {
		return StatoRichiesta.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_stato", getId_stato());
		attributes.put("descrizione_stato", getDescrizione_stato());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_stato = (Long)attributes.get("id_stato");

		if (id_stato != null) {
			setId_stato(id_stato);
		}

		String descrizione_stato = (String)attributes.get("descrizione_stato");

		if (descrizione_stato != null) {
			setDescrizione_stato(descrizione_stato);
		}
	}

	@JSON
	@Override
	public long getId_stato() {
		return _id_stato;
	}

	@Override
	public void setId_stato(long id_stato) {
		_id_stato = id_stato;
	}

	@JSON
	@Override
	public String getDescrizione_stato() {
		if (_descrizione_stato == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizione_stato;
		}
	}

	@Override
	public void setDescrizione_stato(String descrizione_stato) {
		_columnBitmask |= DESCRIZIONE_STATO_COLUMN_BITMASK;

		if (_originalDescrizione_stato == null) {
			_originalDescrizione_stato = _descrizione_stato;
		}

		_descrizione_stato = descrizione_stato;
	}

	public String getOriginalDescrizione_stato() {
		return GetterUtil.getString(_originalDescrizione_stato);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			StatoRichiesta.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StatoRichiesta toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StatoRichiesta)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StatoRichiestaImpl statoRichiestaImpl = new StatoRichiestaImpl();

		statoRichiestaImpl.setId_stato(getId_stato());
		statoRichiestaImpl.setDescrizione_stato(getDescrizione_stato());

		statoRichiestaImpl.resetOriginalValues();

		return statoRichiestaImpl;
	}

	@Override
	public int compareTo(StatoRichiesta statoRichiesta) {
		long primaryKey = statoRichiesta.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StatoRichiesta)) {
			return false;
		}

		StatoRichiesta statoRichiesta = (StatoRichiesta)obj;

		long primaryKey = statoRichiesta.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		StatoRichiestaModelImpl statoRichiestaModelImpl = this;

		statoRichiestaModelImpl._originalDescrizione_stato = statoRichiestaModelImpl._descrizione_stato;

		statoRichiestaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<StatoRichiesta> toCacheModel() {
		StatoRichiestaCacheModel statoRichiestaCacheModel = new StatoRichiestaCacheModel();

		statoRichiestaCacheModel.id_stato = getId_stato();

		statoRichiestaCacheModel.descrizione_stato = getDescrizione_stato();

		String descrizione_stato = statoRichiestaCacheModel.descrizione_stato;

		if ((descrizione_stato != null) && (descrizione_stato.length() == 0)) {
			statoRichiestaCacheModel.descrizione_stato = null;
		}

		return statoRichiestaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id_stato=");
		sb.append(getId_stato());
		sb.append(", descrizione_stato=");
		sb.append(getDescrizione_stato());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("servizio.richieste.badge.mef.model.StatoRichiesta");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_stato</column-name><column-value><![CDATA[");
		sb.append(getId_stato());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizione_stato</column-name><column-value><![CDATA[");
		sb.append(getDescrizione_stato());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = StatoRichiesta.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			StatoRichiesta.class
		};
	private long _id_stato;
	private String _descrizione_stato;
	private String _originalDescrizione_stato;
	private long _columnBitmask;
	private StatoRichiesta _escapedModel;
}