/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.job.siap.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.intranet.mef.job.siap.model.Vacation;
import com.intranet.mef.job.siap.model.VacationModel;
import com.intranet.mef.job.siap.model.VacationSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Vacation service. Represents a row in the &quot;LF_VIEW_FERIE&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link VacationModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link VacationImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see VacationImpl
 * @see Vacation
 * @see VacationModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class VacationModelImpl extends BaseModelImpl<Vacation>
	implements VacationModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a vacation model instance should use the {@link Vacation} interface instead.
	 */
	public static final String TABLE_NAME = "LF_VIEW_FERIE";
	public static final Object[][] TABLE_COLUMNS = {
			{ "PERSON_ID", Types.BIGINT },
			{ "FERIE_ANNO_CORR", Types.INTEGER },
			{ "FERIE_ANNO_PREC", Types.INTEGER },
			{ "FERIE_USUFRUITE", Types.INTEGER },
			{ "FERIE_RESIDUE", Types.INTEGER }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("PERSON_ID", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FERIE_ANNO_CORR", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FERIE_ANNO_PREC", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FERIE_USUFRUITE", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("FERIE_RESIDUE", Types.INTEGER);
	}

	public static final String TABLE_SQL_CREATE = "create table LF_VIEW_FERIE (PERSON_ID LONG not null primary key,FERIE_ANNO_CORR INTEGER,FERIE_ANNO_PREC INTEGER,FERIE_USUFRUITE INTEGER,FERIE_RESIDUE INTEGER)";
	public static final String TABLE_SQL_DROP = "drop table LF_VIEW_FERIE";
	public static final String ORDER_BY_JPQL = " ORDER BY vacation.personId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY LF_VIEW_FERIE.PERSON_ID ASC";
	public static final String DATA_SOURCE = "stage";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.intranet.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.intranet.mef.job.siap.model.Vacation"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.intranet.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.intranet.mef.job.siap.model.Vacation"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Vacation toModel(VacationSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Vacation model = new VacationImpl();

		model.setPersonId(soapModel.getPersonId());
		model.setVacationCurrYear(soapModel.getVacationCurrYear());
		model.setVacationPrevYear(soapModel.getVacationPrevYear());
		model.setVacationSpent(soapModel.getVacationSpent());
		model.setVacationRemaining(soapModel.getVacationRemaining());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Vacation> toModels(VacationSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Vacation> models = new ArrayList<Vacation>(soapModels.length);

		for (VacationSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.intranet.mef.service.util.PropsUtil.get(
				"lock.expiration.time.com.intranet.mef.job.siap.model.Vacation"));

	public VacationModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _personId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setPersonId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _personId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Vacation.class;
	}

	@Override
	public String getModelClassName() {
		return Vacation.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("personId", getPersonId());
		attributes.put("vacationCurrYear", getVacationCurrYear());
		attributes.put("vacationPrevYear", getVacationPrevYear());
		attributes.put("vacationSpent", getVacationSpent());
		attributes.put("vacationRemaining", getVacationRemaining());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long personId = (Long)attributes.get("personId");

		if (personId != null) {
			setPersonId(personId);
		}

		Integer vacationCurrYear = (Integer)attributes.get("vacationCurrYear");

		if (vacationCurrYear != null) {
			setVacationCurrYear(vacationCurrYear);
		}

		Integer vacationPrevYear = (Integer)attributes.get("vacationPrevYear");

		if (vacationPrevYear != null) {
			setVacationPrevYear(vacationPrevYear);
		}

		Integer vacationSpent = (Integer)attributes.get("vacationSpent");

		if (vacationSpent != null) {
			setVacationSpent(vacationSpent);
		}

		Integer vacationRemaining = (Integer)attributes.get("vacationRemaining");

		if (vacationRemaining != null) {
			setVacationRemaining(vacationRemaining);
		}
	}

	@JSON
	@Override
	public long getPersonId() {
		return _personId;
	}

	@Override
	public void setPersonId(long personId) {
		_personId = personId;
	}

	@JSON
	@Override
	public int getVacationCurrYear() {
		return _vacationCurrYear;
	}

	@Override
	public void setVacationCurrYear(int vacationCurrYear) {
		_vacationCurrYear = vacationCurrYear;
	}

	@JSON
	@Override
	public int getVacationPrevYear() {
		return _vacationPrevYear;
	}

	@Override
	public void setVacationPrevYear(int vacationPrevYear) {
		_vacationPrevYear = vacationPrevYear;
	}

	@JSON
	@Override
	public int getVacationSpent() {
		return _vacationSpent;
	}

	@Override
	public void setVacationSpent(int vacationSpent) {
		_vacationSpent = vacationSpent;
	}

	@JSON
	@Override
	public int getVacationRemaining() {
		return _vacationRemaining;
	}

	@Override
	public void setVacationRemaining(int vacationRemaining) {
		_vacationRemaining = vacationRemaining;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Vacation.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Vacation toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Vacation)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		VacationImpl vacationImpl = new VacationImpl();

		vacationImpl.setPersonId(getPersonId());
		vacationImpl.setVacationCurrYear(getVacationCurrYear());
		vacationImpl.setVacationPrevYear(getVacationPrevYear());
		vacationImpl.setVacationSpent(getVacationSpent());
		vacationImpl.setVacationRemaining(getVacationRemaining());

		vacationImpl.resetOriginalValues();

		return vacationImpl;
	}

	@Override
	public int compareTo(Vacation vacation) {
		long primaryKey = vacation.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Vacation)) {
			return false;
		}

		Vacation vacation = (Vacation)obj;

		long primaryKey = vacation.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Vacation> toCacheModel() {
		VacationCacheModel vacationCacheModel = new VacationCacheModel();

		vacationCacheModel.personId = getPersonId();

		vacationCacheModel.vacationCurrYear = getVacationCurrYear();

		vacationCacheModel.vacationPrevYear = getVacationPrevYear();

		vacationCacheModel.vacationSpent = getVacationSpent();

		vacationCacheModel.vacationRemaining = getVacationRemaining();

		return vacationCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{personId=");
		sb.append(getPersonId());
		sb.append(", vacationCurrYear=");
		sb.append(getVacationCurrYear());
		sb.append(", vacationPrevYear=");
		sb.append(getVacationPrevYear());
		sb.append(", vacationSpent=");
		sb.append(getVacationSpent());
		sb.append(", vacationRemaining=");
		sb.append(getVacationRemaining());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("com.intranet.mef.job.siap.model.Vacation");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>personId</column-name><column-value><![CDATA[");
		sb.append(getPersonId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vacationCurrYear</column-name><column-value><![CDATA[");
		sb.append(getVacationCurrYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vacationPrevYear</column-name><column-value><![CDATA[");
		sb.append(getVacationPrevYear());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vacationSpent</column-name><column-value><![CDATA[");
		sb.append(getVacationSpent());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>vacationRemaining</column-name><column-value><![CDATA[");
		sb.append(getVacationRemaining());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Vacation.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Vacation.class
		};
	private long _personId;
	private int _vacationCurrYear;
	private int _vacationPrevYear;
	private int _vacationSpent;
	private int _vacationRemaining;
	private Vacation _escapedModel;
}