/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.richieste.badge.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the AnaDipExt service. Represents a row in the &quot;MBADGE_AnaDipExt&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servizio.richieste.badge.mef.model.impl.AnaDipExtModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servizio.richieste.badge.mef.model.impl.AnaDipExtImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AnaDipExt
 * @see servizio.richieste.badge.mef.model.impl.AnaDipExtImpl
 * @see servizio.richieste.badge.mef.model.impl.AnaDipExtModelImpl
 * @generated
 */
@ProviderType
public interface AnaDipExtModel extends BaseModel<AnaDipExt> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a ana dip ext model instance should use the {@link AnaDipExt} interface instead.
	 */

	/**
	 * Returns the primary key of this ana dip ext.
	 *
	 * @return the primary key of this ana dip ext
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this ana dip ext.
	 *
	 * @param primaryKey the primary key of this ana dip ext
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_dip_ext of this ana dip ext.
	 *
	 * @return the id_dip_ext of this ana dip ext
	 */
	public long getId_dip_ext();

	/**
	 * Sets the id_dip_ext of this ana dip ext.
	 *
	 * @param id_dip_ext the id_dip_ext of this ana dip ext
	 */
	public void setId_dip_ext(long id_dip_ext);

	/**
	 * Returns the nome_dip_ext of this ana dip ext.
	 *
	 * @return the nome_dip_ext of this ana dip ext
	 */
	@AutoEscape
	public String getNome_dip_ext();

	/**
	 * Sets the nome_dip_ext of this ana dip ext.
	 *
	 * @param nome_dip_ext the nome_dip_ext of this ana dip ext
	 */
	public void setNome_dip_ext(String nome_dip_ext);

	/**
	 * Returns the cognome_dip_ext of this ana dip ext.
	 *
	 * @return the cognome_dip_ext of this ana dip ext
	 */
	@AutoEscape
	public String getCognome_dip_ext();

	/**
	 * Sets the cognome_dip_ext of this ana dip ext.
	 *
	 * @param cognome_dip_ext the cognome_dip_ext of this ana dip ext
	 */
	public void setCognome_dip_ext(String cognome_dip_ext);

	/**
	 * Returns the cf_dip_ext of this ana dip ext.
	 *
	 * @return the cf_dip_ext of this ana dip ext
	 */
	@AutoEscape
	public String getCf_dip_ext();

	/**
	 * Sets the cf_dip_ext of this ana dip ext.
	 *
	 * @param cf_dip_ext the cf_dip_ext of this ana dip ext
	 */
	public void setCf_dip_ext(String cf_dip_ext);

	/**
	 * Returns the luogonascita_dip_ext of this ana dip ext.
	 *
	 * @return the luogonascita_dip_ext of this ana dip ext
	 */
	@AutoEscape
	public String getLuogonascita_dip_ext();

	/**
	 * Sets the luogonascita_dip_ext of this ana dip ext.
	 *
	 * @param luogonascita_dip_ext the luogonascita_dip_ext of this ana dip ext
	 */
	public void setLuogonascita_dip_ext(String luogonascita_dip_ext);

	/**
	 * Returns the datanascita_dip_ext of this ana dip ext.
	 *
	 * @return the datanascita_dip_ext of this ana dip ext
	 */
	public Date getDatanascita_dip_ext();

	/**
	 * Sets the datanascita_dip_ext of this ana dip ext.
	 *
	 * @param datanascita_dip_ext the datanascita_dip_ext of this ana dip ext
	 */
	public void setDatanascita_dip_ext(Date datanascita_dip_ext);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(servizio.richieste.badge.mef.model.AnaDipExt anaDipExt);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servizio.richieste.badge.mef.model.AnaDipExt> toCacheModel();

	@Override
	public servizio.richieste.badge.mef.model.AnaDipExt toEscapedModel();

	@Override
	public servizio.richieste.badge.mef.model.AnaDipExt toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}