/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.richieste.badge.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the GestioneUtenti service. Represents a row in the &quot;MBADGE_GestioneUtenti&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servizio.richieste.badge.mef.model.impl.GestioneUtentiModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servizio.richieste.badge.mef.model.impl.GestioneUtentiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see GestioneUtenti
 * @see servizio.richieste.badge.mef.model.impl.GestioneUtentiImpl
 * @see servizio.richieste.badge.mef.model.impl.GestioneUtentiModelImpl
 * @generated
 */
@ProviderType
public interface GestioneUtentiModel extends BaseModel<GestioneUtenti> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a gestione utenti model instance should use the {@link GestioneUtenti} interface instead.
	 */

	/**
	 * Returns the primary key of this gestione utenti.
	 *
	 * @return the primary key of this gestione utenti
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this gestione utenti.
	 *
	 * @param primaryKey the primary key of this gestione utenti
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_gest_utenti of this gestione utenti.
	 *
	 * @return the id_gest_utenti of this gestione utenti
	 */
	public long getId_gest_utenti();

	/**
	 * Sets the id_gest_utenti of this gestione utenti.
	 *
	 * @param id_gest_utenti the id_gest_utenti of this gestione utenti
	 */
	public void setId_gest_utenti(long id_gest_utenti);

	/**
	 * Returns the data of this gestione utenti.
	 *
	 * @return the data of this gestione utenti
	 */
	public Date getData();

	/**
	 * Sets the data of this gestione utenti.
	 *
	 * @param data the data of this gestione utenti
	 */
	public void setData(Date data);

	/**
	 * Returns the screename_dirigente of this gestione utenti.
	 *
	 * @return the screename_dirigente of this gestione utenti
	 */
	@AutoEscape
	public String getScreename_dirigente();

	/**
	 * Sets the screename_dirigente of this gestione utenti.
	 *
	 * @param screename_dirigente the screename_dirigente of this gestione utenti
	 */
	public void setScreename_dirigente(String screename_dirigente);

	/**
	 * Returns the screename_utente of this gestione utenti.
	 *
	 * @return the screename_utente of this gestione utenti
	 */
	@AutoEscape
	public String getScreename_utente();

	/**
	 * Sets the screename_utente of this gestione utenti.
	 *
	 * @param screename_utente the screename_utente of this gestione utenti
	 */
	public void setScreename_utente(String screename_utente);

	/**
	 * Returns the id_ufficio of this gestione utenti.
	 *
	 * @return the id_ufficio of this gestione utenti
	 */
	public long getId_ufficio();

	/**
	 * Sets the id_ufficio of this gestione utenti.
	 *
	 * @param id_ufficio the id_ufficio of this gestione utenti
	 */
	public void setId_ufficio(long id_ufficio);

	/**
	 * Returns the abilitazione of this gestione utenti.
	 *
	 * @return the abilitazione of this gestione utenti
	 */
	public boolean getAbilitazione();

	/**
	 * Returns <code>true</code> if this gestione utenti is abilitazione.
	 *
	 * @return <code>true</code> if this gestione utenti is abilitazione; <code>false</code> otherwise
	 */
	public boolean isAbilitazione();

	/**
	 * Sets whether this gestione utenti is abilitazione.
	 *
	 * @param abilitazione the abilitazione of this gestione utenti
	 */
	public void setAbilitazione(boolean abilitazione);

	/**
	 * Returns the delega of this gestione utenti.
	 *
	 * @return the delega of this gestione utenti
	 */
	public boolean getDelega();

	/**
	 * Returns <code>true</code> if this gestione utenti is delega.
	 *
	 * @return <code>true</code> if this gestione utenti is delega; <code>false</code> otherwise
	 */
	public boolean isDelega();

	/**
	 * Sets whether this gestione utenti is delega.
	 *
	 * @param delega the delega of this gestione utenti
	 */
	public void setDelega(boolean delega);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		servizio.richieste.badge.mef.model.GestioneUtenti gestioneUtenti);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servizio.richieste.badge.mef.model.GestioneUtenti> toCacheModel();

	@Override
	public servizio.richieste.badge.mef.model.GestioneUtenti toEscapedModel();

	@Override
	public servizio.richieste.badge.mef.model.GestioneUtenti toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}