/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.richieste.badge.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the SediEsterne service. Represents a row in the &quot;MBADGE_SediEsterne&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servizio.richieste.badge.mef.model.impl.SediEsterneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servizio.richieste.badge.mef.model.impl.SediEsterneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SediEsterne
 * @see servizio.richieste.badge.mef.model.impl.SediEsterneImpl
 * @see servizio.richieste.badge.mef.model.impl.SediEsterneModelImpl
 * @generated
 */
@ProviderType
public interface SediEsterneModel extends BaseModel<SediEsterne> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sedi esterne model instance should use the {@link SediEsterne} interface instead.
	 */

	/**
	 * Returns the primary key of this sedi esterne.
	 *
	 * @return the primary key of this sedi esterne
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sedi esterne.
	 *
	 * @param primaryKey the primary key of this sedi esterne
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_sede_esterna of this sedi esterne.
	 *
	 * @return the id_sede_esterna of this sedi esterne
	 */
	public long getId_sede_esterna();

	/**
	 * Sets the id_sede_esterna of this sedi esterne.
	 *
	 * @param id_sede_esterna the id_sede_esterna of this sedi esterne
	 */
	public void setId_sede_esterna(long id_sede_esterna);

	/**
	 * Returns the nome_sede_esterna of this sedi esterne.
	 *
	 * @return the nome_sede_esterna of this sedi esterne
	 */
	@AutoEscape
	public String getNome_sede_esterna();

	/**
	 * Sets the nome_sede_esterna of this sedi esterne.
	 *
	 * @param nome_sede_esterna the nome_sede_esterna of this sedi esterne
	 */
	public void setNome_sede_esterna(String nome_sede_esterna);

	/**
	 * Returns the id_sedesiap of this sedi esterne.
	 *
	 * @return the id_sedesiap of this sedi esterne
	 */
	public long getId_sedesiap();

	/**
	 * Sets the id_sedesiap of this sedi esterne.
	 *
	 * @param id_sedesiap the id_sedesiap of this sedi esterne
	 */
	public void setId_sedesiap(long id_sedesiap);

	/**
	 * Returns the acronimo_sede of this sedi esterne.
	 *
	 * @return the acronimo_sede of this sedi esterne
	 */
	@AutoEscape
	public String getAcronimo_sede();

	/**
	 * Sets the acronimo_sede of this sedi esterne.
	 *
	 * @param acronimo_sede the acronimo_sede of this sedi esterne
	 */
	public void setAcronimo_sede(String acronimo_sede);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		servizio.richieste.badge.mef.model.SediEsterne sediEsterne);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servizio.richieste.badge.mef.model.SediEsterne> toCacheModel();

	@Override
	public servizio.richieste.badge.mef.model.SediEsterne toEscapedModel();

	@Override
	public servizio.richieste.badge.mef.model.SediEsterne toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}