/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.accenture.lavoro.agile.istanza.mef.service.base;

import com.accenture.lavoro.agile.istanza.mef.model.OpzioneRich;
import com.accenture.lavoro.agile.istanza.mef.service.OpzioneRichService;
import com.accenture.lavoro.agile.istanza.mef.service.persistence.EmailPersistence;
import com.accenture.lavoro.agile.istanza.mef.service.persistence.OpzioneRichPersistence;
import com.accenture.lavoro.agile.istanza.mef.service.persistence.RichLavAgileFinder;
import com.accenture.lavoro.agile.istanza.mef.service.persistence.RichLavAgilePersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the opzione rich remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.accenture.lavoro.agile.istanza.mef.service.impl.OpzioneRichServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.accenture.lavoro.agile.istanza.mef.service.impl.OpzioneRichServiceImpl
 * @see com.accenture.lavoro.agile.istanza.mef.service.OpzioneRichServiceUtil
 * @generated
 */
public abstract class OpzioneRichServiceBaseImpl extends BaseServiceImpl
	implements OpzioneRichService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.accenture.lavoro.agile.istanza.mef.service.OpzioneRichServiceUtil} to access the opzione rich remote service.
	 */

	/**
	 * Returns the email local service.
	 *
	 * @return the email local service
	 */
	public com.accenture.lavoro.agile.istanza.mef.service.EmailLocalService getEmailLocalService() {
		return emailLocalService;
	}

	/**
	 * Sets the email local service.
	 *
	 * @param emailLocalService the email local service
	 */
	public void setEmailLocalService(
		com.accenture.lavoro.agile.istanza.mef.service.EmailLocalService emailLocalService) {
		this.emailLocalService = emailLocalService;
	}

	/**
	 * Returns the email remote service.
	 *
	 * @return the email remote service
	 */
	public com.accenture.lavoro.agile.istanza.mef.service.EmailService getEmailService() {
		return emailService;
	}

	/**
	 * Sets the email remote service.
	 *
	 * @param emailService the email remote service
	 */
	public void setEmailService(
		com.accenture.lavoro.agile.istanza.mef.service.EmailService emailService) {
		this.emailService = emailService;
	}

	/**
	 * Returns the email persistence.
	 *
	 * @return the email persistence
	 */
	public EmailPersistence getEmailPersistence() {
		return emailPersistence;
	}

	/**
	 * Sets the email persistence.
	 *
	 * @param emailPersistence the email persistence
	 */
	public void setEmailPersistence(EmailPersistence emailPersistence) {
		this.emailPersistence = emailPersistence;
	}

	/**
	 * Returns the opzione rich local service.
	 *
	 * @return the opzione rich local service
	 */
	public com.accenture.lavoro.agile.istanza.mef.service.OpzioneRichLocalService getOpzioneRichLocalService() {
		return opzioneRichLocalService;
	}

	/**
	 * Sets the opzione rich local service.
	 *
	 * @param opzioneRichLocalService the opzione rich local service
	 */
	public void setOpzioneRichLocalService(
		com.accenture.lavoro.agile.istanza.mef.service.OpzioneRichLocalService opzioneRichLocalService) {
		this.opzioneRichLocalService = opzioneRichLocalService;
	}

	/**
	 * Returns the opzione rich remote service.
	 *
	 * @return the opzione rich remote service
	 */
	public OpzioneRichService getOpzioneRichService() {
		return opzioneRichService;
	}

	/**
	 * Sets the opzione rich remote service.
	 *
	 * @param opzioneRichService the opzione rich remote service
	 */
	public void setOpzioneRichService(OpzioneRichService opzioneRichService) {
		this.opzioneRichService = opzioneRichService;
	}

	/**
	 * Returns the opzione rich persistence.
	 *
	 * @return the opzione rich persistence
	 */
	public OpzioneRichPersistence getOpzioneRichPersistence() {
		return opzioneRichPersistence;
	}

	/**
	 * Sets the opzione rich persistence.
	 *
	 * @param opzioneRichPersistence the opzione rich persistence
	 */
	public void setOpzioneRichPersistence(
		OpzioneRichPersistence opzioneRichPersistence) {
		this.opzioneRichPersistence = opzioneRichPersistence;
	}

	/**
	 * Returns the rich lav agile local service.
	 *
	 * @return the rich lav agile local service
	 */
	public com.accenture.lavoro.agile.istanza.mef.service.RichLavAgileLocalService getRichLavAgileLocalService() {
		return richLavAgileLocalService;
	}

	/**
	 * Sets the rich lav agile local service.
	 *
	 * @param richLavAgileLocalService the rich lav agile local service
	 */
	public void setRichLavAgileLocalService(
		com.accenture.lavoro.agile.istanza.mef.service.RichLavAgileLocalService richLavAgileLocalService) {
		this.richLavAgileLocalService = richLavAgileLocalService;
	}

	/**
	 * Returns the rich lav agile remote service.
	 *
	 * @return the rich lav agile remote service
	 */
	public com.accenture.lavoro.agile.istanza.mef.service.RichLavAgileService getRichLavAgileService() {
		return richLavAgileService;
	}

	/**
	 * Sets the rich lav agile remote service.
	 *
	 * @param richLavAgileService the rich lav agile remote service
	 */
	public void setRichLavAgileService(
		com.accenture.lavoro.agile.istanza.mef.service.RichLavAgileService richLavAgileService) {
		this.richLavAgileService = richLavAgileService;
	}

	/**
	 * Returns the rich lav agile persistence.
	 *
	 * @return the rich lav agile persistence
	 */
	public RichLavAgilePersistence getRichLavAgilePersistence() {
		return richLavAgilePersistence;
	}

	/**
	 * Sets the rich lav agile persistence.
	 *
	 * @param richLavAgilePersistence the rich lav agile persistence
	 */
	public void setRichLavAgilePersistence(
		RichLavAgilePersistence richLavAgilePersistence) {
		this.richLavAgilePersistence = richLavAgilePersistence;
	}

	/**
	 * Returns the rich lav agile finder.
	 *
	 * @return the rich lav agile finder
	 */
	public RichLavAgileFinder getRichLavAgileFinder() {
		return richLavAgileFinder;
	}

	/**
	 * Sets the rich lav agile finder.
	 *
	 * @param richLavAgileFinder the rich lav agile finder
	 */
	public void setRichLavAgileFinder(RichLavAgileFinder richLavAgileFinder) {
		this.richLavAgileFinder = richLavAgileFinder;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return OpzioneRichService.class.getName();
	}

	protected Class<?> getModelClass() {
		return OpzioneRich.class;
	}

	protected String getModelClassName() {
		return OpzioneRich.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = opzioneRichPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.accenture.lavoro.agile.istanza.mef.service.EmailLocalService.class)
	protected com.accenture.lavoro.agile.istanza.mef.service.EmailLocalService emailLocalService;
	@BeanReference(type = com.accenture.lavoro.agile.istanza.mef.service.EmailService.class)
	protected com.accenture.lavoro.agile.istanza.mef.service.EmailService emailService;
	@BeanReference(type = EmailPersistence.class)
	protected EmailPersistence emailPersistence;
	@BeanReference(type = com.accenture.lavoro.agile.istanza.mef.service.OpzioneRichLocalService.class)
	protected com.accenture.lavoro.agile.istanza.mef.service.OpzioneRichLocalService opzioneRichLocalService;
	@BeanReference(type = OpzioneRichService.class)
	protected OpzioneRichService opzioneRichService;
	@BeanReference(type = OpzioneRichPersistence.class)
	protected OpzioneRichPersistence opzioneRichPersistence;
	@BeanReference(type = com.accenture.lavoro.agile.istanza.mef.service.RichLavAgileLocalService.class)
	protected com.accenture.lavoro.agile.istanza.mef.service.RichLavAgileLocalService richLavAgileLocalService;
	@BeanReference(type = com.accenture.lavoro.agile.istanza.mef.service.RichLavAgileService.class)
	protected com.accenture.lavoro.agile.istanza.mef.service.RichLavAgileService richLavAgileService;
	@BeanReference(type = RichLavAgilePersistence.class)
	protected RichLavAgilePersistence richLavAgilePersistence;
	@BeanReference(type = RichLavAgileFinder.class)
	protected RichLavAgileFinder richLavAgileFinder;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}