/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.logicaldel.gestione.riunioni.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the CancelAmmConv service. Represents a row in the &quot;LOGICALGR_CancelAmmConv&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.logicaldel.gestione.riunioni.model.impl.CancelAmmConvModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.logicaldel.gestione.riunioni.model.impl.CancelAmmConvImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CancelAmmConv
 * @see com.intranet.mef.logicaldel.gestione.riunioni.model.impl.CancelAmmConvImpl
 * @see com.intranet.mef.logicaldel.gestione.riunioni.model.impl.CancelAmmConvModelImpl
 * @generated
 */
@ProviderType
public interface CancelAmmConvModel extends BaseModel<CancelAmmConv> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a cancel amm conv model instance should use the {@link CancelAmmConv} interface instead.
	 */

	/**
	 * Returns the primary key of this cancel amm conv.
	 *
	 * @return the primary key of this cancel amm conv
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this cancel amm conv.
	 *
	 * @param primaryKey the primary key of this cancel amm conv
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_amministrazione_convocante of this cancel amm conv.
	 *
	 * @return the id_amministrazione_convocante of this cancel amm conv
	 */
	public long getId_amministrazione_convocante();

	/**
	 * Sets the id_amministrazione_convocante of this cancel amm conv.
	 *
	 * @param id_amministrazione_convocante the id_amministrazione_convocante of this cancel amm conv
	 */
	public void setId_amministrazione_convocante(
		long id_amministrazione_convocante);

	/**
	 * Returns the cancellato of this cancel amm conv.
	 *
	 * @return the cancellato of this cancel amm conv
	 */
	public boolean getCancellato();

	/**
	 * Returns <code>true</code> if this cancel amm conv is cancellato.
	 *
	 * @return <code>true</code> if this cancel amm conv is cancellato; <code>false</code> otherwise
	 */
	public boolean isCancellato();

	/**
	 * Sets whether this cancel amm conv is cancellato.
	 *
	 * @param cancellato the cancellato of this cancel amm conv
	 */
	public void setCancellato(boolean cancellato);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CancelAmmConv cancelAmmConv);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CancelAmmConv> toCacheModel();

	@Override
	public CancelAmmConv toEscapedModel();

	@Override
	public CancelAmmConv toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}