/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import service.intranet.mef.model.LogisticaServizio;
import service.intranet.mef.service.LogisticaServizioService;
import service.intranet.mef.service.persistence.AssetPersistence;
import service.intranet.mef.service.persistence.BadgeRichiestePersistence;
import service.intranet.mef.service.persistence.BeneInvPersistence;
import service.intranet.mef.service.persistence.BeneInvRichiestoPersistence;
import service.intranet.mef.service.persistence.HardwareTecniciPersistence;
import service.intranet.mef.service.persistence.LogisticaRichiestePersistence;
import service.intranet.mef.service.persistence.LogisticaServizioPersistence;
import service.intranet.mef.service.persistence.LogisticaStatoPersistence;
import service.intranet.mef.service.persistence.LogisticaValutazionePersistence;
import service.intranet.mef.service.persistence.ModuloTrasportiPersistence;
import service.intranet.mef.service.persistence.PeriodicitaRichPubblicPersistence;
import service.intranet.mef.service.persistence.RichiestaBeneInvFinder;
import service.intranet.mef.service.persistence.RichiestaBeneInvPersistence;
import service.intranet.mef.service.persistence.RichiestaInterventiPersistence;
import service.intranet.mef.service.persistence.RichiestaPubblicSitiPersistence;
import service.intranet.mef.service.persistence.RichiesteHWPersistence;
import service.intranet.mef.service.persistence.RichiesteUtenzaPersistence;
import service.intranet.mef.service.persistence.StatoRichBeneInvPersistence;
import service.intranet.mef.service.persistence.TipoBeneInvPersistence;
import service.intranet.mef.service.persistence.TipologiaComputerPersistence;
import service.intranet.mef.service.persistence.TipologiaDispositiviPersistence;
import service.intranet.mef.service.persistence.TipologiaRichPubblicPersistence;
import service.intranet.mef.service.persistence.TipologiaStampantiPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the logistica servizio remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link service.intranet.mef.service.impl.LogisticaServizioServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see service.intranet.mef.service.impl.LogisticaServizioServiceImpl
 * @see service.intranet.mef.service.LogisticaServizioServiceUtil
 * @generated
 */
public abstract class LogisticaServizioServiceBaseImpl extends BaseServiceImpl
	implements LogisticaServizioService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link service.intranet.mef.service.LogisticaServizioServiceUtil} to access the logistica servizio remote service.
	 */

	/**
	 * Returns the asset local service.
	 *
	 * @return the asset local service
	 */
	public service.intranet.mef.service.AssetLocalService getAssetLocalService() {
		return assetLocalService;
	}

	/**
	 * Sets the asset local service.
	 *
	 * @param assetLocalService the asset local service
	 */
	public void setAssetLocalService(
		service.intranet.mef.service.AssetLocalService assetLocalService) {
		this.assetLocalService = assetLocalService;
	}

	/**
	 * Returns the asset remote service.
	 *
	 * @return the asset remote service
	 */
	public service.intranet.mef.service.AssetService getAssetService() {
		return assetService;
	}

	/**
	 * Sets the asset remote service.
	 *
	 * @param assetService the asset remote service
	 */
	public void setAssetService(
		service.intranet.mef.service.AssetService assetService) {
		this.assetService = assetService;
	}

	/**
	 * Returns the asset persistence.
	 *
	 * @return the asset persistence
	 */
	public AssetPersistence getAssetPersistence() {
		return assetPersistence;
	}

	/**
	 * Sets the asset persistence.
	 *
	 * @param assetPersistence the asset persistence
	 */
	public void setAssetPersistence(AssetPersistence assetPersistence) {
		this.assetPersistence = assetPersistence;
	}

	/**
	 * Returns the badge richieste local service.
	 *
	 * @return the badge richieste local service
	 */
	public service.intranet.mef.service.BadgeRichiesteLocalService getBadgeRichiesteLocalService() {
		return badgeRichiesteLocalService;
	}

	/**
	 * Sets the badge richieste local service.
	 *
	 * @param badgeRichiesteLocalService the badge richieste local service
	 */
	public void setBadgeRichiesteLocalService(
		service.intranet.mef.service.BadgeRichiesteLocalService badgeRichiesteLocalService) {
		this.badgeRichiesteLocalService = badgeRichiesteLocalService;
	}

	/**
	 * Returns the badge richieste remote service.
	 *
	 * @return the badge richieste remote service
	 */
	public service.intranet.mef.service.BadgeRichiesteService getBadgeRichiesteService() {
		return badgeRichiesteService;
	}

	/**
	 * Sets the badge richieste remote service.
	 *
	 * @param badgeRichiesteService the badge richieste remote service
	 */
	public void setBadgeRichiesteService(
		service.intranet.mef.service.BadgeRichiesteService badgeRichiesteService) {
		this.badgeRichiesteService = badgeRichiesteService;
	}

	/**
	 * Returns the badge richieste persistence.
	 *
	 * @return the badge richieste persistence
	 */
	public BadgeRichiestePersistence getBadgeRichiestePersistence() {
		return badgeRichiestePersistence;
	}

	/**
	 * Sets the badge richieste persistence.
	 *
	 * @param badgeRichiestePersistence the badge richieste persistence
	 */
	public void setBadgeRichiestePersistence(
		BadgeRichiestePersistence badgeRichiestePersistence) {
		this.badgeRichiestePersistence = badgeRichiestePersistence;
	}

	/**
	 * Returns the bene inv local service.
	 *
	 * @return the bene inv local service
	 */
	public service.intranet.mef.service.BeneInvLocalService getBeneInvLocalService() {
		return beneInvLocalService;
	}

	/**
	 * Sets the bene inv local service.
	 *
	 * @param beneInvLocalService the bene inv local service
	 */
	public void setBeneInvLocalService(
		service.intranet.mef.service.BeneInvLocalService beneInvLocalService) {
		this.beneInvLocalService = beneInvLocalService;
	}

	/**
	 * Returns the bene inv remote service.
	 *
	 * @return the bene inv remote service
	 */
	public service.intranet.mef.service.BeneInvService getBeneInvService() {
		return beneInvService;
	}

	/**
	 * Sets the bene inv remote service.
	 *
	 * @param beneInvService the bene inv remote service
	 */
	public void setBeneInvService(
		service.intranet.mef.service.BeneInvService beneInvService) {
		this.beneInvService = beneInvService;
	}

	/**
	 * Returns the bene inv persistence.
	 *
	 * @return the bene inv persistence
	 */
	public BeneInvPersistence getBeneInvPersistence() {
		return beneInvPersistence;
	}

	/**
	 * Sets the bene inv persistence.
	 *
	 * @param beneInvPersistence the bene inv persistence
	 */
	public void setBeneInvPersistence(BeneInvPersistence beneInvPersistence) {
		this.beneInvPersistence = beneInvPersistence;
	}

	/**
	 * Returns the bene inv richiesto local service.
	 *
	 * @return the bene inv richiesto local service
	 */
	public service.intranet.mef.service.BeneInvRichiestoLocalService getBeneInvRichiestoLocalService() {
		return beneInvRichiestoLocalService;
	}

	/**
	 * Sets the bene inv richiesto local service.
	 *
	 * @param beneInvRichiestoLocalService the bene inv richiesto local service
	 */
	public void setBeneInvRichiestoLocalService(
		service.intranet.mef.service.BeneInvRichiestoLocalService beneInvRichiestoLocalService) {
		this.beneInvRichiestoLocalService = beneInvRichiestoLocalService;
	}

	/**
	 * Returns the bene inv richiesto remote service.
	 *
	 * @return the bene inv richiesto remote service
	 */
	public service.intranet.mef.service.BeneInvRichiestoService getBeneInvRichiestoService() {
		return beneInvRichiestoService;
	}

	/**
	 * Sets the bene inv richiesto remote service.
	 *
	 * @param beneInvRichiestoService the bene inv richiesto remote service
	 */
	public void setBeneInvRichiestoService(
		service.intranet.mef.service.BeneInvRichiestoService beneInvRichiestoService) {
		this.beneInvRichiestoService = beneInvRichiestoService;
	}

	/**
	 * Returns the bene inv richiesto persistence.
	 *
	 * @return the bene inv richiesto persistence
	 */
	public BeneInvRichiestoPersistence getBeneInvRichiestoPersistence() {
		return beneInvRichiestoPersistence;
	}

	/**
	 * Sets the bene inv richiesto persistence.
	 *
	 * @param beneInvRichiestoPersistence the bene inv richiesto persistence
	 */
	public void setBeneInvRichiestoPersistence(
		BeneInvRichiestoPersistence beneInvRichiestoPersistence) {
		this.beneInvRichiestoPersistence = beneInvRichiestoPersistence;
	}

	/**
	 * Returns the hardware tecnici local service.
	 *
	 * @return the hardware tecnici local service
	 */
	public service.intranet.mef.service.HardwareTecniciLocalService getHardwareTecniciLocalService() {
		return hardwareTecniciLocalService;
	}

	/**
	 * Sets the hardware tecnici local service.
	 *
	 * @param hardwareTecniciLocalService the hardware tecnici local service
	 */
	public void setHardwareTecniciLocalService(
		service.intranet.mef.service.HardwareTecniciLocalService hardwareTecniciLocalService) {
		this.hardwareTecniciLocalService = hardwareTecniciLocalService;
	}

	/**
	 * Returns the hardware tecnici remote service.
	 *
	 * @return the hardware tecnici remote service
	 */
	public service.intranet.mef.service.HardwareTecniciService getHardwareTecniciService() {
		return hardwareTecniciService;
	}

	/**
	 * Sets the hardware tecnici remote service.
	 *
	 * @param hardwareTecniciService the hardware tecnici remote service
	 */
	public void setHardwareTecniciService(
		service.intranet.mef.service.HardwareTecniciService hardwareTecniciService) {
		this.hardwareTecniciService = hardwareTecniciService;
	}

	/**
	 * Returns the hardware tecnici persistence.
	 *
	 * @return the hardware tecnici persistence
	 */
	public HardwareTecniciPersistence getHardwareTecniciPersistence() {
		return hardwareTecniciPersistence;
	}

	/**
	 * Sets the hardware tecnici persistence.
	 *
	 * @param hardwareTecniciPersistence the hardware tecnici persistence
	 */
	public void setHardwareTecniciPersistence(
		HardwareTecniciPersistence hardwareTecniciPersistence) {
		this.hardwareTecniciPersistence = hardwareTecniciPersistence;
	}

	/**
	 * Returns the logistica richieste local service.
	 *
	 * @return the logistica richieste local service
	 */
	public service.intranet.mef.service.LogisticaRichiesteLocalService getLogisticaRichiesteLocalService() {
		return logisticaRichiesteLocalService;
	}

	/**
	 * Sets the logistica richieste local service.
	 *
	 * @param logisticaRichiesteLocalService the logistica richieste local service
	 */
	public void setLogisticaRichiesteLocalService(
		service.intranet.mef.service.LogisticaRichiesteLocalService logisticaRichiesteLocalService) {
		this.logisticaRichiesteLocalService = logisticaRichiesteLocalService;
	}

	/**
	 * Returns the logistica richieste remote service.
	 *
	 * @return the logistica richieste remote service
	 */
	public service.intranet.mef.service.LogisticaRichiesteService getLogisticaRichiesteService() {
		return logisticaRichiesteService;
	}

	/**
	 * Sets the logistica richieste remote service.
	 *
	 * @param logisticaRichiesteService the logistica richieste remote service
	 */
	public void setLogisticaRichiesteService(
		service.intranet.mef.service.LogisticaRichiesteService logisticaRichiesteService) {
		this.logisticaRichiesteService = logisticaRichiesteService;
	}

	/**
	 * Returns the logistica richieste persistence.
	 *
	 * @return the logistica richieste persistence
	 */
	public LogisticaRichiestePersistence getLogisticaRichiestePersistence() {
		return logisticaRichiestePersistence;
	}

	/**
	 * Sets the logistica richieste persistence.
	 *
	 * @param logisticaRichiestePersistence the logistica richieste persistence
	 */
	public void setLogisticaRichiestePersistence(
		LogisticaRichiestePersistence logisticaRichiestePersistence) {
		this.logisticaRichiestePersistence = logisticaRichiestePersistence;
	}

	/**
	 * Returns the logistica servizio local service.
	 *
	 * @return the logistica servizio local service
	 */
	public service.intranet.mef.service.LogisticaServizioLocalService getLogisticaServizioLocalService() {
		return logisticaServizioLocalService;
	}

	/**
	 * Sets the logistica servizio local service.
	 *
	 * @param logisticaServizioLocalService the logistica servizio local service
	 */
	public void setLogisticaServizioLocalService(
		service.intranet.mef.service.LogisticaServizioLocalService logisticaServizioLocalService) {
		this.logisticaServizioLocalService = logisticaServizioLocalService;
	}

	/**
	 * Returns the logistica servizio remote service.
	 *
	 * @return the logistica servizio remote service
	 */
	public LogisticaServizioService getLogisticaServizioService() {
		return logisticaServizioService;
	}

	/**
	 * Sets the logistica servizio remote service.
	 *
	 * @param logisticaServizioService the logistica servizio remote service
	 */
	public void setLogisticaServizioService(
		LogisticaServizioService logisticaServizioService) {
		this.logisticaServizioService = logisticaServizioService;
	}

	/**
	 * Returns the logistica servizio persistence.
	 *
	 * @return the logistica servizio persistence
	 */
	public LogisticaServizioPersistence getLogisticaServizioPersistence() {
		return logisticaServizioPersistence;
	}

	/**
	 * Sets the logistica servizio persistence.
	 *
	 * @param logisticaServizioPersistence the logistica servizio persistence
	 */
	public void setLogisticaServizioPersistence(
		LogisticaServizioPersistence logisticaServizioPersistence) {
		this.logisticaServizioPersistence = logisticaServizioPersistence;
	}

	/**
	 * Returns the logistica stato local service.
	 *
	 * @return the logistica stato local service
	 */
	public service.intranet.mef.service.LogisticaStatoLocalService getLogisticaStatoLocalService() {
		return logisticaStatoLocalService;
	}

	/**
	 * Sets the logistica stato local service.
	 *
	 * @param logisticaStatoLocalService the logistica stato local service
	 */
	public void setLogisticaStatoLocalService(
		service.intranet.mef.service.LogisticaStatoLocalService logisticaStatoLocalService) {
		this.logisticaStatoLocalService = logisticaStatoLocalService;
	}

	/**
	 * Returns the logistica stato remote service.
	 *
	 * @return the logistica stato remote service
	 */
	public service.intranet.mef.service.LogisticaStatoService getLogisticaStatoService() {
		return logisticaStatoService;
	}

	/**
	 * Sets the logistica stato remote service.
	 *
	 * @param logisticaStatoService the logistica stato remote service
	 */
	public void setLogisticaStatoService(
		service.intranet.mef.service.LogisticaStatoService logisticaStatoService) {
		this.logisticaStatoService = logisticaStatoService;
	}

	/**
	 * Returns the logistica stato persistence.
	 *
	 * @return the logistica stato persistence
	 */
	public LogisticaStatoPersistence getLogisticaStatoPersistence() {
		return logisticaStatoPersistence;
	}

	/**
	 * Sets the logistica stato persistence.
	 *
	 * @param logisticaStatoPersistence the logistica stato persistence
	 */
	public void setLogisticaStatoPersistence(
		LogisticaStatoPersistence logisticaStatoPersistence) {
		this.logisticaStatoPersistence = logisticaStatoPersistence;
	}

	/**
	 * Returns the logistica valutazione local service.
	 *
	 * @return the logistica valutazione local service
	 */
	public service.intranet.mef.service.LogisticaValutazioneLocalService getLogisticaValutazioneLocalService() {
		return logisticaValutazioneLocalService;
	}

	/**
	 * Sets the logistica valutazione local service.
	 *
	 * @param logisticaValutazioneLocalService the logistica valutazione local service
	 */
	public void setLogisticaValutazioneLocalService(
		service.intranet.mef.service.LogisticaValutazioneLocalService logisticaValutazioneLocalService) {
		this.logisticaValutazioneLocalService = logisticaValutazioneLocalService;
	}

	/**
	 * Returns the logistica valutazione remote service.
	 *
	 * @return the logistica valutazione remote service
	 */
	public service.intranet.mef.service.LogisticaValutazioneService getLogisticaValutazioneService() {
		return logisticaValutazioneService;
	}

	/**
	 * Sets the logistica valutazione remote service.
	 *
	 * @param logisticaValutazioneService the logistica valutazione remote service
	 */
	public void setLogisticaValutazioneService(
		service.intranet.mef.service.LogisticaValutazioneService logisticaValutazioneService) {
		this.logisticaValutazioneService = logisticaValutazioneService;
	}

	/**
	 * Returns the logistica valutazione persistence.
	 *
	 * @return the logistica valutazione persistence
	 */
	public LogisticaValutazionePersistence getLogisticaValutazionePersistence() {
		return logisticaValutazionePersistence;
	}

	/**
	 * Sets the logistica valutazione persistence.
	 *
	 * @param logisticaValutazionePersistence the logistica valutazione persistence
	 */
	public void setLogisticaValutazionePersistence(
		LogisticaValutazionePersistence logisticaValutazionePersistence) {
		this.logisticaValutazionePersistence = logisticaValutazionePersistence;
	}

	/**
	 * Returns the modulo trasporti local service.
	 *
	 * @return the modulo trasporti local service
	 */
	public service.intranet.mef.service.ModuloTrasportiLocalService getModuloTrasportiLocalService() {
		return moduloTrasportiLocalService;
	}

	/**
	 * Sets the modulo trasporti local service.
	 *
	 * @param moduloTrasportiLocalService the modulo trasporti local service
	 */
	public void setModuloTrasportiLocalService(
		service.intranet.mef.service.ModuloTrasportiLocalService moduloTrasportiLocalService) {
		this.moduloTrasportiLocalService = moduloTrasportiLocalService;
	}

	/**
	 * Returns the modulo trasporti remote service.
	 *
	 * @return the modulo trasporti remote service
	 */
	public service.intranet.mef.service.ModuloTrasportiService getModuloTrasportiService() {
		return moduloTrasportiService;
	}

	/**
	 * Sets the modulo trasporti remote service.
	 *
	 * @param moduloTrasportiService the modulo trasporti remote service
	 */
	public void setModuloTrasportiService(
		service.intranet.mef.service.ModuloTrasportiService moduloTrasportiService) {
		this.moduloTrasportiService = moduloTrasportiService;
	}

	/**
	 * Returns the modulo trasporti persistence.
	 *
	 * @return the modulo trasporti persistence
	 */
	public ModuloTrasportiPersistence getModuloTrasportiPersistence() {
		return moduloTrasportiPersistence;
	}

	/**
	 * Sets the modulo trasporti persistence.
	 *
	 * @param moduloTrasportiPersistence the modulo trasporti persistence
	 */
	public void setModuloTrasportiPersistence(
		ModuloTrasportiPersistence moduloTrasportiPersistence) {
		this.moduloTrasportiPersistence = moduloTrasportiPersistence;
	}

	/**
	 * Returns the periodicita rich pubblic local service.
	 *
	 * @return the periodicita rich pubblic local service
	 */
	public service.intranet.mef.service.PeriodicitaRichPubblicLocalService getPeriodicitaRichPubblicLocalService() {
		return periodicitaRichPubblicLocalService;
	}

	/**
	 * Sets the periodicita rich pubblic local service.
	 *
	 * @param periodicitaRichPubblicLocalService the periodicita rich pubblic local service
	 */
	public void setPeriodicitaRichPubblicLocalService(
		service.intranet.mef.service.PeriodicitaRichPubblicLocalService periodicitaRichPubblicLocalService) {
		this.periodicitaRichPubblicLocalService = periodicitaRichPubblicLocalService;
	}

	/**
	 * Returns the periodicita rich pubblic remote service.
	 *
	 * @return the periodicita rich pubblic remote service
	 */
	public service.intranet.mef.service.PeriodicitaRichPubblicService getPeriodicitaRichPubblicService() {
		return periodicitaRichPubblicService;
	}

	/**
	 * Sets the periodicita rich pubblic remote service.
	 *
	 * @param periodicitaRichPubblicService the periodicita rich pubblic remote service
	 */
	public void setPeriodicitaRichPubblicService(
		service.intranet.mef.service.PeriodicitaRichPubblicService periodicitaRichPubblicService) {
		this.periodicitaRichPubblicService = periodicitaRichPubblicService;
	}

	/**
	 * Returns the periodicita rich pubblic persistence.
	 *
	 * @return the periodicita rich pubblic persistence
	 */
	public PeriodicitaRichPubblicPersistence getPeriodicitaRichPubblicPersistence() {
		return periodicitaRichPubblicPersistence;
	}

	/**
	 * Sets the periodicita rich pubblic persistence.
	 *
	 * @param periodicitaRichPubblicPersistence the periodicita rich pubblic persistence
	 */
	public void setPeriodicitaRichPubblicPersistence(
		PeriodicitaRichPubblicPersistence periodicitaRichPubblicPersistence) {
		this.periodicitaRichPubblicPersistence = periodicitaRichPubblicPersistence;
	}

	/**
	 * Returns the richiesta bene inv local service.
	 *
	 * @return the richiesta bene inv local service
	 */
	public service.intranet.mef.service.RichiestaBeneInvLocalService getRichiestaBeneInvLocalService() {
		return richiestaBeneInvLocalService;
	}

	/**
	 * Sets the richiesta bene inv local service.
	 *
	 * @param richiestaBeneInvLocalService the richiesta bene inv local service
	 */
	public void setRichiestaBeneInvLocalService(
		service.intranet.mef.service.RichiestaBeneInvLocalService richiestaBeneInvLocalService) {
		this.richiestaBeneInvLocalService = richiestaBeneInvLocalService;
	}

	/**
	 * Returns the richiesta bene inv remote service.
	 *
	 * @return the richiesta bene inv remote service
	 */
	public service.intranet.mef.service.RichiestaBeneInvService getRichiestaBeneInvService() {
		return richiestaBeneInvService;
	}

	/**
	 * Sets the richiesta bene inv remote service.
	 *
	 * @param richiestaBeneInvService the richiesta bene inv remote service
	 */
	public void setRichiestaBeneInvService(
		service.intranet.mef.service.RichiestaBeneInvService richiestaBeneInvService) {
		this.richiestaBeneInvService = richiestaBeneInvService;
	}

	/**
	 * Returns the richiesta bene inv persistence.
	 *
	 * @return the richiesta bene inv persistence
	 */
	public RichiestaBeneInvPersistence getRichiestaBeneInvPersistence() {
		return richiestaBeneInvPersistence;
	}

	/**
	 * Sets the richiesta bene inv persistence.
	 *
	 * @param richiestaBeneInvPersistence the richiesta bene inv persistence
	 */
	public void setRichiestaBeneInvPersistence(
		RichiestaBeneInvPersistence richiestaBeneInvPersistence) {
		this.richiestaBeneInvPersistence = richiestaBeneInvPersistence;
	}

	/**
	 * Returns the richiesta bene inv finder.
	 *
	 * @return the richiesta bene inv finder
	 */
	public RichiestaBeneInvFinder getRichiestaBeneInvFinder() {
		return richiestaBeneInvFinder;
	}

	/**
	 * Sets the richiesta bene inv finder.
	 *
	 * @param richiestaBeneInvFinder the richiesta bene inv finder
	 */
	public void setRichiestaBeneInvFinder(
		RichiestaBeneInvFinder richiestaBeneInvFinder) {
		this.richiestaBeneInvFinder = richiestaBeneInvFinder;
	}

	/**
	 * Returns the richiesta interventi local service.
	 *
	 * @return the richiesta interventi local service
	 */
	public service.intranet.mef.service.RichiestaInterventiLocalService getRichiestaInterventiLocalService() {
		return richiestaInterventiLocalService;
	}

	/**
	 * Sets the richiesta interventi local service.
	 *
	 * @param richiestaInterventiLocalService the richiesta interventi local service
	 */
	public void setRichiestaInterventiLocalService(
		service.intranet.mef.service.RichiestaInterventiLocalService richiestaInterventiLocalService) {
		this.richiestaInterventiLocalService = richiestaInterventiLocalService;
	}

	/**
	 * Returns the richiesta interventi remote service.
	 *
	 * @return the richiesta interventi remote service
	 */
	public service.intranet.mef.service.RichiestaInterventiService getRichiestaInterventiService() {
		return richiestaInterventiService;
	}

	/**
	 * Sets the richiesta interventi remote service.
	 *
	 * @param richiestaInterventiService the richiesta interventi remote service
	 */
	public void setRichiestaInterventiService(
		service.intranet.mef.service.RichiestaInterventiService richiestaInterventiService) {
		this.richiestaInterventiService = richiestaInterventiService;
	}

	/**
	 * Returns the richiesta interventi persistence.
	 *
	 * @return the richiesta interventi persistence
	 */
	public RichiestaInterventiPersistence getRichiestaInterventiPersistence() {
		return richiestaInterventiPersistence;
	}

	/**
	 * Sets the richiesta interventi persistence.
	 *
	 * @param richiestaInterventiPersistence the richiesta interventi persistence
	 */
	public void setRichiestaInterventiPersistence(
		RichiestaInterventiPersistence richiestaInterventiPersistence) {
		this.richiestaInterventiPersistence = richiestaInterventiPersistence;
	}

	/**
	 * Returns the richiesta pubblic siti local service.
	 *
	 * @return the richiesta pubblic siti local service
	 */
	public service.intranet.mef.service.RichiestaPubblicSitiLocalService getRichiestaPubblicSitiLocalService() {
		return richiestaPubblicSitiLocalService;
	}

	/**
	 * Sets the richiesta pubblic siti local service.
	 *
	 * @param richiestaPubblicSitiLocalService the richiesta pubblic siti local service
	 */
	public void setRichiestaPubblicSitiLocalService(
		service.intranet.mef.service.RichiestaPubblicSitiLocalService richiestaPubblicSitiLocalService) {
		this.richiestaPubblicSitiLocalService = richiestaPubblicSitiLocalService;
	}

	/**
	 * Returns the richiesta pubblic siti remote service.
	 *
	 * @return the richiesta pubblic siti remote service
	 */
	public service.intranet.mef.service.RichiestaPubblicSitiService getRichiestaPubblicSitiService() {
		return richiestaPubblicSitiService;
	}

	/**
	 * Sets the richiesta pubblic siti remote service.
	 *
	 * @param richiestaPubblicSitiService the richiesta pubblic siti remote service
	 */
	public void setRichiestaPubblicSitiService(
		service.intranet.mef.service.RichiestaPubblicSitiService richiestaPubblicSitiService) {
		this.richiestaPubblicSitiService = richiestaPubblicSitiService;
	}

	/**
	 * Returns the richiesta pubblic siti persistence.
	 *
	 * @return the richiesta pubblic siti persistence
	 */
	public RichiestaPubblicSitiPersistence getRichiestaPubblicSitiPersistence() {
		return richiestaPubblicSitiPersistence;
	}

	/**
	 * Sets the richiesta pubblic siti persistence.
	 *
	 * @param richiestaPubblicSitiPersistence the richiesta pubblic siti persistence
	 */
	public void setRichiestaPubblicSitiPersistence(
		RichiestaPubblicSitiPersistence richiestaPubblicSitiPersistence) {
		this.richiestaPubblicSitiPersistence = richiestaPubblicSitiPersistence;
	}

	/**
	 * Returns the richieste h w local service.
	 *
	 * @return the richieste h w local service
	 */
	public service.intranet.mef.service.RichiesteHWLocalService getRichiesteHWLocalService() {
		return richiesteHWLocalService;
	}

	/**
	 * Sets the richieste h w local service.
	 *
	 * @param richiesteHWLocalService the richieste h w local service
	 */
	public void setRichiesteHWLocalService(
		service.intranet.mef.service.RichiesteHWLocalService richiesteHWLocalService) {
		this.richiesteHWLocalService = richiesteHWLocalService;
	}

	/**
	 * Returns the richieste h w remote service.
	 *
	 * @return the richieste h w remote service
	 */
	public service.intranet.mef.service.RichiesteHWService getRichiesteHWService() {
		return richiesteHWService;
	}

	/**
	 * Sets the richieste h w remote service.
	 *
	 * @param richiesteHWService the richieste h w remote service
	 */
	public void setRichiesteHWService(
		service.intranet.mef.service.RichiesteHWService richiesteHWService) {
		this.richiesteHWService = richiesteHWService;
	}

	/**
	 * Returns the richieste h w persistence.
	 *
	 * @return the richieste h w persistence
	 */
	public RichiesteHWPersistence getRichiesteHWPersistence() {
		return richiesteHWPersistence;
	}

	/**
	 * Sets the richieste h w persistence.
	 *
	 * @param richiesteHWPersistence the richieste h w persistence
	 */
	public void setRichiesteHWPersistence(
		RichiesteHWPersistence richiesteHWPersistence) {
		this.richiesteHWPersistence = richiesteHWPersistence;
	}

	/**
	 * Returns the richieste utenza local service.
	 *
	 * @return the richieste utenza local service
	 */
	public service.intranet.mef.service.RichiesteUtenzaLocalService getRichiesteUtenzaLocalService() {
		return richiesteUtenzaLocalService;
	}

	/**
	 * Sets the richieste utenza local service.
	 *
	 * @param richiesteUtenzaLocalService the richieste utenza local service
	 */
	public void setRichiesteUtenzaLocalService(
		service.intranet.mef.service.RichiesteUtenzaLocalService richiesteUtenzaLocalService) {
		this.richiesteUtenzaLocalService = richiesteUtenzaLocalService;
	}

	/**
	 * Returns the richieste utenza remote service.
	 *
	 * @return the richieste utenza remote service
	 */
	public service.intranet.mef.service.RichiesteUtenzaService getRichiesteUtenzaService() {
		return richiesteUtenzaService;
	}

	/**
	 * Sets the richieste utenza remote service.
	 *
	 * @param richiesteUtenzaService the richieste utenza remote service
	 */
	public void setRichiesteUtenzaService(
		service.intranet.mef.service.RichiesteUtenzaService richiesteUtenzaService) {
		this.richiesteUtenzaService = richiesteUtenzaService;
	}

	/**
	 * Returns the richieste utenza persistence.
	 *
	 * @return the richieste utenza persistence
	 */
	public RichiesteUtenzaPersistence getRichiesteUtenzaPersistence() {
		return richiesteUtenzaPersistence;
	}

	/**
	 * Sets the richieste utenza persistence.
	 *
	 * @param richiesteUtenzaPersistence the richieste utenza persistence
	 */
	public void setRichiesteUtenzaPersistence(
		RichiesteUtenzaPersistence richiesteUtenzaPersistence) {
		this.richiesteUtenzaPersistence = richiesteUtenzaPersistence;
	}

	/**
	 * Returns the stato rich bene inv local service.
	 *
	 * @return the stato rich bene inv local service
	 */
	public service.intranet.mef.service.StatoRichBeneInvLocalService getStatoRichBeneInvLocalService() {
		return statoRichBeneInvLocalService;
	}

	/**
	 * Sets the stato rich bene inv local service.
	 *
	 * @param statoRichBeneInvLocalService the stato rich bene inv local service
	 */
	public void setStatoRichBeneInvLocalService(
		service.intranet.mef.service.StatoRichBeneInvLocalService statoRichBeneInvLocalService) {
		this.statoRichBeneInvLocalService = statoRichBeneInvLocalService;
	}

	/**
	 * Returns the stato rich bene inv remote service.
	 *
	 * @return the stato rich bene inv remote service
	 */
	public service.intranet.mef.service.StatoRichBeneInvService getStatoRichBeneInvService() {
		return statoRichBeneInvService;
	}

	/**
	 * Sets the stato rich bene inv remote service.
	 *
	 * @param statoRichBeneInvService the stato rich bene inv remote service
	 */
	public void setStatoRichBeneInvService(
		service.intranet.mef.service.StatoRichBeneInvService statoRichBeneInvService) {
		this.statoRichBeneInvService = statoRichBeneInvService;
	}

	/**
	 * Returns the stato rich bene inv persistence.
	 *
	 * @return the stato rich bene inv persistence
	 */
	public StatoRichBeneInvPersistence getStatoRichBeneInvPersistence() {
		return statoRichBeneInvPersistence;
	}

	/**
	 * Sets the stato rich bene inv persistence.
	 *
	 * @param statoRichBeneInvPersistence the stato rich bene inv persistence
	 */
	public void setStatoRichBeneInvPersistence(
		StatoRichBeneInvPersistence statoRichBeneInvPersistence) {
		this.statoRichBeneInvPersistence = statoRichBeneInvPersistence;
	}

	/**
	 * Returns the tipo bene inv local service.
	 *
	 * @return the tipo bene inv local service
	 */
	public service.intranet.mef.service.TipoBeneInvLocalService getTipoBeneInvLocalService() {
		return tipoBeneInvLocalService;
	}

	/**
	 * Sets the tipo bene inv local service.
	 *
	 * @param tipoBeneInvLocalService the tipo bene inv local service
	 */
	public void setTipoBeneInvLocalService(
		service.intranet.mef.service.TipoBeneInvLocalService tipoBeneInvLocalService) {
		this.tipoBeneInvLocalService = tipoBeneInvLocalService;
	}

	/**
	 * Returns the tipo bene inv remote service.
	 *
	 * @return the tipo bene inv remote service
	 */
	public service.intranet.mef.service.TipoBeneInvService getTipoBeneInvService() {
		return tipoBeneInvService;
	}

	/**
	 * Sets the tipo bene inv remote service.
	 *
	 * @param tipoBeneInvService the tipo bene inv remote service
	 */
	public void setTipoBeneInvService(
		service.intranet.mef.service.TipoBeneInvService tipoBeneInvService) {
		this.tipoBeneInvService = tipoBeneInvService;
	}

	/**
	 * Returns the tipo bene inv persistence.
	 *
	 * @return the tipo bene inv persistence
	 */
	public TipoBeneInvPersistence getTipoBeneInvPersistence() {
		return tipoBeneInvPersistence;
	}

	/**
	 * Sets the tipo bene inv persistence.
	 *
	 * @param tipoBeneInvPersistence the tipo bene inv persistence
	 */
	public void setTipoBeneInvPersistence(
		TipoBeneInvPersistence tipoBeneInvPersistence) {
		this.tipoBeneInvPersistence = tipoBeneInvPersistence;
	}

	/**
	 * Returns the tipologia computer local service.
	 *
	 * @return the tipologia computer local service
	 */
	public service.intranet.mef.service.TipologiaComputerLocalService getTipologiaComputerLocalService() {
		return tipologiaComputerLocalService;
	}

	/**
	 * Sets the tipologia computer local service.
	 *
	 * @param tipologiaComputerLocalService the tipologia computer local service
	 */
	public void setTipologiaComputerLocalService(
		service.intranet.mef.service.TipologiaComputerLocalService tipologiaComputerLocalService) {
		this.tipologiaComputerLocalService = tipologiaComputerLocalService;
	}

	/**
	 * Returns the tipologia computer remote service.
	 *
	 * @return the tipologia computer remote service
	 */
	public service.intranet.mef.service.TipologiaComputerService getTipologiaComputerService() {
		return tipologiaComputerService;
	}

	/**
	 * Sets the tipologia computer remote service.
	 *
	 * @param tipologiaComputerService the tipologia computer remote service
	 */
	public void setTipologiaComputerService(
		service.intranet.mef.service.TipologiaComputerService tipologiaComputerService) {
		this.tipologiaComputerService = tipologiaComputerService;
	}

	/**
	 * Returns the tipologia computer persistence.
	 *
	 * @return the tipologia computer persistence
	 */
	public TipologiaComputerPersistence getTipologiaComputerPersistence() {
		return tipologiaComputerPersistence;
	}

	/**
	 * Sets the tipologia computer persistence.
	 *
	 * @param tipologiaComputerPersistence the tipologia computer persistence
	 */
	public void setTipologiaComputerPersistence(
		TipologiaComputerPersistence tipologiaComputerPersistence) {
		this.tipologiaComputerPersistence = tipologiaComputerPersistence;
	}

	/**
	 * Returns the tipologia dispositivi local service.
	 *
	 * @return the tipologia dispositivi local service
	 */
	public service.intranet.mef.service.TipologiaDispositiviLocalService getTipologiaDispositiviLocalService() {
		return tipologiaDispositiviLocalService;
	}

	/**
	 * Sets the tipologia dispositivi local service.
	 *
	 * @param tipologiaDispositiviLocalService the tipologia dispositivi local service
	 */
	public void setTipologiaDispositiviLocalService(
		service.intranet.mef.service.TipologiaDispositiviLocalService tipologiaDispositiviLocalService) {
		this.tipologiaDispositiviLocalService = tipologiaDispositiviLocalService;
	}

	/**
	 * Returns the tipologia dispositivi remote service.
	 *
	 * @return the tipologia dispositivi remote service
	 */
	public service.intranet.mef.service.TipologiaDispositiviService getTipologiaDispositiviService() {
		return tipologiaDispositiviService;
	}

	/**
	 * Sets the tipologia dispositivi remote service.
	 *
	 * @param tipologiaDispositiviService the tipologia dispositivi remote service
	 */
	public void setTipologiaDispositiviService(
		service.intranet.mef.service.TipologiaDispositiviService tipologiaDispositiviService) {
		this.tipologiaDispositiviService = tipologiaDispositiviService;
	}

	/**
	 * Returns the tipologia dispositivi persistence.
	 *
	 * @return the tipologia dispositivi persistence
	 */
	public TipologiaDispositiviPersistence getTipologiaDispositiviPersistence() {
		return tipologiaDispositiviPersistence;
	}

	/**
	 * Sets the tipologia dispositivi persistence.
	 *
	 * @param tipologiaDispositiviPersistence the tipologia dispositivi persistence
	 */
	public void setTipologiaDispositiviPersistence(
		TipologiaDispositiviPersistence tipologiaDispositiviPersistence) {
		this.tipologiaDispositiviPersistence = tipologiaDispositiviPersistence;
	}

	/**
	 * Returns the tipologia rich pubblic local service.
	 *
	 * @return the tipologia rich pubblic local service
	 */
	public service.intranet.mef.service.TipologiaRichPubblicLocalService getTipologiaRichPubblicLocalService() {
		return tipologiaRichPubblicLocalService;
	}

	/**
	 * Sets the tipologia rich pubblic local service.
	 *
	 * @param tipologiaRichPubblicLocalService the tipologia rich pubblic local service
	 */
	public void setTipologiaRichPubblicLocalService(
		service.intranet.mef.service.TipologiaRichPubblicLocalService tipologiaRichPubblicLocalService) {
		this.tipologiaRichPubblicLocalService = tipologiaRichPubblicLocalService;
	}

	/**
	 * Returns the tipologia rich pubblic remote service.
	 *
	 * @return the tipologia rich pubblic remote service
	 */
	public service.intranet.mef.service.TipologiaRichPubblicService getTipologiaRichPubblicService() {
		return tipologiaRichPubblicService;
	}

	/**
	 * Sets the tipologia rich pubblic remote service.
	 *
	 * @param tipologiaRichPubblicService the tipologia rich pubblic remote service
	 */
	public void setTipologiaRichPubblicService(
		service.intranet.mef.service.TipologiaRichPubblicService tipologiaRichPubblicService) {
		this.tipologiaRichPubblicService = tipologiaRichPubblicService;
	}

	/**
	 * Returns the tipologia rich pubblic persistence.
	 *
	 * @return the tipologia rich pubblic persistence
	 */
	public TipologiaRichPubblicPersistence getTipologiaRichPubblicPersistence() {
		return tipologiaRichPubblicPersistence;
	}

	/**
	 * Sets the tipologia rich pubblic persistence.
	 *
	 * @param tipologiaRichPubblicPersistence the tipologia rich pubblic persistence
	 */
	public void setTipologiaRichPubblicPersistence(
		TipologiaRichPubblicPersistence tipologiaRichPubblicPersistence) {
		this.tipologiaRichPubblicPersistence = tipologiaRichPubblicPersistence;
	}

	/**
	 * Returns the tipologia stampanti local service.
	 *
	 * @return the tipologia stampanti local service
	 */
	public service.intranet.mef.service.TipologiaStampantiLocalService getTipologiaStampantiLocalService() {
		return tipologiaStampantiLocalService;
	}

	/**
	 * Sets the tipologia stampanti local service.
	 *
	 * @param tipologiaStampantiLocalService the tipologia stampanti local service
	 */
	public void setTipologiaStampantiLocalService(
		service.intranet.mef.service.TipologiaStampantiLocalService tipologiaStampantiLocalService) {
		this.tipologiaStampantiLocalService = tipologiaStampantiLocalService;
	}

	/**
	 * Returns the tipologia stampanti remote service.
	 *
	 * @return the tipologia stampanti remote service
	 */
	public service.intranet.mef.service.TipologiaStampantiService getTipologiaStampantiService() {
		return tipologiaStampantiService;
	}

	/**
	 * Sets the tipologia stampanti remote service.
	 *
	 * @param tipologiaStampantiService the tipologia stampanti remote service
	 */
	public void setTipologiaStampantiService(
		service.intranet.mef.service.TipologiaStampantiService tipologiaStampantiService) {
		this.tipologiaStampantiService = tipologiaStampantiService;
	}

	/**
	 * Returns the tipologia stampanti persistence.
	 *
	 * @return the tipologia stampanti persistence
	 */
	public TipologiaStampantiPersistence getTipologiaStampantiPersistence() {
		return tipologiaStampantiPersistence;
	}

	/**
	 * Sets the tipologia stampanti persistence.
	 *
	 * @param tipologiaStampantiPersistence the tipologia stampanti persistence
	 */
	public void setTipologiaStampantiPersistence(
		TipologiaStampantiPersistence tipologiaStampantiPersistence) {
		this.tipologiaStampantiPersistence = tipologiaStampantiPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return LogisticaServizioService.class.getName();
	}

	protected Class<?> getModelClass() {
		return LogisticaServizio.class;
	}

	protected String getModelClassName() {
		return LogisticaServizio.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = logisticaServizioPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = service.intranet.mef.service.AssetLocalService.class)
	protected service.intranet.mef.service.AssetLocalService assetLocalService;
	@BeanReference(type = service.intranet.mef.service.AssetService.class)
	protected service.intranet.mef.service.AssetService assetService;
	@BeanReference(type = AssetPersistence.class)
	protected AssetPersistence assetPersistence;
	@BeanReference(type = service.intranet.mef.service.BadgeRichiesteLocalService.class)
	protected service.intranet.mef.service.BadgeRichiesteLocalService badgeRichiesteLocalService;
	@BeanReference(type = service.intranet.mef.service.BadgeRichiesteService.class)
	protected service.intranet.mef.service.BadgeRichiesteService badgeRichiesteService;
	@BeanReference(type = BadgeRichiestePersistence.class)
	protected BadgeRichiestePersistence badgeRichiestePersistence;
	@BeanReference(type = service.intranet.mef.service.BeneInvLocalService.class)
	protected service.intranet.mef.service.BeneInvLocalService beneInvLocalService;
	@BeanReference(type = service.intranet.mef.service.BeneInvService.class)
	protected service.intranet.mef.service.BeneInvService beneInvService;
	@BeanReference(type = BeneInvPersistence.class)
	protected BeneInvPersistence beneInvPersistence;
	@BeanReference(type = service.intranet.mef.service.BeneInvRichiestoLocalService.class)
	protected service.intranet.mef.service.BeneInvRichiestoLocalService beneInvRichiestoLocalService;
	@BeanReference(type = service.intranet.mef.service.BeneInvRichiestoService.class)
	protected service.intranet.mef.service.BeneInvRichiestoService beneInvRichiestoService;
	@BeanReference(type = BeneInvRichiestoPersistence.class)
	protected BeneInvRichiestoPersistence beneInvRichiestoPersistence;
	@BeanReference(type = service.intranet.mef.service.HardwareTecniciLocalService.class)
	protected service.intranet.mef.service.HardwareTecniciLocalService hardwareTecniciLocalService;
	@BeanReference(type = service.intranet.mef.service.HardwareTecniciService.class)
	protected service.intranet.mef.service.HardwareTecniciService hardwareTecniciService;
	@BeanReference(type = HardwareTecniciPersistence.class)
	protected HardwareTecniciPersistence hardwareTecniciPersistence;
	@BeanReference(type = service.intranet.mef.service.LogisticaRichiesteLocalService.class)
	protected service.intranet.mef.service.LogisticaRichiesteLocalService logisticaRichiesteLocalService;
	@BeanReference(type = service.intranet.mef.service.LogisticaRichiesteService.class)
	protected service.intranet.mef.service.LogisticaRichiesteService logisticaRichiesteService;
	@BeanReference(type = LogisticaRichiestePersistence.class)
	protected LogisticaRichiestePersistence logisticaRichiestePersistence;
	@BeanReference(type = service.intranet.mef.service.LogisticaServizioLocalService.class)
	protected service.intranet.mef.service.LogisticaServizioLocalService logisticaServizioLocalService;
	@BeanReference(type = LogisticaServizioService.class)
	protected LogisticaServizioService logisticaServizioService;
	@BeanReference(type = LogisticaServizioPersistence.class)
	protected LogisticaServizioPersistence logisticaServizioPersistence;
	@BeanReference(type = service.intranet.mef.service.LogisticaStatoLocalService.class)
	protected service.intranet.mef.service.LogisticaStatoLocalService logisticaStatoLocalService;
	@BeanReference(type = service.intranet.mef.service.LogisticaStatoService.class)
	protected service.intranet.mef.service.LogisticaStatoService logisticaStatoService;
	@BeanReference(type = LogisticaStatoPersistence.class)
	protected LogisticaStatoPersistence logisticaStatoPersistence;
	@BeanReference(type = service.intranet.mef.service.LogisticaValutazioneLocalService.class)
	protected service.intranet.mef.service.LogisticaValutazioneLocalService logisticaValutazioneLocalService;
	@BeanReference(type = service.intranet.mef.service.LogisticaValutazioneService.class)
	protected service.intranet.mef.service.LogisticaValutazioneService logisticaValutazioneService;
	@BeanReference(type = LogisticaValutazionePersistence.class)
	protected LogisticaValutazionePersistence logisticaValutazionePersistence;
	@BeanReference(type = service.intranet.mef.service.ModuloTrasportiLocalService.class)
	protected service.intranet.mef.service.ModuloTrasportiLocalService moduloTrasportiLocalService;
	@BeanReference(type = service.intranet.mef.service.ModuloTrasportiService.class)
	protected service.intranet.mef.service.ModuloTrasportiService moduloTrasportiService;
	@BeanReference(type = ModuloTrasportiPersistence.class)
	protected ModuloTrasportiPersistence moduloTrasportiPersistence;
	@BeanReference(type = service.intranet.mef.service.PeriodicitaRichPubblicLocalService.class)
	protected service.intranet.mef.service.PeriodicitaRichPubblicLocalService periodicitaRichPubblicLocalService;
	@BeanReference(type = service.intranet.mef.service.PeriodicitaRichPubblicService.class)
	protected service.intranet.mef.service.PeriodicitaRichPubblicService periodicitaRichPubblicService;
	@BeanReference(type = PeriodicitaRichPubblicPersistence.class)
	protected PeriodicitaRichPubblicPersistence periodicitaRichPubblicPersistence;
	@BeanReference(type = service.intranet.mef.service.RichiestaBeneInvLocalService.class)
	protected service.intranet.mef.service.RichiestaBeneInvLocalService richiestaBeneInvLocalService;
	@BeanReference(type = service.intranet.mef.service.RichiestaBeneInvService.class)
	protected service.intranet.mef.service.RichiestaBeneInvService richiestaBeneInvService;
	@BeanReference(type = RichiestaBeneInvPersistence.class)
	protected RichiestaBeneInvPersistence richiestaBeneInvPersistence;
	@BeanReference(type = RichiestaBeneInvFinder.class)
	protected RichiestaBeneInvFinder richiestaBeneInvFinder;
	@BeanReference(type = service.intranet.mef.service.RichiestaInterventiLocalService.class)
	protected service.intranet.mef.service.RichiestaInterventiLocalService richiestaInterventiLocalService;
	@BeanReference(type = service.intranet.mef.service.RichiestaInterventiService.class)
	protected service.intranet.mef.service.RichiestaInterventiService richiestaInterventiService;
	@BeanReference(type = RichiestaInterventiPersistence.class)
	protected RichiestaInterventiPersistence richiestaInterventiPersistence;
	@BeanReference(type = service.intranet.mef.service.RichiestaPubblicSitiLocalService.class)
	protected service.intranet.mef.service.RichiestaPubblicSitiLocalService richiestaPubblicSitiLocalService;
	@BeanReference(type = service.intranet.mef.service.RichiestaPubblicSitiService.class)
	protected service.intranet.mef.service.RichiestaPubblicSitiService richiestaPubblicSitiService;
	@BeanReference(type = RichiestaPubblicSitiPersistence.class)
	protected RichiestaPubblicSitiPersistence richiestaPubblicSitiPersistence;
	@BeanReference(type = service.intranet.mef.service.RichiesteHWLocalService.class)
	protected service.intranet.mef.service.RichiesteHWLocalService richiesteHWLocalService;
	@BeanReference(type = service.intranet.mef.service.RichiesteHWService.class)
	protected service.intranet.mef.service.RichiesteHWService richiesteHWService;
	@BeanReference(type = RichiesteHWPersistence.class)
	protected RichiesteHWPersistence richiesteHWPersistence;
	@BeanReference(type = service.intranet.mef.service.RichiesteUtenzaLocalService.class)
	protected service.intranet.mef.service.RichiesteUtenzaLocalService richiesteUtenzaLocalService;
	@BeanReference(type = service.intranet.mef.service.RichiesteUtenzaService.class)
	protected service.intranet.mef.service.RichiesteUtenzaService richiesteUtenzaService;
	@BeanReference(type = RichiesteUtenzaPersistence.class)
	protected RichiesteUtenzaPersistence richiesteUtenzaPersistence;
	@BeanReference(type = service.intranet.mef.service.StatoRichBeneInvLocalService.class)
	protected service.intranet.mef.service.StatoRichBeneInvLocalService statoRichBeneInvLocalService;
	@BeanReference(type = service.intranet.mef.service.StatoRichBeneInvService.class)
	protected service.intranet.mef.service.StatoRichBeneInvService statoRichBeneInvService;
	@BeanReference(type = StatoRichBeneInvPersistence.class)
	protected StatoRichBeneInvPersistence statoRichBeneInvPersistence;
	@BeanReference(type = service.intranet.mef.service.TipoBeneInvLocalService.class)
	protected service.intranet.mef.service.TipoBeneInvLocalService tipoBeneInvLocalService;
	@BeanReference(type = service.intranet.mef.service.TipoBeneInvService.class)
	protected service.intranet.mef.service.TipoBeneInvService tipoBeneInvService;
	@BeanReference(type = TipoBeneInvPersistence.class)
	protected TipoBeneInvPersistence tipoBeneInvPersistence;
	@BeanReference(type = service.intranet.mef.service.TipologiaComputerLocalService.class)
	protected service.intranet.mef.service.TipologiaComputerLocalService tipologiaComputerLocalService;
	@BeanReference(type = service.intranet.mef.service.TipologiaComputerService.class)
	protected service.intranet.mef.service.TipologiaComputerService tipologiaComputerService;
	@BeanReference(type = TipologiaComputerPersistence.class)
	protected TipologiaComputerPersistence tipologiaComputerPersistence;
	@BeanReference(type = service.intranet.mef.service.TipologiaDispositiviLocalService.class)
	protected service.intranet.mef.service.TipologiaDispositiviLocalService tipologiaDispositiviLocalService;
	@BeanReference(type = service.intranet.mef.service.TipologiaDispositiviService.class)
	protected service.intranet.mef.service.TipologiaDispositiviService tipologiaDispositiviService;
	@BeanReference(type = TipologiaDispositiviPersistence.class)
	protected TipologiaDispositiviPersistence tipologiaDispositiviPersistence;
	@BeanReference(type = service.intranet.mef.service.TipologiaRichPubblicLocalService.class)
	protected service.intranet.mef.service.TipologiaRichPubblicLocalService tipologiaRichPubblicLocalService;
	@BeanReference(type = service.intranet.mef.service.TipologiaRichPubblicService.class)
	protected service.intranet.mef.service.TipologiaRichPubblicService tipologiaRichPubblicService;
	@BeanReference(type = TipologiaRichPubblicPersistence.class)
	protected TipologiaRichPubblicPersistence tipologiaRichPubblicPersistence;
	@BeanReference(type = service.intranet.mef.service.TipologiaStampantiLocalService.class)
	protected service.intranet.mef.service.TipologiaStampantiLocalService tipologiaStampantiLocalService;
	@BeanReference(type = service.intranet.mef.service.TipologiaStampantiService.class)
	protected service.intranet.mef.service.TipologiaStampantiService tipologiaStampantiService;
	@BeanReference(type = TipologiaStampantiPersistence.class)
	protected TipologiaStampantiPersistence tipologiaStampantiPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}