/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import service.intranet.mef.model.ModuloTrasporti;
import service.intranet.mef.service.ModuloTrasportiLocalService;
import service.intranet.mef.service.persistence.AssetPersistence;
import service.intranet.mef.service.persistence.BadgeRichiestePersistence;
import service.intranet.mef.service.persistence.BeneInvPersistence;
import service.intranet.mef.service.persistence.BeneInvRichiestoPersistence;
import service.intranet.mef.service.persistence.HardwareTecniciPersistence;
import service.intranet.mef.service.persistence.LogisticaRichiestePersistence;
import service.intranet.mef.service.persistence.LogisticaServizioPersistence;
import service.intranet.mef.service.persistence.LogisticaStatoPersistence;
import service.intranet.mef.service.persistence.LogisticaValutazionePersistence;
import service.intranet.mef.service.persistence.ModuloTrasportiPersistence;
import service.intranet.mef.service.persistence.PeriodicitaRichPubblicPersistence;
import service.intranet.mef.service.persistence.RichiestaBeneInvFinder;
import service.intranet.mef.service.persistence.RichiestaBeneInvPersistence;
import service.intranet.mef.service.persistence.RichiestaInterventiPersistence;
import service.intranet.mef.service.persistence.RichiestaPubblicSitiPersistence;
import service.intranet.mef.service.persistence.RichiesteHWPersistence;
import service.intranet.mef.service.persistence.RichiesteUtenzaPersistence;
import service.intranet.mef.service.persistence.StatoRichBeneInvPersistence;
import service.intranet.mef.service.persistence.TipoBeneInvPersistence;
import service.intranet.mef.service.persistence.TipologiaComputerPersistence;
import service.intranet.mef.service.persistence.TipologiaDispositiviPersistence;
import service.intranet.mef.service.persistence.TipologiaRichPubblicPersistence;
import service.intranet.mef.service.persistence.TipologiaStampantiPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the modulo trasporti local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link service.intranet.mef.service.impl.ModuloTrasportiLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see service.intranet.mef.service.impl.ModuloTrasportiLocalServiceImpl
 * @see service.intranet.mef.service.ModuloTrasportiLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class ModuloTrasportiLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements ModuloTrasportiLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link service.intranet.mef.service.ModuloTrasportiLocalServiceUtil} to access the modulo trasporti local service.
	 */

	/**
	 * Adds the modulo trasporti to the database. Also notifies the appropriate model listeners.
	 *
	 * @param moduloTrasporti the modulo trasporti
	 * @return the modulo trasporti that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ModuloTrasporti addModuloTrasporti(ModuloTrasporti moduloTrasporti) {
		moduloTrasporti.setNew(true);

		return moduloTrasportiPersistence.update(moduloTrasporti);
	}

	/**
	 * Creates a new modulo trasporti with the primary key. Does not add the modulo trasporti to the database.
	 *
	 * @param id_modulo_trasporti the primary key for the new modulo trasporti
	 * @return the new modulo trasporti
	 */
	@Override
	public ModuloTrasporti createModuloTrasporti(long id_modulo_trasporti) {
		return moduloTrasportiPersistence.create(id_modulo_trasporti);
	}

	/**
	 * Deletes the modulo trasporti with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id_modulo_trasporti the primary key of the modulo trasporti
	 * @return the modulo trasporti that was removed
	 * @throws PortalException if a modulo trasporti with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ModuloTrasporti deleteModuloTrasporti(long id_modulo_trasporti)
		throws PortalException {
		return moduloTrasportiPersistence.remove(id_modulo_trasporti);
	}

	/**
	 * Deletes the modulo trasporti from the database. Also notifies the appropriate model listeners.
	 *
	 * @param moduloTrasporti the modulo trasporti
	 * @return the modulo trasporti that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ModuloTrasporti deleteModuloTrasporti(
		ModuloTrasporti moduloTrasporti) {
		return moduloTrasportiPersistence.remove(moduloTrasporti);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(ModuloTrasporti.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return moduloTrasportiPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link service.intranet.mef.model.impl.ModuloTrasportiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return moduloTrasportiPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link service.intranet.mef.model.impl.ModuloTrasportiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return moduloTrasportiPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return moduloTrasportiPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return moduloTrasportiPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public ModuloTrasporti fetchModuloTrasporti(long id_modulo_trasporti) {
		return moduloTrasportiPersistence.fetchByPrimaryKey(id_modulo_trasporti);
	}

	/**
	 * Returns the modulo trasporti with the primary key.
	 *
	 * @param id_modulo_trasporti the primary key of the modulo trasporti
	 * @return the modulo trasporti
	 * @throws PortalException if a modulo trasporti with the primary key could not be found
	 */
	@Override
	public ModuloTrasporti getModuloTrasporti(long id_modulo_trasporti)
		throws PortalException {
		return moduloTrasportiPersistence.findByPrimaryKey(id_modulo_trasporti);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(moduloTrasportiLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ModuloTrasporti.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id_modulo_trasporti");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(moduloTrasportiLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ModuloTrasporti.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"id_modulo_trasporti");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(moduloTrasportiLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ModuloTrasporti.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id_modulo_trasporti");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return moduloTrasportiLocalService.deleteModuloTrasporti((ModuloTrasporti)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return moduloTrasportiPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the modulo trasportis.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link service.intranet.mef.model.impl.ModuloTrasportiModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of modulo trasportis
	 * @param end the upper bound of the range of modulo trasportis (not inclusive)
	 * @return the range of modulo trasportis
	 */
	@Override
	public List<ModuloTrasporti> getModuloTrasportis(int start, int end) {
		return moduloTrasportiPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of modulo trasportis.
	 *
	 * @return the number of modulo trasportis
	 */
	@Override
	public int getModuloTrasportisCount() {
		return moduloTrasportiPersistence.countAll();
	}

	/**
	 * Updates the modulo trasporti in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param moduloTrasporti the modulo trasporti
	 * @return the modulo trasporti that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ModuloTrasporti updateModuloTrasporti(
		ModuloTrasporti moduloTrasporti) {
		return moduloTrasportiPersistence.update(moduloTrasporti);
	}

	/**
	 * Returns the asset local service.
	 *
	 * @return the asset local service
	 */
	public service.intranet.mef.service.AssetLocalService getAssetLocalService() {
		return assetLocalService;
	}

	/**
	 * Sets the asset local service.
	 *
	 * @param assetLocalService the asset local service
	 */
	public void setAssetLocalService(
		service.intranet.mef.service.AssetLocalService assetLocalService) {
		this.assetLocalService = assetLocalService;
	}

	/**
	 * Returns the asset persistence.
	 *
	 * @return the asset persistence
	 */
	public AssetPersistence getAssetPersistence() {
		return assetPersistence;
	}

	/**
	 * Sets the asset persistence.
	 *
	 * @param assetPersistence the asset persistence
	 */
	public void setAssetPersistence(AssetPersistence assetPersistence) {
		this.assetPersistence = assetPersistence;
	}

	/**
	 * Returns the badge richieste local service.
	 *
	 * @return the badge richieste local service
	 */
	public service.intranet.mef.service.BadgeRichiesteLocalService getBadgeRichiesteLocalService() {
		return badgeRichiesteLocalService;
	}

	/**
	 * Sets the badge richieste local service.
	 *
	 * @param badgeRichiesteLocalService the badge richieste local service
	 */
	public void setBadgeRichiesteLocalService(
		service.intranet.mef.service.BadgeRichiesteLocalService badgeRichiesteLocalService) {
		this.badgeRichiesteLocalService = badgeRichiesteLocalService;
	}

	/**
	 * Returns the badge richieste persistence.
	 *
	 * @return the badge richieste persistence
	 */
	public BadgeRichiestePersistence getBadgeRichiestePersistence() {
		return badgeRichiestePersistence;
	}

	/**
	 * Sets the badge richieste persistence.
	 *
	 * @param badgeRichiestePersistence the badge richieste persistence
	 */
	public void setBadgeRichiestePersistence(
		BadgeRichiestePersistence badgeRichiestePersistence) {
		this.badgeRichiestePersistence = badgeRichiestePersistence;
	}

	/**
	 * Returns the bene inv local service.
	 *
	 * @return the bene inv local service
	 */
	public service.intranet.mef.service.BeneInvLocalService getBeneInvLocalService() {
		return beneInvLocalService;
	}

	/**
	 * Sets the bene inv local service.
	 *
	 * @param beneInvLocalService the bene inv local service
	 */
	public void setBeneInvLocalService(
		service.intranet.mef.service.BeneInvLocalService beneInvLocalService) {
		this.beneInvLocalService = beneInvLocalService;
	}

	/**
	 * Returns the bene inv persistence.
	 *
	 * @return the bene inv persistence
	 */
	public BeneInvPersistence getBeneInvPersistence() {
		return beneInvPersistence;
	}

	/**
	 * Sets the bene inv persistence.
	 *
	 * @param beneInvPersistence the bene inv persistence
	 */
	public void setBeneInvPersistence(BeneInvPersistence beneInvPersistence) {
		this.beneInvPersistence = beneInvPersistence;
	}

	/**
	 * Returns the bene inv richiesto local service.
	 *
	 * @return the bene inv richiesto local service
	 */
	public service.intranet.mef.service.BeneInvRichiestoLocalService getBeneInvRichiestoLocalService() {
		return beneInvRichiestoLocalService;
	}

	/**
	 * Sets the bene inv richiesto local service.
	 *
	 * @param beneInvRichiestoLocalService the bene inv richiesto local service
	 */
	public void setBeneInvRichiestoLocalService(
		service.intranet.mef.service.BeneInvRichiestoLocalService beneInvRichiestoLocalService) {
		this.beneInvRichiestoLocalService = beneInvRichiestoLocalService;
	}

	/**
	 * Returns the bene inv richiesto persistence.
	 *
	 * @return the bene inv richiesto persistence
	 */
	public BeneInvRichiestoPersistence getBeneInvRichiestoPersistence() {
		return beneInvRichiestoPersistence;
	}

	/**
	 * Sets the bene inv richiesto persistence.
	 *
	 * @param beneInvRichiestoPersistence the bene inv richiesto persistence
	 */
	public void setBeneInvRichiestoPersistence(
		BeneInvRichiestoPersistence beneInvRichiestoPersistence) {
		this.beneInvRichiestoPersistence = beneInvRichiestoPersistence;
	}

	/**
	 * Returns the hardware tecnici local service.
	 *
	 * @return the hardware tecnici local service
	 */
	public service.intranet.mef.service.HardwareTecniciLocalService getHardwareTecniciLocalService() {
		return hardwareTecniciLocalService;
	}

	/**
	 * Sets the hardware tecnici local service.
	 *
	 * @param hardwareTecniciLocalService the hardware tecnici local service
	 */
	public void setHardwareTecniciLocalService(
		service.intranet.mef.service.HardwareTecniciLocalService hardwareTecniciLocalService) {
		this.hardwareTecniciLocalService = hardwareTecniciLocalService;
	}

	/**
	 * Returns the hardware tecnici persistence.
	 *
	 * @return the hardware tecnici persistence
	 */
	public HardwareTecniciPersistence getHardwareTecniciPersistence() {
		return hardwareTecniciPersistence;
	}

	/**
	 * Sets the hardware tecnici persistence.
	 *
	 * @param hardwareTecniciPersistence the hardware tecnici persistence
	 */
	public void setHardwareTecniciPersistence(
		HardwareTecniciPersistence hardwareTecniciPersistence) {
		this.hardwareTecniciPersistence = hardwareTecniciPersistence;
	}

	/**
	 * Returns the logistica richieste local service.
	 *
	 * @return the logistica richieste local service
	 */
	public service.intranet.mef.service.LogisticaRichiesteLocalService getLogisticaRichiesteLocalService() {
		return logisticaRichiesteLocalService;
	}

	/**
	 * Sets the logistica richieste local service.
	 *
	 * @param logisticaRichiesteLocalService the logistica richieste local service
	 */
	public void setLogisticaRichiesteLocalService(
		service.intranet.mef.service.LogisticaRichiesteLocalService logisticaRichiesteLocalService) {
		this.logisticaRichiesteLocalService = logisticaRichiesteLocalService;
	}

	/**
	 * Returns the logistica richieste persistence.
	 *
	 * @return the logistica richieste persistence
	 */
	public LogisticaRichiestePersistence getLogisticaRichiestePersistence() {
		return logisticaRichiestePersistence;
	}

	/**
	 * Sets the logistica richieste persistence.
	 *
	 * @param logisticaRichiestePersistence the logistica richieste persistence
	 */
	public void setLogisticaRichiestePersistence(
		LogisticaRichiestePersistence logisticaRichiestePersistence) {
		this.logisticaRichiestePersistence = logisticaRichiestePersistence;
	}

	/**
	 * Returns the logistica servizio local service.
	 *
	 * @return the logistica servizio local service
	 */
	public service.intranet.mef.service.LogisticaServizioLocalService getLogisticaServizioLocalService() {
		return logisticaServizioLocalService;
	}

	/**
	 * Sets the logistica servizio local service.
	 *
	 * @param logisticaServizioLocalService the logistica servizio local service
	 */
	public void setLogisticaServizioLocalService(
		service.intranet.mef.service.LogisticaServizioLocalService logisticaServizioLocalService) {
		this.logisticaServizioLocalService = logisticaServizioLocalService;
	}

	/**
	 * Returns the logistica servizio persistence.
	 *
	 * @return the logistica servizio persistence
	 */
	public LogisticaServizioPersistence getLogisticaServizioPersistence() {
		return logisticaServizioPersistence;
	}

	/**
	 * Sets the logistica servizio persistence.
	 *
	 * @param logisticaServizioPersistence the logistica servizio persistence
	 */
	public void setLogisticaServizioPersistence(
		LogisticaServizioPersistence logisticaServizioPersistence) {
		this.logisticaServizioPersistence = logisticaServizioPersistence;
	}

	/**
	 * Returns the logistica stato local service.
	 *
	 * @return the logistica stato local service
	 */
	public service.intranet.mef.service.LogisticaStatoLocalService getLogisticaStatoLocalService() {
		return logisticaStatoLocalService;
	}

	/**
	 * Sets the logistica stato local service.
	 *
	 * @param logisticaStatoLocalService the logistica stato local service
	 */
	public void setLogisticaStatoLocalService(
		service.intranet.mef.service.LogisticaStatoLocalService logisticaStatoLocalService) {
		this.logisticaStatoLocalService = logisticaStatoLocalService;
	}

	/**
	 * Returns the logistica stato persistence.
	 *
	 * @return the logistica stato persistence
	 */
	public LogisticaStatoPersistence getLogisticaStatoPersistence() {
		return logisticaStatoPersistence;
	}

	/**
	 * Sets the logistica stato persistence.
	 *
	 * @param logisticaStatoPersistence the logistica stato persistence
	 */
	public void setLogisticaStatoPersistence(
		LogisticaStatoPersistence logisticaStatoPersistence) {
		this.logisticaStatoPersistence = logisticaStatoPersistence;
	}

	/**
	 * Returns the logistica valutazione local service.
	 *
	 * @return the logistica valutazione local service
	 */
	public service.intranet.mef.service.LogisticaValutazioneLocalService getLogisticaValutazioneLocalService() {
		return logisticaValutazioneLocalService;
	}

	/**
	 * Sets the logistica valutazione local service.
	 *
	 * @param logisticaValutazioneLocalService the logistica valutazione local service
	 */
	public void setLogisticaValutazioneLocalService(
		service.intranet.mef.service.LogisticaValutazioneLocalService logisticaValutazioneLocalService) {
		this.logisticaValutazioneLocalService = logisticaValutazioneLocalService;
	}

	/**
	 * Returns the logistica valutazione persistence.
	 *
	 * @return the logistica valutazione persistence
	 */
	public LogisticaValutazionePersistence getLogisticaValutazionePersistence() {
		return logisticaValutazionePersistence;
	}

	/**
	 * Sets the logistica valutazione persistence.
	 *
	 * @param logisticaValutazionePersistence the logistica valutazione persistence
	 */
	public void setLogisticaValutazionePersistence(
		LogisticaValutazionePersistence logisticaValutazionePersistence) {
		this.logisticaValutazionePersistence = logisticaValutazionePersistence;
	}

	/**
	 * Returns the modulo trasporti local service.
	 *
	 * @return the modulo trasporti local service
	 */
	public ModuloTrasportiLocalService getModuloTrasportiLocalService() {
		return moduloTrasportiLocalService;
	}

	/**
	 * Sets the modulo trasporti local service.
	 *
	 * @param moduloTrasportiLocalService the modulo trasporti local service
	 */
	public void setModuloTrasportiLocalService(
		ModuloTrasportiLocalService moduloTrasportiLocalService) {
		this.moduloTrasportiLocalService = moduloTrasportiLocalService;
	}

	/**
	 * Returns the modulo trasporti persistence.
	 *
	 * @return the modulo trasporti persistence
	 */
	public ModuloTrasportiPersistence getModuloTrasportiPersistence() {
		return moduloTrasportiPersistence;
	}

	/**
	 * Sets the modulo trasporti persistence.
	 *
	 * @param moduloTrasportiPersistence the modulo trasporti persistence
	 */
	public void setModuloTrasportiPersistence(
		ModuloTrasportiPersistence moduloTrasportiPersistence) {
		this.moduloTrasportiPersistence = moduloTrasportiPersistence;
	}

	/**
	 * Returns the periodicita rich pubblic local service.
	 *
	 * @return the periodicita rich pubblic local service
	 */
	public service.intranet.mef.service.PeriodicitaRichPubblicLocalService getPeriodicitaRichPubblicLocalService() {
		return periodicitaRichPubblicLocalService;
	}

	/**
	 * Sets the periodicita rich pubblic local service.
	 *
	 * @param periodicitaRichPubblicLocalService the periodicita rich pubblic local service
	 */
	public void setPeriodicitaRichPubblicLocalService(
		service.intranet.mef.service.PeriodicitaRichPubblicLocalService periodicitaRichPubblicLocalService) {
		this.periodicitaRichPubblicLocalService = periodicitaRichPubblicLocalService;
	}

	/**
	 * Returns the periodicita rich pubblic persistence.
	 *
	 * @return the periodicita rich pubblic persistence
	 */
	public PeriodicitaRichPubblicPersistence getPeriodicitaRichPubblicPersistence() {
		return periodicitaRichPubblicPersistence;
	}

	/**
	 * Sets the periodicita rich pubblic persistence.
	 *
	 * @param periodicitaRichPubblicPersistence the periodicita rich pubblic persistence
	 */
	public void setPeriodicitaRichPubblicPersistence(
		PeriodicitaRichPubblicPersistence periodicitaRichPubblicPersistence) {
		this.periodicitaRichPubblicPersistence = periodicitaRichPubblicPersistence;
	}

	/**
	 * Returns the richiesta bene inv local service.
	 *
	 * @return the richiesta bene inv local service
	 */
	public service.intranet.mef.service.RichiestaBeneInvLocalService getRichiestaBeneInvLocalService() {
		return richiestaBeneInvLocalService;
	}

	/**
	 * Sets the richiesta bene inv local service.
	 *
	 * @param richiestaBeneInvLocalService the richiesta bene inv local service
	 */
	public void setRichiestaBeneInvLocalService(
		service.intranet.mef.service.RichiestaBeneInvLocalService richiestaBeneInvLocalService) {
		this.richiestaBeneInvLocalService = richiestaBeneInvLocalService;
	}

	/**
	 * Returns the richiesta bene inv persistence.
	 *
	 * @return the richiesta bene inv persistence
	 */
	public RichiestaBeneInvPersistence getRichiestaBeneInvPersistence() {
		return richiestaBeneInvPersistence;
	}

	/**
	 * Sets the richiesta bene inv persistence.
	 *
	 * @param richiestaBeneInvPersistence the richiesta bene inv persistence
	 */
	public void setRichiestaBeneInvPersistence(
		RichiestaBeneInvPersistence richiestaBeneInvPersistence) {
		this.richiestaBeneInvPersistence = richiestaBeneInvPersistence;
	}

	/**
	 * Returns the richiesta bene inv finder.
	 *
	 * @return the richiesta bene inv finder
	 */
	public RichiestaBeneInvFinder getRichiestaBeneInvFinder() {
		return richiestaBeneInvFinder;
	}

	/**
	 * Sets the richiesta bene inv finder.
	 *
	 * @param richiestaBeneInvFinder the richiesta bene inv finder
	 */
	public void setRichiestaBeneInvFinder(
		RichiestaBeneInvFinder richiestaBeneInvFinder) {
		this.richiestaBeneInvFinder = richiestaBeneInvFinder;
	}

	/**
	 * Returns the richiesta interventi local service.
	 *
	 * @return the richiesta interventi local service
	 */
	public service.intranet.mef.service.RichiestaInterventiLocalService getRichiestaInterventiLocalService() {
		return richiestaInterventiLocalService;
	}

	/**
	 * Sets the richiesta interventi local service.
	 *
	 * @param richiestaInterventiLocalService the richiesta interventi local service
	 */
	public void setRichiestaInterventiLocalService(
		service.intranet.mef.service.RichiestaInterventiLocalService richiestaInterventiLocalService) {
		this.richiestaInterventiLocalService = richiestaInterventiLocalService;
	}

	/**
	 * Returns the richiesta interventi persistence.
	 *
	 * @return the richiesta interventi persistence
	 */
	public RichiestaInterventiPersistence getRichiestaInterventiPersistence() {
		return richiestaInterventiPersistence;
	}

	/**
	 * Sets the richiesta interventi persistence.
	 *
	 * @param richiestaInterventiPersistence the richiesta interventi persistence
	 */
	public void setRichiestaInterventiPersistence(
		RichiestaInterventiPersistence richiestaInterventiPersistence) {
		this.richiestaInterventiPersistence = richiestaInterventiPersistence;
	}

	/**
	 * Returns the richiesta pubblic siti local service.
	 *
	 * @return the richiesta pubblic siti local service
	 */
	public service.intranet.mef.service.RichiestaPubblicSitiLocalService getRichiestaPubblicSitiLocalService() {
		return richiestaPubblicSitiLocalService;
	}

	/**
	 * Sets the richiesta pubblic siti local service.
	 *
	 * @param richiestaPubblicSitiLocalService the richiesta pubblic siti local service
	 */
	public void setRichiestaPubblicSitiLocalService(
		service.intranet.mef.service.RichiestaPubblicSitiLocalService richiestaPubblicSitiLocalService) {
		this.richiestaPubblicSitiLocalService = richiestaPubblicSitiLocalService;
	}

	/**
	 * Returns the richiesta pubblic siti persistence.
	 *
	 * @return the richiesta pubblic siti persistence
	 */
	public RichiestaPubblicSitiPersistence getRichiestaPubblicSitiPersistence() {
		return richiestaPubblicSitiPersistence;
	}

	/**
	 * Sets the richiesta pubblic siti persistence.
	 *
	 * @param richiestaPubblicSitiPersistence the richiesta pubblic siti persistence
	 */
	public void setRichiestaPubblicSitiPersistence(
		RichiestaPubblicSitiPersistence richiestaPubblicSitiPersistence) {
		this.richiestaPubblicSitiPersistence = richiestaPubblicSitiPersistence;
	}

	/**
	 * Returns the richieste h w local service.
	 *
	 * @return the richieste h w local service
	 */
	public service.intranet.mef.service.RichiesteHWLocalService getRichiesteHWLocalService() {
		return richiesteHWLocalService;
	}

	/**
	 * Sets the richieste h w local service.
	 *
	 * @param richiesteHWLocalService the richieste h w local service
	 */
	public void setRichiesteHWLocalService(
		service.intranet.mef.service.RichiesteHWLocalService richiesteHWLocalService) {
		this.richiesteHWLocalService = richiesteHWLocalService;
	}

	/**
	 * Returns the richieste h w persistence.
	 *
	 * @return the richieste h w persistence
	 */
	public RichiesteHWPersistence getRichiesteHWPersistence() {
		return richiesteHWPersistence;
	}

	/**
	 * Sets the richieste h w persistence.
	 *
	 * @param richiesteHWPersistence the richieste h w persistence
	 */
	public void setRichiesteHWPersistence(
		RichiesteHWPersistence richiesteHWPersistence) {
		this.richiesteHWPersistence = richiesteHWPersistence;
	}

	/**
	 * Returns the richieste utenza local service.
	 *
	 * @return the richieste utenza local service
	 */
	public service.intranet.mef.service.RichiesteUtenzaLocalService getRichiesteUtenzaLocalService() {
		return richiesteUtenzaLocalService;
	}

	/**
	 * Sets the richieste utenza local service.
	 *
	 * @param richiesteUtenzaLocalService the richieste utenza local service
	 */
	public void setRichiesteUtenzaLocalService(
		service.intranet.mef.service.RichiesteUtenzaLocalService richiesteUtenzaLocalService) {
		this.richiesteUtenzaLocalService = richiesteUtenzaLocalService;
	}

	/**
	 * Returns the richieste utenza persistence.
	 *
	 * @return the richieste utenza persistence
	 */
	public RichiesteUtenzaPersistence getRichiesteUtenzaPersistence() {
		return richiesteUtenzaPersistence;
	}

	/**
	 * Sets the richieste utenza persistence.
	 *
	 * @param richiesteUtenzaPersistence the richieste utenza persistence
	 */
	public void setRichiesteUtenzaPersistence(
		RichiesteUtenzaPersistence richiesteUtenzaPersistence) {
		this.richiesteUtenzaPersistence = richiesteUtenzaPersistence;
	}

	/**
	 * Returns the stato rich bene inv local service.
	 *
	 * @return the stato rich bene inv local service
	 */
	public service.intranet.mef.service.StatoRichBeneInvLocalService getStatoRichBeneInvLocalService() {
		return statoRichBeneInvLocalService;
	}

	/**
	 * Sets the stato rich bene inv local service.
	 *
	 * @param statoRichBeneInvLocalService the stato rich bene inv local service
	 */
	public void setStatoRichBeneInvLocalService(
		service.intranet.mef.service.StatoRichBeneInvLocalService statoRichBeneInvLocalService) {
		this.statoRichBeneInvLocalService = statoRichBeneInvLocalService;
	}

	/**
	 * Returns the stato rich bene inv persistence.
	 *
	 * @return the stato rich bene inv persistence
	 */
	public StatoRichBeneInvPersistence getStatoRichBeneInvPersistence() {
		return statoRichBeneInvPersistence;
	}

	/**
	 * Sets the stato rich bene inv persistence.
	 *
	 * @param statoRichBeneInvPersistence the stato rich bene inv persistence
	 */
	public void setStatoRichBeneInvPersistence(
		StatoRichBeneInvPersistence statoRichBeneInvPersistence) {
		this.statoRichBeneInvPersistence = statoRichBeneInvPersistence;
	}

	/**
	 * Returns the tipo bene inv local service.
	 *
	 * @return the tipo bene inv local service
	 */
	public service.intranet.mef.service.TipoBeneInvLocalService getTipoBeneInvLocalService() {
		return tipoBeneInvLocalService;
	}

	/**
	 * Sets the tipo bene inv local service.
	 *
	 * @param tipoBeneInvLocalService the tipo bene inv local service
	 */
	public void setTipoBeneInvLocalService(
		service.intranet.mef.service.TipoBeneInvLocalService tipoBeneInvLocalService) {
		this.tipoBeneInvLocalService = tipoBeneInvLocalService;
	}

	/**
	 * Returns the tipo bene inv persistence.
	 *
	 * @return the tipo bene inv persistence
	 */
	public TipoBeneInvPersistence getTipoBeneInvPersistence() {
		return tipoBeneInvPersistence;
	}

	/**
	 * Sets the tipo bene inv persistence.
	 *
	 * @param tipoBeneInvPersistence the tipo bene inv persistence
	 */
	public void setTipoBeneInvPersistence(
		TipoBeneInvPersistence tipoBeneInvPersistence) {
		this.tipoBeneInvPersistence = tipoBeneInvPersistence;
	}

	/**
	 * Returns the tipologia computer local service.
	 *
	 * @return the tipologia computer local service
	 */
	public service.intranet.mef.service.TipologiaComputerLocalService getTipologiaComputerLocalService() {
		return tipologiaComputerLocalService;
	}

	/**
	 * Sets the tipologia computer local service.
	 *
	 * @param tipologiaComputerLocalService the tipologia computer local service
	 */
	public void setTipologiaComputerLocalService(
		service.intranet.mef.service.TipologiaComputerLocalService tipologiaComputerLocalService) {
		this.tipologiaComputerLocalService = tipologiaComputerLocalService;
	}

	/**
	 * Returns the tipologia computer persistence.
	 *
	 * @return the tipologia computer persistence
	 */
	public TipologiaComputerPersistence getTipologiaComputerPersistence() {
		return tipologiaComputerPersistence;
	}

	/**
	 * Sets the tipologia computer persistence.
	 *
	 * @param tipologiaComputerPersistence the tipologia computer persistence
	 */
	public void setTipologiaComputerPersistence(
		TipologiaComputerPersistence tipologiaComputerPersistence) {
		this.tipologiaComputerPersistence = tipologiaComputerPersistence;
	}

	/**
	 * Returns the tipologia dispositivi local service.
	 *
	 * @return the tipologia dispositivi local service
	 */
	public service.intranet.mef.service.TipologiaDispositiviLocalService getTipologiaDispositiviLocalService() {
		return tipologiaDispositiviLocalService;
	}

	/**
	 * Sets the tipologia dispositivi local service.
	 *
	 * @param tipologiaDispositiviLocalService the tipologia dispositivi local service
	 */
	public void setTipologiaDispositiviLocalService(
		service.intranet.mef.service.TipologiaDispositiviLocalService tipologiaDispositiviLocalService) {
		this.tipologiaDispositiviLocalService = tipologiaDispositiviLocalService;
	}

	/**
	 * Returns the tipologia dispositivi persistence.
	 *
	 * @return the tipologia dispositivi persistence
	 */
	public TipologiaDispositiviPersistence getTipologiaDispositiviPersistence() {
		return tipologiaDispositiviPersistence;
	}

	/**
	 * Sets the tipologia dispositivi persistence.
	 *
	 * @param tipologiaDispositiviPersistence the tipologia dispositivi persistence
	 */
	public void setTipologiaDispositiviPersistence(
		TipologiaDispositiviPersistence tipologiaDispositiviPersistence) {
		this.tipologiaDispositiviPersistence = tipologiaDispositiviPersistence;
	}

	/**
	 * Returns the tipologia rich pubblic local service.
	 *
	 * @return the tipologia rich pubblic local service
	 */
	public service.intranet.mef.service.TipologiaRichPubblicLocalService getTipologiaRichPubblicLocalService() {
		return tipologiaRichPubblicLocalService;
	}

	/**
	 * Sets the tipologia rich pubblic local service.
	 *
	 * @param tipologiaRichPubblicLocalService the tipologia rich pubblic local service
	 */
	public void setTipologiaRichPubblicLocalService(
		service.intranet.mef.service.TipologiaRichPubblicLocalService tipologiaRichPubblicLocalService) {
		this.tipologiaRichPubblicLocalService = tipologiaRichPubblicLocalService;
	}

	/**
	 * Returns the tipologia rich pubblic persistence.
	 *
	 * @return the tipologia rich pubblic persistence
	 */
	public TipologiaRichPubblicPersistence getTipologiaRichPubblicPersistence() {
		return tipologiaRichPubblicPersistence;
	}

	/**
	 * Sets the tipologia rich pubblic persistence.
	 *
	 * @param tipologiaRichPubblicPersistence the tipologia rich pubblic persistence
	 */
	public void setTipologiaRichPubblicPersistence(
		TipologiaRichPubblicPersistence tipologiaRichPubblicPersistence) {
		this.tipologiaRichPubblicPersistence = tipologiaRichPubblicPersistence;
	}

	/**
	 * Returns the tipologia stampanti local service.
	 *
	 * @return the tipologia stampanti local service
	 */
	public service.intranet.mef.service.TipologiaStampantiLocalService getTipologiaStampantiLocalService() {
		return tipologiaStampantiLocalService;
	}

	/**
	 * Sets the tipologia stampanti local service.
	 *
	 * @param tipologiaStampantiLocalService the tipologia stampanti local service
	 */
	public void setTipologiaStampantiLocalService(
		service.intranet.mef.service.TipologiaStampantiLocalService tipologiaStampantiLocalService) {
		this.tipologiaStampantiLocalService = tipologiaStampantiLocalService;
	}

	/**
	 * Returns the tipologia stampanti persistence.
	 *
	 * @return the tipologia stampanti persistence
	 */
	public TipologiaStampantiPersistence getTipologiaStampantiPersistence() {
		return tipologiaStampantiPersistence;
	}

	/**
	 * Sets the tipologia stampanti persistence.
	 *
	 * @param tipologiaStampantiPersistence the tipologia stampanti persistence
	 */
	public void setTipologiaStampantiPersistence(
		TipologiaStampantiPersistence tipologiaStampantiPersistence) {
		this.tipologiaStampantiPersistence = tipologiaStampantiPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("service.intranet.mef.model.ModuloTrasporti",
			moduloTrasportiLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"service.intranet.mef.model.ModuloTrasporti");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ModuloTrasportiLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ModuloTrasporti.class;
	}

	protected String getModelClassName() {
		return ModuloTrasporti.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = moduloTrasportiPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = service.intranet.mef.service.AssetLocalService.class)
	protected service.intranet.mef.service.AssetLocalService assetLocalService;
	@BeanReference(type = AssetPersistence.class)
	protected AssetPersistence assetPersistence;
	@BeanReference(type = service.intranet.mef.service.BadgeRichiesteLocalService.class)
	protected service.intranet.mef.service.BadgeRichiesteLocalService badgeRichiesteLocalService;
	@BeanReference(type = BadgeRichiestePersistence.class)
	protected BadgeRichiestePersistence badgeRichiestePersistence;
	@BeanReference(type = service.intranet.mef.service.BeneInvLocalService.class)
	protected service.intranet.mef.service.BeneInvLocalService beneInvLocalService;
	@BeanReference(type = BeneInvPersistence.class)
	protected BeneInvPersistence beneInvPersistence;
	@BeanReference(type = service.intranet.mef.service.BeneInvRichiestoLocalService.class)
	protected service.intranet.mef.service.BeneInvRichiestoLocalService beneInvRichiestoLocalService;
	@BeanReference(type = BeneInvRichiestoPersistence.class)
	protected BeneInvRichiestoPersistence beneInvRichiestoPersistence;
	@BeanReference(type = service.intranet.mef.service.HardwareTecniciLocalService.class)
	protected service.intranet.mef.service.HardwareTecniciLocalService hardwareTecniciLocalService;
	@BeanReference(type = HardwareTecniciPersistence.class)
	protected HardwareTecniciPersistence hardwareTecniciPersistence;
	@BeanReference(type = service.intranet.mef.service.LogisticaRichiesteLocalService.class)
	protected service.intranet.mef.service.LogisticaRichiesteLocalService logisticaRichiesteLocalService;
	@BeanReference(type = LogisticaRichiestePersistence.class)
	protected LogisticaRichiestePersistence logisticaRichiestePersistence;
	@BeanReference(type = service.intranet.mef.service.LogisticaServizioLocalService.class)
	protected service.intranet.mef.service.LogisticaServizioLocalService logisticaServizioLocalService;
	@BeanReference(type = LogisticaServizioPersistence.class)
	protected LogisticaServizioPersistence logisticaServizioPersistence;
	@BeanReference(type = service.intranet.mef.service.LogisticaStatoLocalService.class)
	protected service.intranet.mef.service.LogisticaStatoLocalService logisticaStatoLocalService;
	@BeanReference(type = LogisticaStatoPersistence.class)
	protected LogisticaStatoPersistence logisticaStatoPersistence;
	@BeanReference(type = service.intranet.mef.service.LogisticaValutazioneLocalService.class)
	protected service.intranet.mef.service.LogisticaValutazioneLocalService logisticaValutazioneLocalService;
	@BeanReference(type = LogisticaValutazionePersistence.class)
	protected LogisticaValutazionePersistence logisticaValutazionePersistence;
	@BeanReference(type = ModuloTrasportiLocalService.class)
	protected ModuloTrasportiLocalService moduloTrasportiLocalService;
	@BeanReference(type = ModuloTrasportiPersistence.class)
	protected ModuloTrasportiPersistence moduloTrasportiPersistence;
	@BeanReference(type = service.intranet.mef.service.PeriodicitaRichPubblicLocalService.class)
	protected service.intranet.mef.service.PeriodicitaRichPubblicLocalService periodicitaRichPubblicLocalService;
	@BeanReference(type = PeriodicitaRichPubblicPersistence.class)
	protected PeriodicitaRichPubblicPersistence periodicitaRichPubblicPersistence;
	@BeanReference(type = service.intranet.mef.service.RichiestaBeneInvLocalService.class)
	protected service.intranet.mef.service.RichiestaBeneInvLocalService richiestaBeneInvLocalService;
	@BeanReference(type = RichiestaBeneInvPersistence.class)
	protected RichiestaBeneInvPersistence richiestaBeneInvPersistence;
	@BeanReference(type = RichiestaBeneInvFinder.class)
	protected RichiestaBeneInvFinder richiestaBeneInvFinder;
	@BeanReference(type = service.intranet.mef.service.RichiestaInterventiLocalService.class)
	protected service.intranet.mef.service.RichiestaInterventiLocalService richiestaInterventiLocalService;
	@BeanReference(type = RichiestaInterventiPersistence.class)
	protected RichiestaInterventiPersistence richiestaInterventiPersistence;
	@BeanReference(type = service.intranet.mef.service.RichiestaPubblicSitiLocalService.class)
	protected service.intranet.mef.service.RichiestaPubblicSitiLocalService richiestaPubblicSitiLocalService;
	@BeanReference(type = RichiestaPubblicSitiPersistence.class)
	protected RichiestaPubblicSitiPersistence richiestaPubblicSitiPersistence;
	@BeanReference(type = service.intranet.mef.service.RichiesteHWLocalService.class)
	protected service.intranet.mef.service.RichiesteHWLocalService richiesteHWLocalService;
	@BeanReference(type = RichiesteHWPersistence.class)
	protected RichiesteHWPersistence richiesteHWPersistence;
	@BeanReference(type = service.intranet.mef.service.RichiesteUtenzaLocalService.class)
	protected service.intranet.mef.service.RichiesteUtenzaLocalService richiesteUtenzaLocalService;
	@BeanReference(type = RichiesteUtenzaPersistence.class)
	protected RichiesteUtenzaPersistence richiesteUtenzaPersistence;
	@BeanReference(type = service.intranet.mef.service.StatoRichBeneInvLocalService.class)
	protected service.intranet.mef.service.StatoRichBeneInvLocalService statoRichBeneInvLocalService;
	@BeanReference(type = StatoRichBeneInvPersistence.class)
	protected StatoRichBeneInvPersistence statoRichBeneInvPersistence;
	@BeanReference(type = service.intranet.mef.service.TipoBeneInvLocalService.class)
	protected service.intranet.mef.service.TipoBeneInvLocalService tipoBeneInvLocalService;
	@BeanReference(type = TipoBeneInvPersistence.class)
	protected TipoBeneInvPersistence tipoBeneInvPersistence;
	@BeanReference(type = service.intranet.mef.service.TipologiaComputerLocalService.class)
	protected service.intranet.mef.service.TipologiaComputerLocalService tipologiaComputerLocalService;
	@BeanReference(type = TipologiaComputerPersistence.class)
	protected TipologiaComputerPersistence tipologiaComputerPersistence;
	@BeanReference(type = service.intranet.mef.service.TipologiaDispositiviLocalService.class)
	protected service.intranet.mef.service.TipologiaDispositiviLocalService tipologiaDispositiviLocalService;
	@BeanReference(type = TipologiaDispositiviPersistence.class)
	protected TipologiaDispositiviPersistence tipologiaDispositiviPersistence;
	@BeanReference(type = service.intranet.mef.service.TipologiaRichPubblicLocalService.class)
	protected service.intranet.mef.service.TipologiaRichPubblicLocalService tipologiaRichPubblicLocalService;
	@BeanReference(type = TipologiaRichPubblicPersistence.class)
	protected TipologiaRichPubblicPersistence tipologiaRichPubblicPersistence;
	@BeanReference(type = service.intranet.mef.service.TipologiaStampantiLocalService.class)
	protected service.intranet.mef.service.TipologiaStampantiLocalService tipologiaStampantiLocalService;
	@BeanReference(type = TipologiaStampantiPersistence.class)
	protected TipologiaStampantiPersistence tipologiaStampantiPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}