/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.beni.facile.consumo.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RigheRichiestaBFC service. Represents a row in the &quot;MEFBFC_RigheRichiestaBFC&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servizio.beni.facile.consumo.model.impl.RigheRichiestaBFCModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servizio.beni.facile.consumo.model.impl.RigheRichiestaBFCImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RigheRichiestaBFC
 * @see servizio.beni.facile.consumo.model.impl.RigheRichiestaBFCImpl
 * @see servizio.beni.facile.consumo.model.impl.RigheRichiestaBFCModelImpl
 * @generated
 */
@ProviderType
public interface RigheRichiestaBFCModel extends BaseModel<RigheRichiestaBFC> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a righe richiesta b f c model instance should use the {@link RigheRichiestaBFC} interface instead.
	 */

	/**
	 * Returns the primary key of this righe richiesta b f c.
	 *
	 * @return the primary key of this righe richiesta b f c
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this righe richiesta b f c.
	 *
	 * @param primaryKey the primary key of this righe richiesta b f c
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this righe richiesta b f c.
	 *
	 * @return the ID of this righe richiesta b f c
	 */
	public long getId();

	/**
	 * Sets the ID of this righe richiesta b f c.
	 *
	 * @param id the ID of this righe richiesta b f c
	 */
	public void setId(long id);

	/**
	 * Returns the id_richiesta of this righe richiesta b f c.
	 *
	 * @return the id_richiesta of this righe richiesta b f c
	 */
	public long getId_richiesta();

	/**
	 * Sets the id_richiesta of this righe richiesta b f c.
	 *
	 * @param id_richiesta the id_richiesta of this righe richiesta b f c
	 */
	public void setId_richiesta(long id_richiesta);

	/**
	 * Returns the dipartimento of this righe richiesta b f c.
	 *
	 * @return the dipartimento of this righe richiesta b f c
	 */
	@AutoEscape
	public String getDipartimento();

	/**
	 * Sets the dipartimento of this righe richiesta b f c.
	 *
	 * @param dipartimento the dipartimento of this righe richiesta b f c
	 */
	public void setDipartimento(String dipartimento);

	/**
	 * Returns the dati of this righe richiesta b f c.
	 *
	 * @return the dati of this righe richiesta b f c
	 */
	@AutoEscape
	public String getDati();

	/**
	 * Sets the dati of this righe richiesta b f c.
	 *
	 * @param dati the dati of this righe richiesta b f c
	 */
	public void setDati(String dati);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		servizio.beni.facile.consumo.model.RigheRichiestaBFC righeRichiestaBFC);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servizio.beni.facile.consumo.model.RigheRichiestaBFC> toCacheModel();

	@Override
	public servizio.beni.facile.consumo.model.RigheRichiestaBFC toEscapedModel();

	@Override
	public servizio.beni.facile.consumo.model.RigheRichiestaBFC toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}