/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.accenture.istanza.interpello.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.accenture.istanza.interpello.model.RichInterpello;
import com.accenture.istanza.interpello.model.RichInterpelloModel;
import com.accenture.istanza.interpello.model.RichInterpelloSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RichInterpello service. Represents a row in the &quot;MEFINTERPELLO_RichInterpello&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link RichInterpelloModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RichInterpelloImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RichInterpelloImpl
 * @see RichInterpello
 * @see RichInterpelloModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RichInterpelloModelImpl extends BaseModelImpl<RichInterpello>
	implements RichInterpelloModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a rich interpello model instance should use the {@link RichInterpello} interface instead.
	 */
	public static final String TABLE_NAME = "MEFINTERPELLO_RichInterpello";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "id_richiesta", Types.BIGINT },
			{ "cognome", Types.VARCHAR },
			{ "nome", Types.VARCHAR },
			{ "dipartimento", Types.BIGINT },
			{ "direzione", Types.BIGINT },
			{ "ufficio", Types.BIGINT },
			{ "screename", Types.VARCHAR },
			{ "json_richiedente", Types.VARCHAR },
			{ "json_richiesta", Types.VARCHAR },
			{ "bando", Types.VARCHAR },
			{ "data_richiesta", Types.TIMESTAMP },
			{ "allegato", Types.VARCHAR },
			{ "pdf", Types.VARCHAR },
			{ "note", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("id_richiesta", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cognome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dipartimento", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("direzione", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("ufficio", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("screename", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("json_richiedente", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("json_richiesta", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("bando", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("data_richiesta", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("allegato", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("pdf", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("note", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MEFINTERPELLO_RichInterpello (id_ LONG not null primary key,id_richiesta LONG,cognome VARCHAR(75) null,nome VARCHAR(75) null,dipartimento LONG,direzione LONG,ufficio LONG,screename VARCHAR(75) null,json_richiedente VARCHAR(2000) null,json_richiesta VARCHAR(2000) null,bando VARCHAR(75) null,data_richiesta DATE null,allegato VARCHAR(200) null,pdf VARCHAR(200) null,note VARCHAR(1000) null)";
	public static final String TABLE_SQL_DROP = "drop table MEFINTERPELLO_RichInterpello";
	public static final String ORDER_BY_JPQL = " ORDER BY richInterpello.data_richiesta DESC";
	public static final String ORDER_BY_SQL = " ORDER BY MEFINTERPELLO_RichInterpello.data_richiesta DESC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.accenture.istanza.interpello.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.accenture.istanza.interpello.model.RichInterpello"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.accenture.istanza.interpello.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.accenture.istanza.interpello.model.RichInterpello"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.accenture.istanza.interpello.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.accenture.istanza.interpello.model.RichInterpello"),
			true);
	public static final long SCREENAME_COLUMN_BITMASK = 1L;
	public static final long DATA_RICHIESTA_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RichInterpello toModel(RichInterpelloSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RichInterpello model = new RichInterpelloImpl();

		model.setId(soapModel.getId());
		model.setId_richiesta(soapModel.getId_richiesta());
		model.setCognome(soapModel.getCognome());
		model.setNome(soapModel.getNome());
		model.setDipartimento(soapModel.getDipartimento());
		model.setDirezione(soapModel.getDirezione());
		model.setUfficio(soapModel.getUfficio());
		model.setScreename(soapModel.getScreename());
		model.setJson_richiedente(soapModel.getJson_richiedente());
		model.setJson_richiesta(soapModel.getJson_richiesta());
		model.setBando(soapModel.getBando());
		model.setData_richiesta(soapModel.getData_richiesta());
		model.setAllegato(soapModel.getAllegato());
		model.setPdf(soapModel.getPdf());
		model.setNote(soapModel.getNote());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RichInterpello> toModels(RichInterpelloSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<RichInterpello> models = new ArrayList<RichInterpello>(soapModels.length);

		for (RichInterpelloSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.accenture.istanza.interpello.service.util.PropsUtil.get(
				"lock.expiration.time.com.accenture.istanza.interpello.model.RichInterpello"));

	public RichInterpelloModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RichInterpello.class;
	}

	@Override
	public String getModelClassName() {
		return RichInterpello.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("id_richiesta", getId_richiesta());
		attributes.put("cognome", getCognome());
		attributes.put("nome", getNome());
		attributes.put("dipartimento", getDipartimento());
		attributes.put("direzione", getDirezione());
		attributes.put("ufficio", getUfficio());
		attributes.put("screename", getScreename());
		attributes.put("json_richiedente", getJson_richiedente());
		attributes.put("json_richiesta", getJson_richiesta());
		attributes.put("bando", getBando());
		attributes.put("data_richiesta", getData_richiesta());
		attributes.put("allegato", getAllegato());
		attributes.put("pdf", getPdf());
		attributes.put("note", getNote());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		Long id_richiesta = (Long)attributes.get("id_richiesta");

		if (id_richiesta != null) {
			setId_richiesta(id_richiesta);
		}

		String cognome = (String)attributes.get("cognome");

		if (cognome != null) {
			setCognome(cognome);
		}

		String nome = (String)attributes.get("nome");

		if (nome != null) {
			setNome(nome);
		}

		Long dipartimento = (Long)attributes.get("dipartimento");

		if (dipartimento != null) {
			setDipartimento(dipartimento);
		}

		Long direzione = (Long)attributes.get("direzione");

		if (direzione != null) {
			setDirezione(direzione);
		}

		Long ufficio = (Long)attributes.get("ufficio");

		if (ufficio != null) {
			setUfficio(ufficio);
		}

		String screename = (String)attributes.get("screename");

		if (screename != null) {
			setScreename(screename);
		}

		String json_richiedente = (String)attributes.get("json_richiedente");

		if (json_richiedente != null) {
			setJson_richiedente(json_richiedente);
		}

		String json_richiesta = (String)attributes.get("json_richiesta");

		if (json_richiesta != null) {
			setJson_richiesta(json_richiesta);
		}

		String bando = (String)attributes.get("bando");

		if (bando != null) {
			setBando(bando);
		}

		Date data_richiesta = (Date)attributes.get("data_richiesta");

		if (data_richiesta != null) {
			setData_richiesta(data_richiesta);
		}

		String allegato = (String)attributes.get("allegato");

		if (allegato != null) {
			setAllegato(allegato);
		}

		String pdf = (String)attributes.get("pdf");

		if (pdf != null) {
			setPdf(pdf);
		}

		String note = (String)attributes.get("note");

		if (note != null) {
			setNote(note);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public long getId_richiesta() {
		return _id_richiesta;
	}

	@Override
	public void setId_richiesta(long id_richiesta) {
		_id_richiesta = id_richiesta;
	}

	@JSON
	@Override
	public String getCognome() {
		if (_cognome == null) {
			return "";
		}
		else {
			return _cognome;
		}
	}

	@Override
	public void setCognome(String cognome) {
		_cognome = cognome;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return "";
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_nome = nome;
	}

	@JSON
	@Override
	public long getDipartimento() {
		return _dipartimento;
	}

	@Override
	public void setDipartimento(long dipartimento) {
		_dipartimento = dipartimento;
	}

	@JSON
	@Override
	public long getDirezione() {
		return _direzione;
	}

	@Override
	public void setDirezione(long direzione) {
		_direzione = direzione;
	}

	@JSON
	@Override
	public long getUfficio() {
		return _ufficio;
	}

	@Override
	public void setUfficio(long ufficio) {
		_ufficio = ufficio;
	}

	@JSON
	@Override
	public String getScreename() {
		if (_screename == null) {
			return "";
		}
		else {
			return _screename;
		}
	}

	@Override
	public void setScreename(String screename) {
		_columnBitmask |= SCREENAME_COLUMN_BITMASK;

		if (_originalScreename == null) {
			_originalScreename = _screename;
		}

		_screename = screename;
	}

	public String getOriginalScreename() {
		return GetterUtil.getString(_originalScreename);
	}

	@JSON
	@Override
	public String getJson_richiedente() {
		if (_json_richiedente == null) {
			return "";
		}
		else {
			return _json_richiedente;
		}
	}

	@Override
	public void setJson_richiedente(String json_richiedente) {
		_json_richiedente = json_richiedente;
	}

	@JSON
	@Override
	public String getJson_richiesta() {
		if (_json_richiesta == null) {
			return "";
		}
		else {
			return _json_richiesta;
		}
	}

	@Override
	public void setJson_richiesta(String json_richiesta) {
		_json_richiesta = json_richiesta;
	}

	@JSON
	@Override
	public String getBando() {
		if (_bando == null) {
			return "";
		}
		else {
			return _bando;
		}
	}

	@Override
	public void setBando(String bando) {
		_bando = bando;
	}

	@JSON
	@Override
	public Date getData_richiesta() {
		return _data_richiesta;
	}

	@Override
	public void setData_richiesta(Date data_richiesta) {
		_columnBitmask = -1L;

		_data_richiesta = data_richiesta;
	}

	@JSON
	@Override
	public String getAllegato() {
		if (_allegato == null) {
			return "";
		}
		else {
			return _allegato;
		}
	}

	@Override
	public void setAllegato(String allegato) {
		_allegato = allegato;
	}

	@JSON
	@Override
	public String getPdf() {
		if (_pdf == null) {
			return "";
		}
		else {
			return _pdf;
		}
	}

	@Override
	public void setPdf(String pdf) {
		_pdf = pdf;
	}

	@JSON
	@Override
	public String getNote() {
		if (_note == null) {
			return "";
		}
		else {
			return _note;
		}
	}

	@Override
	public void setNote(String note) {
		_note = note;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			RichInterpello.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RichInterpello toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RichInterpello)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RichInterpelloImpl richInterpelloImpl = new RichInterpelloImpl();

		richInterpelloImpl.setId(getId());
		richInterpelloImpl.setId_richiesta(getId_richiesta());
		richInterpelloImpl.setCognome(getCognome());
		richInterpelloImpl.setNome(getNome());
		richInterpelloImpl.setDipartimento(getDipartimento());
		richInterpelloImpl.setDirezione(getDirezione());
		richInterpelloImpl.setUfficio(getUfficio());
		richInterpelloImpl.setScreename(getScreename());
		richInterpelloImpl.setJson_richiedente(getJson_richiedente());
		richInterpelloImpl.setJson_richiesta(getJson_richiesta());
		richInterpelloImpl.setBando(getBando());
		richInterpelloImpl.setData_richiesta(getData_richiesta());
		richInterpelloImpl.setAllegato(getAllegato());
		richInterpelloImpl.setPdf(getPdf());
		richInterpelloImpl.setNote(getNote());

		richInterpelloImpl.resetOriginalValues();

		return richInterpelloImpl;
	}

	@Override
	public int compareTo(RichInterpello richInterpello) {
		int value = 0;

		value = DateUtil.compareTo(getData_richiesta(),
				richInterpello.getData_richiesta());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RichInterpello)) {
			return false;
		}

		RichInterpello richInterpello = (RichInterpello)obj;

		long primaryKey = richInterpello.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		RichInterpelloModelImpl richInterpelloModelImpl = this;

		richInterpelloModelImpl._originalScreename = richInterpelloModelImpl._screename;

		richInterpelloModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<RichInterpello> toCacheModel() {
		RichInterpelloCacheModel richInterpelloCacheModel = new RichInterpelloCacheModel();

		richInterpelloCacheModel.id = getId();

		richInterpelloCacheModel.id_richiesta = getId_richiesta();

		richInterpelloCacheModel.cognome = getCognome();

		String cognome = richInterpelloCacheModel.cognome;

		if ((cognome != null) && (cognome.length() == 0)) {
			richInterpelloCacheModel.cognome = null;
		}

		richInterpelloCacheModel.nome = getNome();

		String nome = richInterpelloCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			richInterpelloCacheModel.nome = null;
		}

		richInterpelloCacheModel.dipartimento = getDipartimento();

		richInterpelloCacheModel.direzione = getDirezione();

		richInterpelloCacheModel.ufficio = getUfficio();

		richInterpelloCacheModel.screename = getScreename();

		String screename = richInterpelloCacheModel.screename;

		if ((screename != null) && (screename.length() == 0)) {
			richInterpelloCacheModel.screename = null;
		}

		richInterpelloCacheModel.json_richiedente = getJson_richiedente();

		String json_richiedente = richInterpelloCacheModel.json_richiedente;

		if ((json_richiedente != null) && (json_richiedente.length() == 0)) {
			richInterpelloCacheModel.json_richiedente = null;
		}

		richInterpelloCacheModel.json_richiesta = getJson_richiesta();

		String json_richiesta = richInterpelloCacheModel.json_richiesta;

		if ((json_richiesta != null) && (json_richiesta.length() == 0)) {
			richInterpelloCacheModel.json_richiesta = null;
		}

		richInterpelloCacheModel.bando = getBando();

		String bando = richInterpelloCacheModel.bando;

		if ((bando != null) && (bando.length() == 0)) {
			richInterpelloCacheModel.bando = null;
		}

		Date data_richiesta = getData_richiesta();

		if (data_richiesta != null) {
			richInterpelloCacheModel.data_richiesta = data_richiesta.getTime();
		}
		else {
			richInterpelloCacheModel.data_richiesta = Long.MIN_VALUE;
		}

		richInterpelloCacheModel.allegato = getAllegato();

		String allegato = richInterpelloCacheModel.allegato;

		if ((allegato != null) && (allegato.length() == 0)) {
			richInterpelloCacheModel.allegato = null;
		}

		richInterpelloCacheModel.pdf = getPdf();

		String pdf = richInterpelloCacheModel.pdf;

		if ((pdf != null) && (pdf.length() == 0)) {
			richInterpelloCacheModel.pdf = null;
		}

		richInterpelloCacheModel.note = getNote();

		String note = richInterpelloCacheModel.note;

		if ((note != null) && (note.length() == 0)) {
			richInterpelloCacheModel.note = null;
		}

		return richInterpelloCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(31);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", id_richiesta=");
		sb.append(getId_richiesta());
		sb.append(", cognome=");
		sb.append(getCognome());
		sb.append(", nome=");
		sb.append(getNome());
		sb.append(", dipartimento=");
		sb.append(getDipartimento());
		sb.append(", direzione=");
		sb.append(getDirezione());
		sb.append(", ufficio=");
		sb.append(getUfficio());
		sb.append(", screename=");
		sb.append(getScreename());
		sb.append(", json_richiedente=");
		sb.append(getJson_richiedente());
		sb.append(", json_richiesta=");
		sb.append(getJson_richiesta());
		sb.append(", bando=");
		sb.append(getBando());
		sb.append(", data_richiesta=");
		sb.append(getData_richiesta());
		sb.append(", allegato=");
		sb.append(getAllegato());
		sb.append(", pdf=");
		sb.append(getPdf());
		sb.append(", note=");
		sb.append(getNote());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(49);

		sb.append("<model><model-name>");
		sb.append("com.accenture.istanza.interpello.model.RichInterpello");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_richiesta</column-name><column-value><![CDATA[");
		sb.append(getId_richiesta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cognome</column-name><column-value><![CDATA[");
		sb.append(getCognome());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nome</column-name><column-value><![CDATA[");
		sb.append(getNome());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dipartimento</column-name><column-value><![CDATA[");
		sb.append(getDipartimento());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>direzione</column-name><column-value><![CDATA[");
		sb.append(getDirezione());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ufficio</column-name><column-value><![CDATA[");
		sb.append(getUfficio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>screename</column-name><column-value><![CDATA[");
		sb.append(getScreename());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>json_richiedente</column-name><column-value><![CDATA[");
		sb.append(getJson_richiedente());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>json_richiesta</column-name><column-value><![CDATA[");
		sb.append(getJson_richiesta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bando</column-name><column-value><![CDATA[");
		sb.append(getBando());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_richiesta</column-name><column-value><![CDATA[");
		sb.append(getData_richiesta());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>allegato</column-name><column-value><![CDATA[");
		sb.append(getAllegato());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>pdf</column-name><column-value><![CDATA[");
		sb.append(getPdf());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>note</column-name><column-value><![CDATA[");
		sb.append(getNote());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = RichInterpello.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			RichInterpello.class, ModelWrapper.class
		};
	private long _id;
	private long _id_richiesta;
	private String _cognome;
	private String _nome;
	private long _dipartimento;
	private long _direzione;
	private long _ufficio;
	private String _screename;
	private String _originalScreename;
	private String _json_richiedente;
	private String _json_richiesta;
	private String _bando;
	private Date _data_richiesta;
	private String _allegato;
	private String _pdf;
	private String _note;
	private long _columnBitmask;
	private RichInterpello _escapedModel;
}