/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mef.richiesta.gest.pos.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the FuoriPorta service. Represents a row in the &quot;BADGE_POS_FuoriPorta&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>mef.richiesta.gest.pos.model.impl.FuoriPortaModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>mef.richiesta.gest.pos.model.impl.FuoriPortaImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see FuoriPorta
 * @generated
 */
@ProviderType
public interface FuoriPortaModel extends BaseModel<FuoriPorta> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a fuori porta model instance should use the {@link FuoriPorta} interface instead.
	 */

	/**
	 * Returns the primary key of this fuori porta.
	 *
	 * @return the primary key of this fuori porta
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this fuori porta.
	 *
	 * @param primaryKey the primary key of this fuori porta
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_pk_fuori porta of this fuori porta.
	 *
	 * @return the id_pk_fuori porta of this fuori porta
	 */
	public long getId_pk_fuoriPorta();

	/**
	 * Sets the id_pk_fuori porta of this fuori porta.
	 *
	 * @param id_pk_fuoriPorta the id_pk_fuori porta of this fuori porta
	 */
	public void setId_pk_fuoriPorta(long id_pk_fuoriPorta);

	/**
	 * Returns the id_fuori porta of this fuori porta.
	 *
	 * @return the id_fuori porta of this fuori porta
	 */
	public long getId_fuoriPorta();

	/**
	 * Sets the id_fuori porta of this fuori porta.
	 *
	 * @param id_fuoriPorta the id_fuori porta of this fuori porta
	 */
	public void setId_fuoriPorta(long id_fuoriPorta);

	/**
	 * Returns the id_corridoio of this fuori porta.
	 *
	 * @return the id_corridoio of this fuori porta
	 */
	public long getId_corridoio();

	/**
	 * Sets the id_corridoio of this fuori porta.
	 *
	 * @param id_corridoio the id_corridoio of this fuori porta
	 */
	public void setId_corridoio(long id_corridoio);

	/**
	 * Returns the cod_fuori porta of this fuori porta.
	 *
	 * @return the cod_fuori porta of this fuori porta
	 */
	@AutoEscape
	public String getCod_fuoriPorta();

	/**
	 * Sets the cod_fuori porta of this fuori porta.
	 *
	 * @param cod_fuoriPorta the cod_fuori porta of this fuori porta
	 */
	public void setCod_fuoriPorta(String cod_fuoriPorta);

	/**
	 * Returns the desc of this fuori porta.
	 *
	 * @return the desc of this fuori porta
	 */
	@AutoEscape
	public String getDesc();

	/**
	 * Sets the desc of this fuori porta.
	 *
	 * @param desc the desc of this fuori porta
	 */
	public void setDesc(String desc);

	/**
	 * Returns the data_ins of this fuori porta.
	 *
	 * @return the data_ins of this fuori porta
	 */
	@AutoEscape
	public String getData_ins();

	/**
	 * Sets the data_ins of this fuori porta.
	 *
	 * @param data_ins the data_ins of this fuori porta
	 */
	public void setData_ins(String data_ins);

	/**
	 * Returns the data_agg of this fuori porta.
	 *
	 * @return the data_agg of this fuori porta
	 */
	@AutoEscape
	public String getData_agg();

	/**
	 * Sets the data_agg of this fuori porta.
	 *
	 * @param data_agg the data_agg of this fuori porta
	 */
	public void setData_agg(String data_agg);

	/**
	 * Returns the user_ins of this fuori porta.
	 *
	 * @return the user_ins of this fuori porta
	 */
	@AutoEscape
	public String getUser_ins();

	/**
	 * Sets the user_ins of this fuori porta.
	 *
	 * @param user_ins the user_ins of this fuori porta
	 */
	public void setUser_ins(String user_ins);

	/**
	 * Returns the user_agg of this fuori porta.
	 *
	 * @return the user_agg of this fuori porta
	 */
	@AutoEscape
	public String getUser_agg();

	/**
	 * Sets the user_agg of this fuori porta.
	 *
	 * @param user_agg the user_agg of this fuori porta
	 */
	public void setUser_agg(String user_agg);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(mef.richiesta.gest.pos.model.FuoriPorta fuoriPorta);

	@Override
	public int hashCode();

	@Override
	public CacheModel<mef.richiesta.gest.pos.model.FuoriPorta> toCacheModel();

	@Override
	public mef.richiesta.gest.pos.model.FuoriPorta toEscapedModel();

	@Override
	public mef.richiesta.gest.pos.model.FuoriPorta toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}