/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mef.richiesta.gest.pos.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Sede service. Represents a row in the &quot;BADGE_POS_Sede&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>mef.richiesta.gest.pos.model.impl.SedeModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>mef.richiesta.gest.pos.model.impl.SedeImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Sede
 * @generated
 */
@ProviderType
public interface SedeModel extends BaseModel<Sede> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sede model instance should use the {@link Sede} interface instead.
	 */

	/**
	 * Returns the primary key of this sede.
	 *
	 * @return the primary key of this sede
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sede.
	 *
	 * @param primaryKey the primary key of this sede
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_pk_sede of this sede.
	 *
	 * @return the id_pk_sede of this sede
	 */
	public long getId_pk_sede();

	/**
	 * Sets the id_pk_sede of this sede.
	 *
	 * @param id_pk_sede the id_pk_sede of this sede
	 */
	public void setId_pk_sede(long id_pk_sede);

	/**
	 * Returns the id_sede of this sede.
	 *
	 * @return the id_sede of this sede
	 */
	public long getId_sede();

	/**
	 * Sets the id_sede of this sede.
	 *
	 * @param id_sede the id_sede of this sede
	 */
	public void setId_sede(long id_sede);

	/**
	 * Returns the cod_sede of this sede.
	 *
	 * @return the cod_sede of this sede
	 */
	@AutoEscape
	public String getCod_sede();

	/**
	 * Sets the cod_sede of this sede.
	 *
	 * @param cod_sede the cod_sede of this sede
	 */
	public void setCod_sede(String cod_sede);

	/**
	 * Returns the desc of this sede.
	 *
	 * @return the desc of this sede
	 */
	@AutoEscape
	public String getDesc();

	/**
	 * Sets the desc of this sede.
	 *
	 * @param desc the desc of this sede
	 */
	public void setDesc(String desc);

	/**
	 * Returns the data_ins of this sede.
	 *
	 * @return the data_ins of this sede
	 */
	@AutoEscape
	public String getData_ins();

	/**
	 * Sets the data_ins of this sede.
	 *
	 * @param data_ins the data_ins of this sede
	 */
	public void setData_ins(String data_ins);

	/**
	 * Returns the data_agg of this sede.
	 *
	 * @return the data_agg of this sede
	 */
	@AutoEscape
	public String getData_agg();

	/**
	 * Sets the data_agg of this sede.
	 *
	 * @param data_agg the data_agg of this sede
	 */
	public void setData_agg(String data_agg);

	/**
	 * Returns the user_ins of this sede.
	 *
	 * @return the user_ins of this sede
	 */
	@AutoEscape
	public String getUser_ins();

	/**
	 * Sets the user_ins of this sede.
	 *
	 * @param user_ins the user_ins of this sede
	 */
	public void setUser_ins(String user_ins);

	/**
	 * Returns the user_agg of this sede.
	 *
	 * @return the user_agg of this sede
	 */
	@AutoEscape
	public String getUser_agg();

	/**
	 * Sets the user_agg of this sede.
	 *
	 * @param user_agg the user_agg of this sede
	 */
	public void setUser_agg(String user_agg);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(mef.richiesta.gest.pos.model.Sede sede);

	@Override
	public int hashCode();

	@Override
	public CacheModel<mef.richiesta.gest.pos.model.Sede> toCacheModel();

	@Override
	public mef.richiesta.gest.pos.model.Sede toEscapedModel();

	@Override
	public mef.richiesta.gest.pos.model.Sede toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}