/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.richiesta.trasporti.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Mobilita service. Represents a row in the &quot;LF_MOBILITA&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servizio.richiesta.trasporti.model.impl.MobilitaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servizio.richiesta.trasporti.model.impl.MobilitaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Mobilita
 * @see servizio.richiesta.trasporti.model.impl.MobilitaImpl
 * @see servizio.richiesta.trasporti.model.impl.MobilitaModelImpl
 * @generated
 */
@ProviderType
public interface MobilitaModel extends BaseModel<Mobilita> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a mobilita model instance should use the {@link Mobilita} interface instead.
	 */

	/**
	 * Returns the primary key of this mobilita.
	 *
	 * @return the primary key of this mobilita
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this mobilita.
	 *
	 * @param primaryKey the primary key of this mobilita
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the custom_key of this mobilita.
	 *
	 * @return the custom_key of this mobilita
	 */
	@AutoEscape
	public String getCustom_key();

	/**
	 * Sets the custom_key of this mobilita.
	 *
	 * @param custom_key the custom_key of this mobilita
	 */
	public void setCustom_key(String custom_key);

	/**
	 * Returns the person_id of this mobilita.
	 *
	 * @return the person_id of this mobilita
	 */
	public long getPerson_id();

	/**
	 * Sets the person_id of this mobilita.
	 *
	 * @param person_id the person_id of this mobilita
	 */
	public void setPerson_id(long person_id);

	/**
	 * Returns the tipo_mobilita of this mobilita.
	 *
	 * @return the tipo_mobilita of this mobilita
	 */
	@AutoEscape
	public String getTipo_mobilita();

	/**
	 * Sets the tipo_mobilita of this mobilita.
	 *
	 * @param tipo_mobilita the tipo_mobilita of this mobilita
	 */
	public void setTipo_mobilita(String tipo_mobilita);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(servizio.richiesta.trasporti.model.Mobilita mobilita);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servizio.richiesta.trasporti.model.Mobilita> toCacheModel();

	@Override
	public servizio.richiesta.trasporti.model.Mobilita toEscapedModel();

	@Override
	public servizio.richiesta.trasporti.model.Mobilita toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}