/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.assistance.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.intranet.mef.assistance.model.Ambito;
import com.intranet.mef.assistance.service.AmbitoLocalServiceUtil;

/**
 * The extended model base implementation for the Ambito service. Represents a row in the &quot;Assistance_Ambito&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AmbitoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AmbitoImpl
 * @see Ambito
 * @generated
 */
@ProviderType
public abstract class AmbitoBaseImpl extends AmbitoModelImpl implements Ambito {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a ambito model instance should use the {@link Ambito} interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			AmbitoLocalServiceUtil.addAmbito(this);
		}
		else {
			AmbitoLocalServiceUtil.updateAmbito(this);
		}
	}
}