/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.assistance.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.intranet.mef.assistance.model.Area;
import com.intranet.mef.assistance.model.AreaModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the Area service. Represents a row in the &quot;Assistance_Area&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link AreaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AreaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AreaImpl
 * @see Area
 * @see AreaModel
 * @generated
 */
@ProviderType
public class AreaModelImpl extends BaseModelImpl<Area> implements AreaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a area model instance should use the {@link Area} interface instead.
	 */
	public static final String TABLE_NAME = "Assistance_Area";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "areaId", Types.VARCHAR },
			{ "areaName", Types.VARCHAR },
			{ "assServiceId", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("areaId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("areaName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("assServiceId", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table Assistance_Area (uuid_ VARCHAR(75) null,areaId VARCHAR(75) not null primary key,areaName VARCHAR(200) null,assServiceId VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table Assistance_Area";
	public static final String ORDER_BY_JPQL = " ORDER BY area.areaId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY Assistance_Area.areaId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.intranet.mef.assistance.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.com.intranet.mef.assistance.model.Area"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.intranet.mef.assistance.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.com.intranet.mef.assistance.model.Area"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.intranet.mef.assistance.service.util.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.intranet.mef.assistance.model.Area"),
			true);
	public static final long ASSSERVICEID_COLUMN_BITMASK = 1L;
	public static final long UUID_COLUMN_BITMASK = 2L;
	public static final long AREAID_COLUMN_BITMASK = 4L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.intranet.mef.assistance.service.util.ServiceProps.get(
				"lock.expiration.time.com.intranet.mef.assistance.model.Area"));

	public AreaModelImpl() {
	}

	@Override
	public String getPrimaryKey() {
		return _areaId;
	}

	@Override
	public void setPrimaryKey(String primaryKey) {
		setAreaId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _areaId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((String)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return Area.class;
	}

	@Override
	public String getModelClassName() {
		return Area.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("areaId", getAreaId());
		attributes.put("areaName", getAreaName());
		attributes.put("assServiceId", getAssServiceId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		String areaId = (String)attributes.get("areaId");

		if (areaId != null) {
			setAreaId(areaId);
		}

		String areaName = (String)attributes.get("areaName");

		if (areaName != null) {
			setAreaName(areaName);
		}

		String assServiceId = (String)attributes.get("assServiceId");

		if (assServiceId != null) {
			setAssServiceId(assServiceId);
		}
	}

	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@Override
	public String getAreaId() {
		if (_areaId == null) {
			return StringPool.BLANK;
		}
		else {
			return _areaId;
		}
	}

	@Override
	public void setAreaId(String areaId) {
		_columnBitmask = -1L;

		_areaId = areaId;
	}

	@Override
	public String getAreaName() {
		if (_areaName == null) {
			return StringPool.BLANK;
		}
		else {
			return _areaName;
		}
	}

	@Override
	public void setAreaName(String areaName) {
		_areaName = areaName;
	}

	@Override
	public String getAssServiceId() {
		if (_assServiceId == null) {
			return StringPool.BLANK;
		}
		else {
			return _assServiceId;
		}
	}

	@Override
	public void setAssServiceId(String assServiceId) {
		_columnBitmask |= ASSSERVICEID_COLUMN_BITMASK;

		if (_originalAssServiceId == null) {
			_originalAssServiceId = _assServiceId;
		}

		_assServiceId = assServiceId;
	}

	public String getOriginalAssServiceId() {
		return GetterUtil.getString(_originalAssServiceId);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public Area toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Area)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AreaImpl areaImpl = new AreaImpl();

		areaImpl.setUuid(getUuid());
		areaImpl.setAreaId(getAreaId());
		areaImpl.setAreaName(getAreaName());
		areaImpl.setAssServiceId(getAssServiceId());

		areaImpl.resetOriginalValues();

		return areaImpl;
	}

	@Override
	public int compareTo(Area area) {
		int value = 0;

		value = getAreaId().compareTo(area.getAreaId());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Area)) {
			return false;
		}

		Area area = (Area)obj;

		String primaryKey = area.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		AreaModelImpl areaModelImpl = this;

		areaModelImpl._originalUuid = areaModelImpl._uuid;

		areaModelImpl._originalAssServiceId = areaModelImpl._assServiceId;

		areaModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Area> toCacheModel() {
		AreaCacheModel areaCacheModel = new AreaCacheModel();

		areaCacheModel.uuid = getUuid();

		String uuid = areaCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			areaCacheModel.uuid = null;
		}

		areaCacheModel.areaId = getAreaId();

		String areaId = areaCacheModel.areaId;

		if ((areaId != null) && (areaId.length() == 0)) {
			areaCacheModel.areaId = null;
		}

		areaCacheModel.areaName = getAreaName();

		String areaName = areaCacheModel.areaName;

		if ((areaName != null) && (areaName.length() == 0)) {
			areaCacheModel.areaName = null;
		}

		areaCacheModel.assServiceId = getAssServiceId();

		String assServiceId = areaCacheModel.assServiceId;

		if ((assServiceId != null) && (assServiceId.length() == 0)) {
			areaCacheModel.assServiceId = null;
		}

		return areaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", areaId=");
		sb.append(getAreaId());
		sb.append(", areaName=");
		sb.append(getAreaName());
		sb.append(", assServiceId=");
		sb.append(getAssServiceId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("com.intranet.mef.assistance.model.Area");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>areaId</column-name><column-value><![CDATA[");
		sb.append(getAreaId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>areaName</column-name><column-value><![CDATA[");
		sb.append(getAreaName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>assServiceId</column-name><column-value><![CDATA[");
		sb.append(getAssServiceId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Area.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Area.class
		};
	private String _uuid;
	private String _originalUuid;
	private String _areaId;
	private String _areaName;
	private String _assServiceId;
	private String _originalAssServiceId;
	private long _columnBitmask;
	private Area _escapedModel;
}