create table LOCBFC_LocalRich (
	idStatoAttuale LONG,
	id_ LONG not null primary key,
	id_richiesta LONG,
	dataRichiesta DATE null,
	idPeriodicita LONG,
	email VARCHAR(100) null,
	rifStanza VARCHAR(50) null,
	ispettorato VARCHAR(100) null,
	noteRich STRING null,
	ufficio VARCHAR(100) null,
	note STRING null,
	uidIns LONG,
	dataIns DATE null,
	uidUpd LONG,
	dataUpd DATE null,
	oggetto VARCHAR(100) null,
	idSede VARCHAR(50) null,
	strutIsp VARCHAR(10) null,
	strutUff VARCHAR(10) null,
	strutIsp2 VARCHAR(10) null,
	telRich VARCHAR(20) null,
	costoReale DOUBLE,
	preventivo INTEGER,
	flagInvio INTEGER,
	inStage BOOLEAN
);

create table LOCBFC_LocalRichInfo (
	idStatoAttuale LONG,
	id_ LONG not null primary key,
	id_richiesta LONG,
	dataRichiesta DATE null,
	email VARCHAR(100) null,
	rifStanza VARCHAR(50) null,
	ispettorato VARCHAR(100) null,
	nomeRef VARCHAR(100) null,
	telRef VARCHAR(100) null,
	nMacchina VARCHAR(100) null,
	noteRich STRING null,
	ufficio VARCHAR(100) null,
	note STRING null,
	uidIns LONG,
	dataIns DATE null,
	uidUpd LONG,
	dataUpd DATE null,
	oggetto VARCHAR(100) null,
	idSede VARCHAR(50) null,
	telRich VARCHAR(20) null,
	strutUff VARCHAR(10) null,
	strutIsp VARCHAR(10) null,
	costoReale DOUBLE,
	preventivo INTEGER,
	flagInvio INTEGER,
	inStage BOOLEAN
);