/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.prenotazione.aule.mef.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import servizio.prenotazione.aule.mef.model.StatoAula;
import servizio.prenotazione.aule.mef.model.StatoAulaModel;
import servizio.prenotazione.aule.mef.model.StatoAulaSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the StatoAula service. Represents a row in the &quot;MEFAULE_StatoAula&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link StatoAulaModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatoAulaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StatoAulaImpl
 * @see StatoAula
 * @see StatoAulaModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class StatoAulaModelImpl extends BaseModelImpl<StatoAula>
	implements StatoAulaModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a stato aula model instance should use the {@link StatoAula} interface instead.
	 */
	public static final String TABLE_NAME = "MEFAULE_StatoAula";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_stato_aula", Types.BIGINT },
			{ "desc_stato", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_stato_aula", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("desc_stato", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MEFAULE_StatoAula (id_stato_aula LONG not null primary key,desc_stato VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table MEFAULE_StatoAula";
	public static final String ORDER_BY_JPQL = " ORDER BY statoAula.id_stato_aula ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MEFAULE_StatoAula.id_stato_aula ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(servizio.prenotazione.aule.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.servizio.prenotazione.aule.mef.model.StatoAula"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(servizio.prenotazione.aule.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.servizio.prenotazione.aule.mef.model.StatoAula"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static StatoAula toModel(StatoAulaSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		StatoAula model = new StatoAulaImpl();

		model.setId_stato_aula(soapModel.getId_stato_aula());
		model.setDesc_stato(soapModel.getDesc_stato());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<StatoAula> toModels(StatoAulaSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<StatoAula> models = new ArrayList<StatoAula>(soapModels.length);

		for (StatoAulaSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(servizio.prenotazione.aule.mef.service.util.PropsUtil.get(
				"lock.expiration.time.servizio.prenotazione.aule.mef.model.StatoAula"));

	public StatoAulaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_stato_aula;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_stato_aula(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_stato_aula;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StatoAula.class;
	}

	@Override
	public String getModelClassName() {
		return StatoAula.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_stato_aula", getId_stato_aula());
		attributes.put("desc_stato", getDesc_stato());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_stato_aula = (Long)attributes.get("id_stato_aula");

		if (id_stato_aula != null) {
			setId_stato_aula(id_stato_aula);
		}

		String desc_stato = (String)attributes.get("desc_stato");

		if (desc_stato != null) {
			setDesc_stato(desc_stato);
		}
	}

	@JSON
	@Override
	public long getId_stato_aula() {
		return _id_stato_aula;
	}

	@Override
	public void setId_stato_aula(long id_stato_aula) {
		_id_stato_aula = id_stato_aula;
	}

	@JSON
	@Override
	public String getDesc_stato() {
		if (_desc_stato == null) {
			return StringPool.BLANK;
		}
		else {
			return _desc_stato;
		}
	}

	@Override
	public void setDesc_stato(String desc_stato) {
		_desc_stato = desc_stato;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			StatoAula.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StatoAula toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StatoAula)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StatoAulaImpl statoAulaImpl = new StatoAulaImpl();

		statoAulaImpl.setId_stato_aula(getId_stato_aula());
		statoAulaImpl.setDesc_stato(getDesc_stato());

		statoAulaImpl.resetOriginalValues();

		return statoAulaImpl;
	}

	@Override
	public int compareTo(StatoAula statoAula) {
		long primaryKey = statoAula.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StatoAula)) {
			return false;
		}

		StatoAula statoAula = (StatoAula)obj;

		long primaryKey = statoAula.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<StatoAula> toCacheModel() {
		StatoAulaCacheModel statoAulaCacheModel = new StatoAulaCacheModel();

		statoAulaCacheModel.id_stato_aula = getId_stato_aula();

		statoAulaCacheModel.desc_stato = getDesc_stato();

		String desc_stato = statoAulaCacheModel.desc_stato;

		if ((desc_stato != null) && (desc_stato.length() == 0)) {
			statoAulaCacheModel.desc_stato = null;
		}

		return statoAulaCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id_stato_aula=");
		sb.append(getId_stato_aula());
		sb.append(", desc_stato=");
		sb.append(getDesc_stato());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("servizio.prenotazione.aule.mef.model.StatoAula");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_stato_aula</column-name><column-value><![CDATA[");
		sb.append(getId_stato_aula());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>desc_stato</column-name><column-value><![CDATA[");
		sb.append(getDesc_stato());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = StatoAula.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			StatoAula.class
		};
	private long _id_stato_aula;
	private String _desc_stato;
	private StatoAula _escapedModel;
}