/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mef.email.configurator.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AppNames service. Represents a row in the &quot;MEFEMAILC_AppNames&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link mef.email.configurator.model.impl.AppNamesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link mef.email.configurator.model.impl.AppNamesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AppNames
 * @see mef.email.configurator.model.impl.AppNamesImpl
 * @see mef.email.configurator.model.impl.AppNamesModelImpl
 * @generated
 */
@ProviderType
public interface AppNamesModel extends BaseModel<AppNames> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a app names model instance should use the {@link AppNames} interface instead.
	 */

	/**
	 * Returns the primary key of this app names.
	 *
	 * @return the primary key of this app names
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this app names.
	 *
	 * @param primaryKey the primary key of this app names
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this app names.
	 *
	 * @return the ID of this app names
	 */
	public long getId();

	/**
	 * Sets the ID of this app names.
	 *
	 * @param id the ID of this app names
	 */
	public void setId(long id);

	/**
	 * Returns the appname of this app names.
	 *
	 * @return the appname of this app names
	 */
	@AutoEscape
	public String getAppname();

	/**
	 * Sets the appname of this app names.
	 *
	 * @param appname the appname of this app names
	 */
	public void setAppname(String appname);

	/**
	 * Returns the appid of this app names.
	 *
	 * @return the appid of this app names
	 */
	public long getAppid();

	/**
	 * Sets the appid of this app names.
	 *
	 * @param appid the appid of this app names
	 */
	public void setAppid(long appid);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(mef.email.configurator.model.AppNames appNames);

	@Override
	public int hashCode();

	@Override
	public CacheModel<mef.email.configurator.model.AppNames> toCacheModel();

	@Override
	public mef.email.configurator.model.AppNames toEscapedModel();

	@Override
	public mef.email.configurator.model.AppNames toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}