/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mef.email.configurator.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the EmailApp service. Represents a row in the &quot;MEFEMAILC_EmailApp&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link mef.email.configurator.model.impl.EmailAppModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link mef.email.configurator.model.impl.EmailAppImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see EmailApp
 * @see mef.email.configurator.model.impl.EmailAppImpl
 * @see mef.email.configurator.model.impl.EmailAppModelImpl
 * @generated
 */
@ProviderType
public interface EmailAppModel extends BaseModel<EmailApp> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a email app model instance should use the {@link EmailApp} interface instead.
	 */

	/**
	 * Returns the primary key of this email app.
	 *
	 * @return the primary key of this email app
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this email app.
	 *
	 * @param primaryKey the primary key of this email app
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this email app.
	 *
	 * @return the ID of this email app
	 */
	public long getId();

	/**
	 * Sets the ID of this email app.
	 *
	 * @param id the ID of this email app
	 */
	public void setId(long id);

	/**
	 * Returns the appid of this email app.
	 *
	 * @return the appid of this email app
	 */
	public long getAppid();

	/**
	 * Sets the appid of this email app.
	 *
	 * @param appid the appid of this email app
	 */
	public void setAppid(long appid);

	/**
	 * Returns the struttura of this email app.
	 *
	 * @return the struttura of this email app
	 */
	public long getStruttura();

	/**
	 * Sets the struttura of this email app.
	 *
	 * @param struttura the struttura of this email app
	 */
	public void setStruttura(long struttura);

	/**
	 * Returns the email of this email app.
	 *
	 * @return the email of this email app
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this email app.
	 *
	 * @param email the email of this email app
	 */
	public void setEmail(String email);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(mef.email.configurator.model.EmailApp emailApp);

	@Override
	public int hashCode();

	@Override
	public CacheModel<mef.email.configurator.model.EmailApp> toCacheModel();

	@Override
	public mef.email.configurator.model.EmailApp toEscapedModel();

	@Override
	public mef.email.configurator.model.EmailApp toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}