/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import service.intranet.mef.model.BeneInv;
import service.intranet.mef.model.BeneInvModel;
import service.intranet.mef.model.BeneInvSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BeneInv service. Represents a row in the &quot;MFORM_BeneInv&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link BeneInvModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BeneInvImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BeneInvImpl
 * @see BeneInv
 * @see BeneInvModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class BeneInvModelImpl extends BaseModelImpl<BeneInv>
	implements BeneInvModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bene inv model instance should use the {@link BeneInv} interface instead.
	 */
	public static final String TABLE_NAME = "MFORM_BeneInv";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "bene", Types.VARCHAR },
			{ "id_tipo", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("bene", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("id_tipo", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table MFORM_BeneInv (id_ LONG not null primary key,bene VARCHAR(75) null,id_tipo LONG)";
	public static final String TABLE_SQL_DROP = "drop table MFORM_BeneInv";
	public static final String ORDER_BY_JPQL = " ORDER BY beneInv.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MFORM_BeneInv.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.service.intranet.mef.model.BeneInv"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.service.intranet.mef.model.BeneInv"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.service.intranet.mef.model.BeneInv"),
			true);
	public static final long ID_TIPO_COLUMN_BITMASK = 1L;
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BeneInv toModel(BeneInvSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BeneInv model = new BeneInvImpl();

		model.setId(soapModel.getId());
		model.setBene(soapModel.getBene());
		model.setId_tipo(soapModel.getId_tipo());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BeneInv> toModels(BeneInvSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BeneInv> models = new ArrayList<BeneInv>(soapModels.length);

		for (BeneInvSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(service.intranet.mef.service.util.PropsUtil.get(
				"lock.expiration.time.service.intranet.mef.model.BeneInv"));

	public BeneInvModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BeneInv.class;
	}

	@Override
	public String getModelClassName() {
		return BeneInv.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("bene", getBene());
		attributes.put("id_tipo", getId_tipo());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String bene = (String)attributes.get("bene");

		if (bene != null) {
			setBene(bene);
		}

		Long id_tipo = (Long)attributes.get("id_tipo");

		if (id_tipo != null) {
			setId_tipo(id_tipo);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getBene() {
		if (_bene == null) {
			return StringPool.BLANK;
		}
		else {
			return _bene;
		}
	}

	@Override
	public void setBene(String bene) {
		_bene = bene;
	}

	@JSON
	@Override
	public long getId_tipo() {
		return _id_tipo;
	}

	@Override
	public void setId_tipo(long id_tipo) {
		_columnBitmask |= ID_TIPO_COLUMN_BITMASK;

		if (!_setOriginalId_tipo) {
			_setOriginalId_tipo = true;

			_originalId_tipo = _id_tipo;
		}

		_id_tipo = id_tipo;
	}

	public long getOriginalId_tipo() {
		return _originalId_tipo;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			BeneInv.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BeneInv toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BeneInv)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BeneInvImpl beneInvImpl = new BeneInvImpl();

		beneInvImpl.setId(getId());
		beneInvImpl.setBene(getBene());
		beneInvImpl.setId_tipo(getId_tipo());

		beneInvImpl.resetOriginalValues();

		return beneInvImpl;
	}

	@Override
	public int compareTo(BeneInv beneInv) {
		long primaryKey = beneInv.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BeneInv)) {
			return false;
		}

		BeneInv beneInv = (BeneInv)obj;

		long primaryKey = beneInv.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		BeneInvModelImpl beneInvModelImpl = this;

		beneInvModelImpl._originalId_tipo = beneInvModelImpl._id_tipo;

		beneInvModelImpl._setOriginalId_tipo = false;

		beneInvModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BeneInv> toCacheModel() {
		BeneInvCacheModel beneInvCacheModel = new BeneInvCacheModel();

		beneInvCacheModel.id = getId();

		beneInvCacheModel.bene = getBene();

		String bene = beneInvCacheModel.bene;

		if ((bene != null) && (bene.length() == 0)) {
			beneInvCacheModel.bene = null;
		}

		beneInvCacheModel.id_tipo = getId_tipo();

		return beneInvCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", bene=");
		sb.append(getBene());
		sb.append(", id_tipo=");
		sb.append(getId_tipo());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("service.intranet.mef.model.BeneInv");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>bene</column-name><column-value><![CDATA[");
		sb.append(getBene());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_tipo</column-name><column-value><![CDATA[");
		sb.append(getId_tipo());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = BeneInv.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			BeneInv.class
		};
	private long _id;
	private String _bene;
	private long _id_tipo;
	private long _originalId_tipo;
	private boolean _setOriginalId_tipo;
	private long _columnBitmask;
	private BeneInv _escapedModel;
}