/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import service.intranet.mef.model.BeneInvRichiesto;
import service.intranet.mef.model.BeneInvRichiestoModel;
import service.intranet.mef.model.BeneInvRichiestoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the BeneInvRichiesto service. Represents a row in the &quot;MFORM_BeneInvRichiesto&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link BeneInvRichiestoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link BeneInvRichiestoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see BeneInvRichiestoImpl
 * @see BeneInvRichiesto
 * @see BeneInvRichiestoModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class BeneInvRichiestoModelImpl extends BaseModelImpl<BeneInvRichiesto>
	implements BeneInvRichiestoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a bene inv richiesto model instance should use the {@link BeneInvRichiesto} interface instead.
	 */
	public static final String TABLE_NAME = "MFORM_BeneInvRichiesto";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_bene_rich", Types.BIGINT },
			{ "tipologia", Types.VARCHAR },
			{ "descrizione", Types.VARCHAR },
			{ "quantita", Types.INTEGER },
			{ "dettagli", Types.VARCHAR },
			{ "in_elenco", Types.BOOLEAN },
			{ "id_richiesta", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_bene_rich", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("tipologia", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("quantita", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("dettagli", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("in_elenco", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("id_richiesta", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table MFORM_BeneInvRichiesto (id_bene_rich LONG not null primary key,tipologia VARCHAR(75) null,descrizione VARCHAR(75) null,quantita INTEGER,dettagli VARCHAR(75) null,in_elenco BOOLEAN,id_richiesta LONG)";
	public static final String TABLE_SQL_DROP = "drop table MFORM_BeneInvRichiesto";
	public static final String ORDER_BY_JPQL = " ORDER BY beneInvRichiesto.id_bene_rich ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MFORM_BeneInvRichiesto.id_bene_rich ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.service.intranet.mef.model.BeneInvRichiesto"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.service.intranet.mef.model.BeneInvRichiesto"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.service.intranet.mef.model.BeneInvRichiesto"),
			true);
	public static final long ID_RICHIESTA_COLUMN_BITMASK = 1L;
	public static final long IN_ELENCO_COLUMN_BITMASK = 2L;
	public static final long ID_BENE_RICH_COLUMN_BITMASK = 4L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static BeneInvRichiesto toModel(BeneInvRichiestoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		BeneInvRichiesto model = new BeneInvRichiestoImpl();

		model.setId_bene_rich(soapModel.getId_bene_rich());
		model.setTipologia(soapModel.getTipologia());
		model.setDescrizione(soapModel.getDescrizione());
		model.setQuantita(soapModel.getQuantita());
		model.setDettagli(soapModel.getDettagli());
		model.setIn_elenco(soapModel.getIn_elenco());
		model.setId_richiesta(soapModel.getId_richiesta());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<BeneInvRichiesto> toModels(
		BeneInvRichiestoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<BeneInvRichiesto> models = new ArrayList<BeneInvRichiesto>(soapModels.length);

		for (BeneInvRichiestoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(service.intranet.mef.service.util.PropsUtil.get(
				"lock.expiration.time.service.intranet.mef.model.BeneInvRichiesto"));

	public BeneInvRichiestoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_bene_rich;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_bene_rich(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_bene_rich;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return BeneInvRichiesto.class;
	}

	@Override
	public String getModelClassName() {
		return BeneInvRichiesto.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_bene_rich", getId_bene_rich());
		attributes.put("tipologia", getTipologia());
		attributes.put("descrizione", getDescrizione());
		attributes.put("quantita", getQuantita());
		attributes.put("dettagli", getDettagli());
		attributes.put("in_elenco", getIn_elenco());
		attributes.put("id_richiesta", getId_richiesta());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_bene_rich = (Long)attributes.get("id_bene_rich");

		if (id_bene_rich != null) {
			setId_bene_rich(id_bene_rich);
		}

		String tipologia = (String)attributes.get("tipologia");

		if (tipologia != null) {
			setTipologia(tipologia);
		}

		String descrizione = (String)attributes.get("descrizione");

		if (descrizione != null) {
			setDescrizione(descrizione);
		}

		Integer quantita = (Integer)attributes.get("quantita");

		if (quantita != null) {
			setQuantita(quantita);
		}

		String dettagli = (String)attributes.get("dettagli");

		if (dettagli != null) {
			setDettagli(dettagli);
		}

		Boolean in_elenco = (Boolean)attributes.get("in_elenco");

		if (in_elenco != null) {
			setIn_elenco(in_elenco);
		}

		Long id_richiesta = (Long)attributes.get("id_richiesta");

		if (id_richiesta != null) {
			setId_richiesta(id_richiesta);
		}
	}

	@JSON
	@Override
	public long getId_bene_rich() {
		return _id_bene_rich;
	}

	@Override
	public void setId_bene_rich(long id_bene_rich) {
		_id_bene_rich = id_bene_rich;
	}

	@JSON
	@Override
	public String getTipologia() {
		if (_tipologia == null) {
			return StringPool.BLANK;
		}
		else {
			return _tipologia;
		}
	}

	@Override
	public void setTipologia(String tipologia) {
		_tipologia = tipologia;
	}

	@JSON
	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		_descrizione = descrizione;
	}

	@JSON
	@Override
	public int getQuantita() {
		return _quantita;
	}

	@Override
	public void setQuantita(int quantita) {
		_quantita = quantita;
	}

	@JSON
	@Override
	public String getDettagli() {
		if (_dettagli == null) {
			return StringPool.BLANK;
		}
		else {
			return _dettagli;
		}
	}

	@Override
	public void setDettagli(String dettagli) {
		_dettagli = dettagli;
	}

	@JSON
	@Override
	public boolean getIn_elenco() {
		return _in_elenco;
	}

	@JSON
	@Override
	public boolean isIn_elenco() {
		return _in_elenco;
	}

	@Override
	public void setIn_elenco(boolean in_elenco) {
		_columnBitmask |= IN_ELENCO_COLUMN_BITMASK;

		if (!_setOriginalIn_elenco) {
			_setOriginalIn_elenco = true;

			_originalIn_elenco = _in_elenco;
		}

		_in_elenco = in_elenco;
	}

	public boolean getOriginalIn_elenco() {
		return _originalIn_elenco;
	}

	@JSON
	@Override
	public long getId_richiesta() {
		return _id_richiesta;
	}

	@Override
	public void setId_richiesta(long id_richiesta) {
		_columnBitmask |= ID_RICHIESTA_COLUMN_BITMASK;

		if (!_setOriginalId_richiesta) {
			_setOriginalId_richiesta = true;

			_originalId_richiesta = _id_richiesta;
		}

		_id_richiesta = id_richiesta;
	}

	public long getOriginalId_richiesta() {
		return _originalId_richiesta;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			BeneInvRichiesto.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public BeneInvRichiesto toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (BeneInvRichiesto)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		BeneInvRichiestoImpl beneInvRichiestoImpl = new BeneInvRichiestoImpl();

		beneInvRichiestoImpl.setId_bene_rich(getId_bene_rich());
		beneInvRichiestoImpl.setTipologia(getTipologia());
		beneInvRichiestoImpl.setDescrizione(getDescrizione());
		beneInvRichiestoImpl.setQuantita(getQuantita());
		beneInvRichiestoImpl.setDettagli(getDettagli());
		beneInvRichiestoImpl.setIn_elenco(getIn_elenco());
		beneInvRichiestoImpl.setId_richiesta(getId_richiesta());

		beneInvRichiestoImpl.resetOriginalValues();

		return beneInvRichiestoImpl;
	}

	@Override
	public int compareTo(BeneInvRichiesto beneInvRichiesto) {
		long primaryKey = beneInvRichiesto.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof BeneInvRichiesto)) {
			return false;
		}

		BeneInvRichiesto beneInvRichiesto = (BeneInvRichiesto)obj;

		long primaryKey = beneInvRichiesto.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		BeneInvRichiestoModelImpl beneInvRichiestoModelImpl = this;

		beneInvRichiestoModelImpl._originalIn_elenco = beneInvRichiestoModelImpl._in_elenco;

		beneInvRichiestoModelImpl._setOriginalIn_elenco = false;

		beneInvRichiestoModelImpl._originalId_richiesta = beneInvRichiestoModelImpl._id_richiesta;

		beneInvRichiestoModelImpl._setOriginalId_richiesta = false;

		beneInvRichiestoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<BeneInvRichiesto> toCacheModel() {
		BeneInvRichiestoCacheModel beneInvRichiestoCacheModel = new BeneInvRichiestoCacheModel();

		beneInvRichiestoCacheModel.id_bene_rich = getId_bene_rich();

		beneInvRichiestoCacheModel.tipologia = getTipologia();

		String tipologia = beneInvRichiestoCacheModel.tipologia;

		if ((tipologia != null) && (tipologia.length() == 0)) {
			beneInvRichiestoCacheModel.tipologia = null;
		}

		beneInvRichiestoCacheModel.descrizione = getDescrizione();

		String descrizione = beneInvRichiestoCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			beneInvRichiestoCacheModel.descrizione = null;
		}

		beneInvRichiestoCacheModel.quantita = getQuantita();

		beneInvRichiestoCacheModel.dettagli = getDettagli();

		String dettagli = beneInvRichiestoCacheModel.dettagli;

		if ((dettagli != null) && (dettagli.length() == 0)) {
			beneInvRichiestoCacheModel.dettagli = null;
		}

		beneInvRichiestoCacheModel.in_elenco = getIn_elenco();

		beneInvRichiestoCacheModel.id_richiesta = getId_richiesta();

		return beneInvRichiestoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(15);

		sb.append("{id_bene_rich=");
		sb.append(getId_bene_rich());
		sb.append(", tipologia=");
		sb.append(getTipologia());
		sb.append(", descrizione=");
		sb.append(getDescrizione());
		sb.append(", quantita=");
		sb.append(getQuantita());
		sb.append(", dettagli=");
		sb.append(getDettagli());
		sb.append(", in_elenco=");
		sb.append(getIn_elenco());
		sb.append(", id_richiesta=");
		sb.append(getId_richiesta());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(25);

		sb.append("<model><model-name>");
		sb.append("service.intranet.mef.model.BeneInvRichiesto");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_bene_rich</column-name><column-value><![CDATA[");
		sb.append(getId_bene_rich());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>tipologia</column-name><column-value><![CDATA[");
		sb.append(getTipologia());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizione</column-name><column-value><![CDATA[");
		sb.append(getDescrizione());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>quantita</column-name><column-value><![CDATA[");
		sb.append(getQuantita());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dettagli</column-name><column-value><![CDATA[");
		sb.append(getDettagli());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>in_elenco</column-name><column-value><![CDATA[");
		sb.append(getIn_elenco());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>id_richiesta</column-name><column-value><![CDATA[");
		sb.append(getId_richiesta());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = BeneInvRichiesto.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			BeneInvRichiesto.class
		};
	private long _id_bene_rich;
	private String _tipologia;
	private String _descrizione;
	private int _quantita;
	private String _dettagli;
	private boolean _in_elenco;
	private boolean _originalIn_elenco;
	private boolean _setOriginalIn_elenco;
	private long _id_richiesta;
	private long _originalId_richiesta;
	private boolean _setOriginalId_richiesta;
	private long _columnBitmask;
	private BeneInvRichiesto _escapedModel;
}