/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import service.intranet.mef.model.LogisticaValutazione;
import service.intranet.mef.model.LogisticaValutazioneModel;
import service.intranet.mef.model.LogisticaValutazioneSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LogisticaValutazione service. Represents a row in the &quot;MFORM_LogisticaValutazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LogisticaValutazioneModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LogisticaValutazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LogisticaValutazioneImpl
 * @see LogisticaValutazione
 * @see LogisticaValutazioneModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LogisticaValutazioneModelImpl extends BaseModelImpl<LogisticaValutazione>
	implements LogisticaValutazioneModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a logistica valutazione model instance should use the {@link LogisticaValutazione} interface instead.
	 */
	public static final String TABLE_NAME = "MFORM_LogisticaValutazione";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "descrizione", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("descrizione", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MFORM_LogisticaValutazione (id_ LONG not null primary key,descrizione VARCHAR(500) null)";
	public static final String TABLE_SQL_DROP = "drop table MFORM_LogisticaValutazione";
	public static final String ORDER_BY_JPQL = " ORDER BY logisticaValutazione.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MFORM_LogisticaValutazione.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.service.intranet.mef.model.LogisticaValutazione"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.service.intranet.mef.model.LogisticaValutazione"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LogisticaValutazione toModel(
		LogisticaValutazioneSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LogisticaValutazione model = new LogisticaValutazioneImpl();

		model.setId(soapModel.getId());
		model.setDescrizione(soapModel.getDescrizione());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LogisticaValutazione> toModels(
		LogisticaValutazioneSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LogisticaValutazione> models = new ArrayList<LogisticaValutazione>(soapModels.length);

		for (LogisticaValutazioneSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(service.intranet.mef.service.util.PropsUtil.get(
				"lock.expiration.time.service.intranet.mef.model.LogisticaValutazione"));

	public LogisticaValutazioneModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LogisticaValutazione.class;
	}

	@Override
	public String getModelClassName() {
		return LogisticaValutazione.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("descrizione", getDescrizione());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String descrizione = (String)attributes.get("descrizione");

		if (descrizione != null) {
			setDescrizione(descrizione);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		_descrizione = descrizione;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LogisticaValutazione.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LogisticaValutazione toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LogisticaValutazione)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LogisticaValutazioneImpl logisticaValutazioneImpl = new LogisticaValutazioneImpl();

		logisticaValutazioneImpl.setId(getId());
		logisticaValutazioneImpl.setDescrizione(getDescrizione());

		logisticaValutazioneImpl.resetOriginalValues();

		return logisticaValutazioneImpl;
	}

	@Override
	public int compareTo(LogisticaValutazione logisticaValutazione) {
		long primaryKey = logisticaValutazione.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LogisticaValutazione)) {
			return false;
		}

		LogisticaValutazione logisticaValutazione = (LogisticaValutazione)obj;

		long primaryKey = logisticaValutazione.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<LogisticaValutazione> toCacheModel() {
		LogisticaValutazioneCacheModel logisticaValutazioneCacheModel = new LogisticaValutazioneCacheModel();

		logisticaValutazioneCacheModel.id = getId();

		logisticaValutazioneCacheModel.descrizione = getDescrizione();

		String descrizione = logisticaValutazioneCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			logisticaValutazioneCacheModel.descrizione = null;
		}

		return logisticaValutazioneCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", descrizione=");
		sb.append(getDescrizione());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("service.intranet.mef.model.LogisticaValutazione");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizione</column-name><column-value><![CDATA[");
		sb.append(getDescrizione());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = LogisticaValutazione.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			LogisticaValutazione.class
		};
	private long _id;
	private String _descrizione;
	private LogisticaValutazione _escapedModel;
}