/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import service.intranet.mef.model.LogisticaStato;
import service.intranet.mef.model.LogisticaStatoModel;
import service.intranet.mef.model.LogisticaStatoSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the LogisticaStato service. Represents a row in the &quot;MFORM_LogisticaStato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LogisticaStatoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LogisticaStatoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LogisticaStatoImpl
 * @see LogisticaStato
 * @see LogisticaStatoModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LogisticaStatoModelImpl extends BaseModelImpl<LogisticaStato>
	implements LogisticaStatoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a logistica stato model instance should use the {@link LogisticaStato} interface instead.
	 */
	public static final String TABLE_NAME = "MFORM_LogisticaStato";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "descrizione", Types.VARCHAR },
			{ "utente", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("utente", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MFORM_LogisticaStato (id_ LONG not null primary key,descrizione VARCHAR(500) null,utente VARCHAR(500) null)";
	public static final String TABLE_SQL_DROP = "drop table MFORM_LogisticaStato";
	public static final String ORDER_BY_JPQL = " ORDER BY logisticaStato.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MFORM_LogisticaStato.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.service.intranet.mef.model.LogisticaStato"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.service.intranet.mef.model.LogisticaStato"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.service.intranet.mef.model.LogisticaStato"),
			true);
	public static final long UTENTE_COLUMN_BITMASK = 1L;
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static LogisticaStato toModel(LogisticaStatoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		LogisticaStato model = new LogisticaStatoImpl();

		model.setId(soapModel.getId());
		model.setDescrizione(soapModel.getDescrizione());
		model.setUtente(soapModel.getUtente());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<LogisticaStato> toModels(LogisticaStatoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<LogisticaStato> models = new ArrayList<LogisticaStato>(soapModels.length);

		for (LogisticaStatoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(service.intranet.mef.service.util.PropsUtil.get(
				"lock.expiration.time.service.intranet.mef.model.LogisticaStato"));

	public LogisticaStatoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return LogisticaStato.class;
	}

	@Override
	public String getModelClassName() {
		return LogisticaStato.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("descrizione", getDescrizione());
		attributes.put("utente", getUtente());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String descrizione = (String)attributes.get("descrizione");

		if (descrizione != null) {
			setDescrizione(descrizione);
		}

		String utente = (String)attributes.get("utente");

		if (utente != null) {
			setUtente(utente);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		_descrizione = descrizione;
	}

	@JSON
	@Override
	public String getUtente() {
		if (_utente == null) {
			return StringPool.BLANK;
		}
		else {
			return _utente;
		}
	}

	@Override
	public void setUtente(String utente) {
		_columnBitmask |= UTENTE_COLUMN_BITMASK;

		if (_originalUtente == null) {
			_originalUtente = _utente;
		}

		_utente = utente;
	}

	public String getOriginalUtente() {
		return GetterUtil.getString(_originalUtente);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			LogisticaStato.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public LogisticaStato toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (LogisticaStato)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LogisticaStatoImpl logisticaStatoImpl = new LogisticaStatoImpl();

		logisticaStatoImpl.setId(getId());
		logisticaStatoImpl.setDescrizione(getDescrizione());
		logisticaStatoImpl.setUtente(getUtente());

		logisticaStatoImpl.resetOriginalValues();

		return logisticaStatoImpl;
	}

	@Override
	public int compareTo(LogisticaStato logisticaStato) {
		long primaryKey = logisticaStato.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof LogisticaStato)) {
			return false;
		}

		LogisticaStato logisticaStato = (LogisticaStato)obj;

		long primaryKey = logisticaStato.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		LogisticaStatoModelImpl logisticaStatoModelImpl = this;

		logisticaStatoModelImpl._originalUtente = logisticaStatoModelImpl._utente;

		logisticaStatoModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<LogisticaStato> toCacheModel() {
		LogisticaStatoCacheModel logisticaStatoCacheModel = new LogisticaStatoCacheModel();

		logisticaStatoCacheModel.id = getId();

		logisticaStatoCacheModel.descrizione = getDescrizione();

		String descrizione = logisticaStatoCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			logisticaStatoCacheModel.descrizione = null;
		}

		logisticaStatoCacheModel.utente = getUtente();

		String utente = logisticaStatoCacheModel.utente;

		if ((utente != null) && (utente.length() == 0)) {
			logisticaStatoCacheModel.utente = null;
		}

		return logisticaStatoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", descrizione=");
		sb.append(getDescrizione());
		sb.append(", utente=");
		sb.append(getUtente());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("service.intranet.mef.model.LogisticaStato");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizione</column-name><column-value><![CDATA[");
		sb.append(getDescrizione());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>utente</column-name><column-value><![CDATA[");
		sb.append(getUtente());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = LogisticaStato.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			LogisticaStato.class
		};
	private long _id;
	private String _descrizione;
	private String _utente;
	private String _originalUtente;
	private long _columnBitmask;
	private LogisticaStato _escapedModel;
}