/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import service.intranet.mef.model.RichiestaInterventi;
import service.intranet.mef.model.RichiestaInterventiModel;
import service.intranet.mef.model.RichiestaInterventiSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the RichiestaInterventi service. Represents a row in the &quot;MFORM_RichiestaInterventi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link RichiestaInterventiModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link RichiestaInterventiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RichiestaInterventiImpl
 * @see RichiestaInterventi
 * @see RichiestaInterventiModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class RichiestaInterventiModelImpl extends BaseModelImpl<RichiestaInterventi>
	implements RichiestaInterventiModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a richiesta interventi model instance should use the {@link RichiestaInterventi} interface instead.
	 */
	public static final String TABLE_NAME = "MFORM_RichiestaInterventi";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "utente", Types.VARCHAR },
			{ "dettaglio", Types.VARCHAR },
			{ "data_interventi", Types.TIMESTAMP }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("utente", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dettaglio", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("data_interventi", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE = "create table MFORM_RichiestaInterventi (id_ LONG not null primary key,utente VARCHAR(75) null,dettaglio VARCHAR(2500) null,data_interventi DATE null)";
	public static final String TABLE_SQL_DROP = "drop table MFORM_RichiestaInterventi";
	public static final String ORDER_BY_JPQL = " ORDER BY richiestaInterventi.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MFORM_RichiestaInterventi.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.service.intranet.mef.model.RichiestaInterventi"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.service.intranet.mef.model.RichiestaInterventi"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static RichiestaInterventi toModel(RichiestaInterventiSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		RichiestaInterventi model = new RichiestaInterventiImpl();

		model.setId(soapModel.getId());
		model.setUtente(soapModel.getUtente());
		model.setDettaglio(soapModel.getDettaglio());
		model.setData_interventi(soapModel.getData_interventi());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<RichiestaInterventi> toModels(
		RichiestaInterventiSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<RichiestaInterventi> models = new ArrayList<RichiestaInterventi>(soapModels.length);

		for (RichiestaInterventiSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(service.intranet.mef.service.util.PropsUtil.get(
				"lock.expiration.time.service.intranet.mef.model.RichiestaInterventi"));

	public RichiestaInterventiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return RichiestaInterventi.class;
	}

	@Override
	public String getModelClassName() {
		return RichiestaInterventi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("utente", getUtente());
		attributes.put("dettaglio", getDettaglio());
		attributes.put("data_interventi", getData_interventi());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String utente = (String)attributes.get("utente");

		if (utente != null) {
			setUtente(utente);
		}

		String dettaglio = (String)attributes.get("dettaglio");

		if (dettaglio != null) {
			setDettaglio(dettaglio);
		}

		Date data_interventi = (Date)attributes.get("data_interventi");

		if (data_interventi != null) {
			setData_interventi(data_interventi);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getUtente() {
		if (_utente == null) {
			return StringPool.BLANK;
		}
		else {
			return _utente;
		}
	}

	@Override
	public void setUtente(String utente) {
		_utente = utente;
	}

	@JSON
	@Override
	public String getDettaglio() {
		if (_dettaglio == null) {
			return StringPool.BLANK;
		}
		else {
			return _dettaglio;
		}
	}

	@Override
	public void setDettaglio(String dettaglio) {
		_dettaglio = dettaglio;
	}

	@JSON
	@Override
	public Date getData_interventi() {
		return _data_interventi;
	}

	@Override
	public void setData_interventi(Date data_interventi) {
		_data_interventi = data_interventi;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			RichiestaInterventi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public RichiestaInterventi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (RichiestaInterventi)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		RichiestaInterventiImpl richiestaInterventiImpl = new RichiestaInterventiImpl();

		richiestaInterventiImpl.setId(getId());
		richiestaInterventiImpl.setUtente(getUtente());
		richiestaInterventiImpl.setDettaglio(getDettaglio());
		richiestaInterventiImpl.setData_interventi(getData_interventi());

		richiestaInterventiImpl.resetOriginalValues();

		return richiestaInterventiImpl;
	}

	@Override
	public int compareTo(RichiestaInterventi richiestaInterventi) {
		long primaryKey = richiestaInterventi.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof RichiestaInterventi)) {
			return false;
		}

		RichiestaInterventi richiestaInterventi = (RichiestaInterventi)obj;

		long primaryKey = richiestaInterventi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<RichiestaInterventi> toCacheModel() {
		RichiestaInterventiCacheModel richiestaInterventiCacheModel = new RichiestaInterventiCacheModel();

		richiestaInterventiCacheModel.id = getId();

		richiestaInterventiCacheModel.utente = getUtente();

		String utente = richiestaInterventiCacheModel.utente;

		if ((utente != null) && (utente.length() == 0)) {
			richiestaInterventiCacheModel.utente = null;
		}

		richiestaInterventiCacheModel.dettaglio = getDettaglio();

		String dettaglio = richiestaInterventiCacheModel.dettaglio;

		if ((dettaglio != null) && (dettaglio.length() == 0)) {
			richiestaInterventiCacheModel.dettaglio = null;
		}

		Date data_interventi = getData_interventi();

		if (data_interventi != null) {
			richiestaInterventiCacheModel.data_interventi = data_interventi.getTime();
		}
		else {
			richiestaInterventiCacheModel.data_interventi = Long.MIN_VALUE;
		}

		return richiestaInterventiCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", utente=");
		sb.append(getUtente());
		sb.append(", dettaglio=");
		sb.append(getDettaglio());
		sb.append(", data_interventi=");
		sb.append(getData_interventi());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("service.intranet.mef.model.RichiestaInterventi");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>utente</column-name><column-value><![CDATA[");
		sb.append(getUtente());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dettaglio</column-name><column-value><![CDATA[");
		sb.append(getDettaglio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>data_interventi</column-name><column-value><![CDATA[");
		sb.append(getData_interventi());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = RichiestaInterventi.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			RichiestaInterventi.class
		};
	private long _id;
	private String _utente;
	private String _dettaglio;
	private Date _data_interventi;
	private RichiestaInterventi _escapedModel;
}