/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import service.intranet.mef.model.StatoRichBeneInv;
import service.intranet.mef.model.StatoRichBeneInvModel;
import service.intranet.mef.model.StatoRichBeneInvSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the StatoRichBeneInv service. Represents a row in the &quot;MFORM_StatoRichBeneInv&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link StatoRichBeneInvModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatoRichBeneInvImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StatoRichBeneInvImpl
 * @see StatoRichBeneInv
 * @see StatoRichBeneInvModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class StatoRichBeneInvModelImpl extends BaseModelImpl<StatoRichBeneInv>
	implements StatoRichBeneInvModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a stato rich bene inv model instance should use the {@link StatoRichBeneInv} interface instead.
	 */
	public static final String TABLE_NAME = "MFORM_StatoRichBeneInv";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_", Types.BIGINT },
			{ "stato", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("stato", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MFORM_StatoRichBeneInv (id_ LONG not null primary key,stato VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table MFORM_StatoRichBeneInv";
	public static final String ORDER_BY_JPQL = " ORDER BY statoRichBeneInv.id ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MFORM_StatoRichBeneInv.id_ ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.service.intranet.mef.model.StatoRichBeneInv"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.service.intranet.mef.model.StatoRichBeneInv"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.service.intranet.mef.model.StatoRichBeneInv"),
			true);
	public static final long STATO_COLUMN_BITMASK = 1L;
	public static final long ID_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static StatoRichBeneInv toModel(StatoRichBeneInvSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		StatoRichBeneInv model = new StatoRichBeneInvImpl();

		model.setId(soapModel.getId());
		model.setStato(soapModel.getStato());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<StatoRichBeneInv> toModels(
		StatoRichBeneInvSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<StatoRichBeneInv> models = new ArrayList<StatoRichBeneInv>(soapModels.length);

		for (StatoRichBeneInvSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(service.intranet.mef.service.util.PropsUtil.get(
				"lock.expiration.time.service.intranet.mef.model.StatoRichBeneInv"));

	public StatoRichBeneInvModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StatoRichBeneInv.class;
	}

	@Override
	public String getModelClassName() {
		return StatoRichBeneInv.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id", getId());
		attributes.put("stato", getStato());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id = (Long)attributes.get("id");

		if (id != null) {
			setId(id);
		}

		String stato = (String)attributes.get("stato");

		if (stato != null) {
			setStato(stato);
		}
	}

	@JSON
	@Override
	public long getId() {
		return _id;
	}

	@Override
	public void setId(long id) {
		_id = id;
	}

	@JSON
	@Override
	public String getStato() {
		if (_stato == null) {
			return StringPool.BLANK;
		}
		else {
			return _stato;
		}
	}

	@Override
	public void setStato(String stato) {
		_columnBitmask |= STATO_COLUMN_BITMASK;

		if (_originalStato == null) {
			_originalStato = _stato;
		}

		_stato = stato;
	}

	public String getOriginalStato() {
		return GetterUtil.getString(_originalStato);
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			StatoRichBeneInv.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StatoRichBeneInv toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StatoRichBeneInv)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StatoRichBeneInvImpl statoRichBeneInvImpl = new StatoRichBeneInvImpl();

		statoRichBeneInvImpl.setId(getId());
		statoRichBeneInvImpl.setStato(getStato());

		statoRichBeneInvImpl.resetOriginalValues();

		return statoRichBeneInvImpl;
	}

	@Override
	public int compareTo(StatoRichBeneInv statoRichBeneInv) {
		long primaryKey = statoRichBeneInv.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StatoRichBeneInv)) {
			return false;
		}

		StatoRichBeneInv statoRichBeneInv = (StatoRichBeneInv)obj;

		long primaryKey = statoRichBeneInv.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		StatoRichBeneInvModelImpl statoRichBeneInvModelImpl = this;

		statoRichBeneInvModelImpl._originalStato = statoRichBeneInvModelImpl._stato;

		statoRichBeneInvModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<StatoRichBeneInv> toCacheModel() {
		StatoRichBeneInvCacheModel statoRichBeneInvCacheModel = new StatoRichBeneInvCacheModel();

		statoRichBeneInvCacheModel.id = getId();

		statoRichBeneInvCacheModel.stato = getStato();

		String stato = statoRichBeneInvCacheModel.stato;

		if ((stato != null) && (stato.length() == 0)) {
			statoRichBeneInvCacheModel.stato = null;
		}

		return statoRichBeneInvCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id=");
		sb.append(getId());
		sb.append(", stato=");
		sb.append(getStato());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("service.intranet.mef.model.StatoRichBeneInv");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id</column-name><column-value><![CDATA[");
		sb.append(getId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>stato</column-name><column-value><![CDATA[");
		sb.append(getStato());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = StatoRichBeneInv.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			StatoRichBeneInv.class
		};
	private long _id;
	private String _stato;
	private String _originalStato;
	private long _columnBitmask;
	private StatoRichBeneInv _escapedModel;
}