/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package service.intranet.mef.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import service.intranet.mef.model.TipologiaDispositivi;
import service.intranet.mef.model.TipologiaDispositiviModel;
import service.intranet.mef.model.TipologiaDispositiviSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TipologiaDispositivi service. Represents a row in the &quot;MFORM_TipologiaDispositivi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link TipologiaDispositiviModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TipologiaDispositiviImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TipologiaDispositiviImpl
 * @see TipologiaDispositivi
 * @see TipologiaDispositiviModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class TipologiaDispositiviModelImpl extends BaseModelImpl<TipologiaDispositivi>
	implements TipologiaDispositiviModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tipologia dispositivi model instance should use the {@link TipologiaDispositivi} interface instead.
	 */
	public static final String TABLE_NAME = "MFORM_TipologiaDispositivi";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_tipologia_dispositivi", Types.BIGINT },
			{ "descrizione", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_tipologia_dispositivi", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("descrizione", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MFORM_TipologiaDispositivi (id_tipologia_dispositivi LONG not null primary key,descrizione VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table MFORM_TipologiaDispositivi";
	public static final String ORDER_BY_JPQL = " ORDER BY tipologiaDispositivi.id_tipologia_dispositivi ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MFORM_TipologiaDispositivi.id_tipologia_dispositivi ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.service.intranet.mef.model.TipologiaDispositivi"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(service.intranet.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.service.intranet.mef.model.TipologiaDispositivi"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TipologiaDispositivi toModel(
		TipologiaDispositiviSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TipologiaDispositivi model = new TipologiaDispositiviImpl();

		model.setId_tipologia_dispositivi(soapModel.getId_tipologia_dispositivi());
		model.setDescrizione(soapModel.getDescrizione());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TipologiaDispositivi> toModels(
		TipologiaDispositiviSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TipologiaDispositivi> models = new ArrayList<TipologiaDispositivi>(soapModels.length);

		for (TipologiaDispositiviSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(service.intranet.mef.service.util.PropsUtil.get(
				"lock.expiration.time.service.intranet.mef.model.TipologiaDispositivi"));

	public TipologiaDispositiviModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_tipologia_dispositivi;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_tipologia_dispositivi(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_tipologia_dispositivi;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return TipologiaDispositivi.class;
	}

	@Override
	public String getModelClassName() {
		return TipologiaDispositivi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_tipologia_dispositivi", getId_tipologia_dispositivi());
		attributes.put("descrizione", getDescrizione());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_tipologia_dispositivi = (Long)attributes.get(
				"id_tipologia_dispositivi");

		if (id_tipologia_dispositivi != null) {
			setId_tipologia_dispositivi(id_tipologia_dispositivi);
		}

		String descrizione = (String)attributes.get("descrizione");

		if (descrizione != null) {
			setDescrizione(descrizione);
		}
	}

	@JSON
	@Override
	public long getId_tipologia_dispositivi() {
		return _id_tipologia_dispositivi;
	}

	@Override
	public void setId_tipologia_dispositivi(long id_tipologia_dispositivi) {
		_id_tipologia_dispositivi = id_tipologia_dispositivi;
	}

	@JSON
	@Override
	public String getDescrizione() {
		if (_descrizione == null) {
			return StringPool.BLANK;
		}
		else {
			return _descrizione;
		}
	}

	@Override
	public void setDescrizione(String descrizione) {
		_descrizione = descrizione;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TipologiaDispositivi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TipologiaDispositivi toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (TipologiaDispositivi)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		TipologiaDispositiviImpl tipologiaDispositiviImpl = new TipologiaDispositiviImpl();

		tipologiaDispositiviImpl.setId_tipologia_dispositivi(getId_tipologia_dispositivi());
		tipologiaDispositiviImpl.setDescrizione(getDescrizione());

		tipologiaDispositiviImpl.resetOriginalValues();

		return tipologiaDispositiviImpl;
	}

	@Override
	public int compareTo(TipologiaDispositivi tipologiaDispositivi) {
		long primaryKey = tipologiaDispositivi.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof TipologiaDispositivi)) {
			return false;
		}

		TipologiaDispositivi tipologiaDispositivi = (TipologiaDispositivi)obj;

		long primaryKey = tipologiaDispositivi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TipologiaDispositivi> toCacheModel() {
		TipologiaDispositiviCacheModel tipologiaDispositiviCacheModel = new TipologiaDispositiviCacheModel();

		tipologiaDispositiviCacheModel.id_tipologia_dispositivi = getId_tipologia_dispositivi();

		tipologiaDispositiviCacheModel.descrizione = getDescrizione();

		String descrizione = tipologiaDispositiviCacheModel.descrizione;

		if ((descrizione != null) && (descrizione.length() == 0)) {
			tipologiaDispositiviCacheModel.descrizione = null;
		}

		return tipologiaDispositiviCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id_tipologia_dispositivi=");
		sb.append(getId_tipologia_dispositivi());
		sb.append(", descrizione=");
		sb.append(getDescrizione());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("service.intranet.mef.model.TipologiaDispositivi");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_tipologia_dispositivi</column-name><column-value><![CDATA[");
		sb.append(getId_tipologia_dispositivi());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>descrizione</column-name><column-value><![CDATA[");
		sb.append(getDescrizione());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = TipologiaDispositivi.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			TipologiaDispositivi.class
		};
	private long _id_tipologia_dispositivi;
	private String _descrizione;
	private TipologiaDispositivi _escapedModel;
}