/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mef.richieste.figli.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the RICHIESTA_RIMBORSO service. Represents a row in the &quot;MFORM_RICHIESTA_RIMBORSO&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>mef.richieste.figli.model.impl.RICHIESTA_RIMBORSOModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>mef.richieste.figli.model.impl.RICHIESTA_RIMBORSOImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see RICHIESTA_RIMBORSO
 * @generated
 */
@ProviderType
public interface RICHIESTA_RIMBORSOModel extends BaseModel<RICHIESTA_RIMBORSO> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a richiesta_rimborso model instance should use the {@link RICHIESTA_RIMBORSO} interface instead.
	 */

	/**
	 * Returns the primary key of this richiesta_rimborso.
	 *
	 * @return the primary key of this richiesta_rimborso
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this richiesta_rimborso.
	 *
	 * @param primaryKey the primary key of this richiesta_rimborso
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this richiesta_rimborso.
	 *
	 * @return the ID of this richiesta_rimborso
	 */
	public long getId();

	/**
	 * Sets the ID of this richiesta_rimborso.
	 *
	 * @param Id the ID of this richiesta_rimborso
	 */
	public void setId(long Id);

	/**
	 * Returns the nome_ richiedente of this richiesta_rimborso.
	 *
	 * @return the nome_ richiedente of this richiesta_rimborso
	 */
	@AutoEscape
	public String getNome_Richiedente();

	/**
	 * Sets the nome_ richiedente of this richiesta_rimborso.
	 *
	 * @param Nome_Richiedente the nome_ richiedente of this richiesta_rimborso
	 */
	public void setNome_Richiedente(String Nome_Richiedente);

	/**
	 * Returns the cognome_ richiedente of this richiesta_rimborso.
	 *
	 * @return the cognome_ richiedente of this richiesta_rimborso
	 */
	@AutoEscape
	public String getCognome_Richiedente();

	/**
	 * Sets the cognome_ richiedente of this richiesta_rimborso.
	 *
	 * @param Cognome_Richiedente the cognome_ richiedente of this richiesta_rimborso
	 */
	public void setCognome_Richiedente(String Cognome_Richiedente);

	/**
	 * Returns the codice_ fiscale_ richiedente of this richiesta_rimborso.
	 *
	 * @return the codice_ fiscale_ richiedente of this richiesta_rimborso
	 */
	@AutoEscape
	public String getCodice_Fiscale_Richiedente();

	/**
	 * Sets the codice_ fiscale_ richiedente of this richiesta_rimborso.
	 *
	 * @param Codice_Fiscale_Richiedente the codice_ fiscale_ richiedente of this richiesta_rimborso
	 */
	public void setCodice_Fiscale_Richiedente(
		String Codice_Fiscale_Richiedente);

	/**
	 * Returns the utente_ inserimento of this richiesta_rimborso.
	 *
	 * @return the utente_ inserimento of this richiesta_rimborso
	 */
	@AutoEscape
	public String getUtente_Inserimento();

	/**
	 * Sets the utente_ inserimento of this richiesta_rimborso.
	 *
	 * @param Utente_Inserimento the utente_ inserimento of this richiesta_rimborso
	 */
	public void setUtente_Inserimento(String Utente_Inserimento);

	/**
	 * Returns the data_ inserimento of this richiesta_rimborso.
	 *
	 * @return the data_ inserimento of this richiesta_rimborso
	 */
	@AutoEscape
	public String getData_Inserimento();

	/**
	 * Sets the data_ inserimento of this richiesta_rimborso.
	 *
	 * @param Data_Inserimento the data_ inserimento of this richiesta_rimborso
	 */
	public void setData_Inserimento(String Data_Inserimento);

	/**
	 * Returns the iban of this richiesta_rimborso.
	 *
	 * @return the iban of this richiesta_rimborso
	 */
	@AutoEscape
	public String getIban();

	/**
	 * Sets the iban of this richiesta_rimborso.
	 *
	 * @param Iban the iban of this richiesta_rimborso
	 */
	public void setIban(String Iban);

	/**
	 * Returns the importo of this richiesta_rimborso.
	 *
	 * @return the importo of this richiesta_rimborso
	 */
	@AutoEscape
	public String getImporto();

	/**
	 * Sets the importo of this richiesta_rimborso.
	 *
	 * @param Importo the importo of this richiesta_rimborso
	 */
	public void setImporto(String Importo);

	/**
	 * Returns the figlio_ nome of this richiesta_rimborso.
	 *
	 * @return the figlio_ nome of this richiesta_rimborso
	 */
	@AutoEscape
	public String getFiglio_Nome();

	/**
	 * Sets the figlio_ nome of this richiesta_rimborso.
	 *
	 * @param Figlio_Nome the figlio_ nome of this richiesta_rimborso
	 */
	public void setFiglio_Nome(String Figlio_Nome);

	/**
	 * Returns the figlio_ cognome of this richiesta_rimborso.
	 *
	 * @return the figlio_ cognome of this richiesta_rimborso
	 */
	@AutoEscape
	public String getFiglio_Cognome();

	/**
	 * Sets the figlio_ cognome of this richiesta_rimborso.
	 *
	 * @param Figlio_Cognome the figlio_ cognome of this richiesta_rimborso
	 */
	public void setFiglio_Cognome(String Figlio_Cognome);

	/**
	 * Returns the figlio_ data_ nascita of this richiesta_rimborso.
	 *
	 * @return the figlio_ data_ nascita of this richiesta_rimborso
	 */
	@AutoEscape
	public String getFiglio_Data_Nascita();

	/**
	 * Sets the figlio_ data_ nascita of this richiesta_rimborso.
	 *
	 * @param Figlio_Data_Nascita the figlio_ data_ nascita of this richiesta_rimborso
	 */
	public void setFiglio_Data_Nascita(String Figlio_Data_Nascita);

	/**
	 * Returns the figlio_ luogo_ nascita of this richiesta_rimborso.
	 *
	 * @return the figlio_ luogo_ nascita of this richiesta_rimborso
	 */
	@AutoEscape
	public String getFiglio_Luogo_Nascita();

	/**
	 * Sets the figlio_ luogo_ nascita of this richiesta_rimborso.
	 *
	 * @param Figlio_Luogo_Nascita the figlio_ luogo_ nascita of this richiesta_rimborso
	 */
	public void setFiglio_Luogo_Nascita(String Figlio_Luogo_Nascita);

	/**
	 * Returns the figlio_ codice_ fiscale of this richiesta_rimborso.
	 *
	 * @return the figlio_ codice_ fiscale of this richiesta_rimborso
	 */
	@AutoEscape
	public String getFiglio_Codice_Fiscale();

	/**
	 * Sets the figlio_ codice_ fiscale of this richiesta_rimborso.
	 *
	 * @param Figlio_Codice_Fiscale the figlio_ codice_ fiscale of this richiesta_rimborso
	 */
	public void setFiglio_Codice_Fiscale(String Figlio_Codice_Fiscale);

	/**
	 * Returns the note of this richiesta_rimborso.
	 *
	 * @return the note of this richiesta_rimborso
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this richiesta_rimborso.
	 *
	 * @param Note the note of this richiesta_rimborso
	 */
	public void setNote(String Note);

	/**
	 * Returns the flag_ inviato of this richiesta_rimborso.
	 *
	 * @return the flag_ inviato of this richiesta_rimborso
	 */
	public Boolean getFlag_Inviato();

	/**
	 * Sets the flag_ inviato of this richiesta_rimborso.
	 *
	 * @param Flag_Inviato the flag_ inviato of this richiesta_rimborso
	 */
	public void setFlag_Inviato(Boolean Flag_Inviato);

	/**
	 * Returns the telefono of this richiesta_rimborso.
	 *
	 * @return the telefono of this richiesta_rimborso
	 */
	@AutoEscape
	public String getTelefono();

	/**
	 * Sets the telefono of this richiesta_rimborso.
	 *
	 * @param Telefono the telefono of this richiesta_rimborso
	 */
	public void setTelefono(String Telefono);

	/**
	 * Returns the allegato_uuid of this richiesta_rimborso.
	 *
	 * @return the allegato_uuid of this richiesta_rimborso
	 */
	@AutoEscape
	public String getAllegato_UUID();

	/**
	 * Sets the allegato_uuid of this richiesta_rimborso.
	 *
	 * @param Allegato_UUID the allegato_uuid of this richiesta_rimborso
	 */
	public void setAllegato_UUID(String Allegato_UUID);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		mef.richieste.figli.model.RICHIESTA_RIMBORSO richiesta_rimborso);

	@Override
	public int hashCode();

	@Override
	public CacheModel<mef.richieste.figli.model.RICHIESTA_RIMBORSO>
		toCacheModel();

	@Override
	public mef.richieste.figli.model.RICHIESTA_RIMBORSO toEscapedModel();

	@Override
	public mef.richieste.figli.model.RICHIESTA_RIMBORSO toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}