/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package mef.richiesta.gest.pos.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.Collections;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

import mef.richiesta.gest.pos.model.Piano;
import mef.richiesta.gest.pos.model.PianoModel;

/**
 * The base model implementation for the Piano service. Represents a row in the &quot;BADGE_POS_Piano&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface </code>PianoModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PianoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PianoImpl
 * @generated
 */
@ProviderType
public class PianoModelImpl extends BaseModelImpl<Piano> implements PianoModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a piano model instance should use the <code>Piano</code> interface instead.
	 */
	public static final String TABLE_NAME = "BADGE_POS_Piano";

	public static final Object[][] TABLE_COLUMNS = {
		{"id_pk_piano", Types.BIGINT}, {"id_piano", Types.BIGINT},
		{"id_sede", Types.BIGINT}, {"cod_piano", Types.VARCHAR},
		{"desc_", Types.VARCHAR}, {"data_ins", Types.VARCHAR},
		{"data_agg", Types.VARCHAR}, {"user_ins", Types.VARCHAR},
		{"user_agg", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_pk_piano", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("id_piano", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("id_sede", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("cod_piano", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("desc_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("data_ins", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("data_agg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("user_ins", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("user_agg", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table BADGE_POS_Piano (id_pk_piano LONG not null primary key,id_piano LONG,id_sede LONG,cod_piano VARCHAR(75) null,desc_ VARCHAR(75) null,data_ins VARCHAR(75) null,data_agg VARCHAR(75) null,user_ins VARCHAR(75) null,user_agg VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table BADGE_POS_Piano";

	public static final String ORDER_BY_JPQL =
		" ORDER BY piano.id_pk_piano ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY BADGE_POS_Piano.id_pk_piano ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(
		mef.richiesta.gest.pos.service.util.ServiceProps.get(
			"value.object.entity.cache.enabled.mef.richiesta.gest.pos.model.Piano"),
		true);

	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(
		mef.richiesta.gest.pos.service.util.ServiceProps.get(
			"value.object.finder.cache.enabled.mef.richiesta.gest.pos.model.Piano"),
		true);

	public static final boolean COLUMN_BITMASK_ENABLED = false;

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(
		mef.richiesta.gest.pos.service.util.ServiceProps.get(
			"lock.expiration.time.mef.richiesta.gest.pos.model.Piano"));

	public PianoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_pk_piano;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_pk_piano(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_pk_piano;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Piano.class;
	}

	@Override
	public String getModelClassName() {
		return Piano.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Piano, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Piano, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Piano, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Piano)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Piano, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Piano, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Piano)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Piano, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Piano, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Piano>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Piano.class.getClassLoader(), Piano.class, ModelWrapper.class);

		try {
			Constructor<Piano> constructor =
				(Constructor<Piano>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException roe) {
					throw new InternalError(roe);
				}
			};
		}
		catch (NoSuchMethodException nsme) {
			throw new InternalError(nsme);
		}
	}

	private static final Map<String, Function<Piano, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Piano, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Piano, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Piano, Object>>();
		Map<String, BiConsumer<Piano, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Piano, ?>>();

		attributeGetterFunctions.put(
			"id_pk_piano",
			new Function<Piano, Object>() {

				@Override
				public Object apply(Piano piano) {
					return piano.getId_pk_piano();
				}

			});
		attributeSetterBiConsumers.put(
			"id_pk_piano",
			new BiConsumer<Piano, Object>() {

				@Override
				public void accept(Piano piano, Object id_pk_piano) {
					piano.setId_pk_piano((Long)id_pk_piano);
				}

			});
		attributeGetterFunctions.put(
			"id_piano",
			new Function<Piano, Object>() {

				@Override
				public Object apply(Piano piano) {
					return piano.getId_piano();
				}

			});
		attributeSetterBiConsumers.put(
			"id_piano",
			new BiConsumer<Piano, Object>() {

				@Override
				public void accept(Piano piano, Object id_piano) {
					piano.setId_piano((Long)id_piano);
				}

			});
		attributeGetterFunctions.put(
			"id_sede",
			new Function<Piano, Object>() {

				@Override
				public Object apply(Piano piano) {
					return piano.getId_sede();
				}

			});
		attributeSetterBiConsumers.put(
			"id_sede",
			new BiConsumer<Piano, Object>() {

				@Override
				public void accept(Piano piano, Object id_sede) {
					piano.setId_sede((Long)id_sede);
				}

			});
		attributeGetterFunctions.put(
			"cod_piano",
			new Function<Piano, Object>() {

				@Override
				public Object apply(Piano piano) {
					return piano.getCod_piano();
				}

			});
		attributeSetterBiConsumers.put(
			"cod_piano",
			new BiConsumer<Piano, Object>() {

				@Override
				public void accept(Piano piano, Object cod_piano) {
					piano.setCod_piano((String)cod_piano);
				}

			});
		attributeGetterFunctions.put(
			"desc",
			new Function<Piano, Object>() {

				@Override
				public Object apply(Piano piano) {
					return piano.getDesc();
				}

			});
		attributeSetterBiConsumers.put(
			"desc",
			new BiConsumer<Piano, Object>() {

				@Override
				public void accept(Piano piano, Object desc) {
					piano.setDesc((String)desc);
				}

			});
		attributeGetterFunctions.put(
			"data_ins",
			new Function<Piano, Object>() {

				@Override
				public Object apply(Piano piano) {
					return piano.getData_ins();
				}

			});
		attributeSetterBiConsumers.put(
			"data_ins",
			new BiConsumer<Piano, Object>() {

				@Override
				public void accept(Piano piano, Object data_ins) {
					piano.setData_ins((String)data_ins);
				}

			});
		attributeGetterFunctions.put(
			"data_agg",
			new Function<Piano, Object>() {

				@Override
				public Object apply(Piano piano) {
					return piano.getData_agg();
				}

			});
		attributeSetterBiConsumers.put(
			"data_agg",
			new BiConsumer<Piano, Object>() {

				@Override
				public void accept(Piano piano, Object data_agg) {
					piano.setData_agg((String)data_agg);
				}

			});
		attributeGetterFunctions.put(
			"user_ins",
			new Function<Piano, Object>() {

				@Override
				public Object apply(Piano piano) {
					return piano.getUser_ins();
				}

			});
		attributeSetterBiConsumers.put(
			"user_ins",
			new BiConsumer<Piano, Object>() {

				@Override
				public void accept(Piano piano, Object user_ins) {
					piano.setUser_ins((String)user_ins);
				}

			});
		attributeGetterFunctions.put(
			"user_agg",
			new Function<Piano, Object>() {

				@Override
				public Object apply(Piano piano) {
					return piano.getUser_agg();
				}

			});
		attributeSetterBiConsumers.put(
			"user_agg",
			new BiConsumer<Piano, Object>() {

				@Override
				public void accept(Piano piano, Object user_agg) {
					piano.setUser_agg((String)user_agg);
				}

			});

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId_pk_piano() {
		return _id_pk_piano;
	}

	@Override
	public void setId_pk_piano(long id_pk_piano) {
		_id_pk_piano = id_pk_piano;
	}

	@Override
	public long getId_piano() {
		return _id_piano;
	}

	@Override
	public void setId_piano(long id_piano) {
		_id_piano = id_piano;
	}

	@Override
	public long getId_sede() {
		return _id_sede;
	}

	@Override
	public void setId_sede(long id_sede) {
		_id_sede = id_sede;
	}

	@Override
	public String getCod_piano() {
		if (_cod_piano == null) {
			return "";
		}
		else {
			return _cod_piano;
		}
	}

	@Override
	public void setCod_piano(String cod_piano) {
		_cod_piano = cod_piano;
	}

	@Override
	public String getDesc() {
		if (_desc == null) {
			return "";
		}
		else {
			return _desc;
		}
	}

	@Override
	public void setDesc(String desc) {
		_desc = desc;
	}

	@Override
	public String getData_ins() {
		if (_data_ins == null) {
			return "";
		}
		else {
			return _data_ins;
		}
	}

	@Override
	public void setData_ins(String data_ins) {
		_data_ins = data_ins;
	}

	@Override
	public String getData_agg() {
		if (_data_agg == null) {
			return "";
		}
		else {
			return _data_agg;
		}
	}

	@Override
	public void setData_agg(String data_agg) {
		_data_agg = data_agg;
	}

	@Override
	public String getUser_ins() {
		if (_user_ins == null) {
			return "";
		}
		else {
			return _user_ins;
		}
	}

	@Override
	public void setUser_ins(String user_ins) {
		_user_ins = user_ins;
	}

	@Override
	public String getUser_agg() {
		if (_user_agg == null) {
			return "";
		}
		else {
			return _user_agg;
		}
	}

	@Override
	public void setUser_agg(String user_agg) {
		_user_agg = user_agg;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, Piano.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Piano toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = _escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PianoImpl pianoImpl = new PianoImpl();

		pianoImpl.setId_pk_piano(getId_pk_piano());
		pianoImpl.setId_piano(getId_piano());
		pianoImpl.setId_sede(getId_sede());
		pianoImpl.setCod_piano(getCod_piano());
		pianoImpl.setDesc(getDesc());
		pianoImpl.setData_ins(getData_ins());
		pianoImpl.setData_agg(getData_agg());
		pianoImpl.setUser_ins(getUser_ins());
		pianoImpl.setUser_agg(getUser_agg());

		pianoImpl.resetOriginalValues();

		return pianoImpl;
	}

	@Override
	public int compareTo(Piano piano) {
		long primaryKey = piano.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Piano)) {
			return false;
		}

		Piano piano = (Piano)obj;

		long primaryKey = piano.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Piano> toCacheModel() {
		PianoCacheModel pianoCacheModel = new PianoCacheModel();

		pianoCacheModel.id_pk_piano = getId_pk_piano();

		pianoCacheModel.id_piano = getId_piano();

		pianoCacheModel.id_sede = getId_sede();

		pianoCacheModel.cod_piano = getCod_piano();

		String cod_piano = pianoCacheModel.cod_piano;

		if ((cod_piano != null) && (cod_piano.length() == 0)) {
			pianoCacheModel.cod_piano = null;
		}

		pianoCacheModel.desc = getDesc();

		String desc = pianoCacheModel.desc;

		if ((desc != null) && (desc.length() == 0)) {
			pianoCacheModel.desc = null;
		}

		pianoCacheModel.data_ins = getData_ins();

		String data_ins = pianoCacheModel.data_ins;

		if ((data_ins != null) && (data_ins.length() == 0)) {
			pianoCacheModel.data_ins = null;
		}

		pianoCacheModel.data_agg = getData_agg();

		String data_agg = pianoCacheModel.data_agg;

		if ((data_agg != null) && (data_agg.length() == 0)) {
			pianoCacheModel.data_agg = null;
		}

		pianoCacheModel.user_ins = getUser_ins();

		String user_ins = pianoCacheModel.user_ins;

		if ((user_ins != null) && (user_ins.length() == 0)) {
			pianoCacheModel.user_ins = null;
		}

		pianoCacheModel.user_agg = getUser_agg();

		String user_agg = pianoCacheModel.user_agg;

		if ((user_agg != null) && (user_agg.length() == 0)) {
			pianoCacheModel.user_agg = null;
		}

		return pianoCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Piano, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Piano, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Piano, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Piano)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Piano, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Piano, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Piano, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Piano)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static final Function<InvocationHandler, Piano>
		_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	private long _id_pk_piano;
	private long _id_piano;
	private long _id_sede;
	private String _cod_piano;
	private String _desc;
	private String _data_ins;
	private String _data_agg;
	private String _user_ins;
	private String _user_agg;
	private Piano _escapedModel;

}