/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.prenotazione.aule.servizi.mef.service.base;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.service.BaseServiceImpl;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import servizio.prenotazione.aule.servizi.mef.model.ServLog;
import servizio.prenotazione.aule.servizi.mef.service.ServLogService;
import servizio.prenotazione.aule.servizi.mef.service.persistence.ServLogPersistence;
import servizio.prenotazione.aule.servizi.mef.service.persistence.StrumEventoPersistence;
import servizio.prenotazione.aule.servizi.mef.service.persistence.StrumTecPersistence;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the serv log remote service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link servizio.prenotazione.aule.servizi.mef.service.impl.ServLogServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see servizio.prenotazione.aule.servizi.mef.service.impl.ServLogServiceImpl
 * @see servizio.prenotazione.aule.servizi.mef.service.ServLogServiceUtil
 * @generated
 */
public abstract class ServLogServiceBaseImpl extends BaseServiceImpl
	implements ServLogService, IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link servizio.prenotazione.aule.servizi.mef.service.ServLogServiceUtil} to access the serv log remote service.
	 */

	/**
	 * Returns the serv log local service.
	 *
	 * @return the serv log local service
	 */
	public servizio.prenotazione.aule.servizi.mef.service.ServLogLocalService getServLogLocalService() {
		return servLogLocalService;
	}

	/**
	 * Sets the serv log local service.
	 *
	 * @param servLogLocalService the serv log local service
	 */
	public void setServLogLocalService(
		servizio.prenotazione.aule.servizi.mef.service.ServLogLocalService servLogLocalService) {
		this.servLogLocalService = servLogLocalService;
	}

	/**
	 * Returns the serv log remote service.
	 *
	 * @return the serv log remote service
	 */
	public ServLogService getServLogService() {
		return servLogService;
	}

	/**
	 * Sets the serv log remote service.
	 *
	 * @param servLogService the serv log remote service
	 */
	public void setServLogService(ServLogService servLogService) {
		this.servLogService = servLogService;
	}

	/**
	 * Returns the serv log persistence.
	 *
	 * @return the serv log persistence
	 */
	public ServLogPersistence getServLogPersistence() {
		return servLogPersistence;
	}

	/**
	 * Sets the serv log persistence.
	 *
	 * @param servLogPersistence the serv log persistence
	 */
	public void setServLogPersistence(ServLogPersistence servLogPersistence) {
		this.servLogPersistence = servLogPersistence;
	}

	/**
	 * Returns the strum evento local service.
	 *
	 * @return the strum evento local service
	 */
	public servizio.prenotazione.aule.servizi.mef.service.StrumEventoLocalService getStrumEventoLocalService() {
		return strumEventoLocalService;
	}

	/**
	 * Sets the strum evento local service.
	 *
	 * @param strumEventoLocalService the strum evento local service
	 */
	public void setStrumEventoLocalService(
		servizio.prenotazione.aule.servizi.mef.service.StrumEventoLocalService strumEventoLocalService) {
		this.strumEventoLocalService = strumEventoLocalService;
	}

	/**
	 * Returns the strum evento remote service.
	 *
	 * @return the strum evento remote service
	 */
	public servizio.prenotazione.aule.servizi.mef.service.StrumEventoService getStrumEventoService() {
		return strumEventoService;
	}

	/**
	 * Sets the strum evento remote service.
	 *
	 * @param strumEventoService the strum evento remote service
	 */
	public void setStrumEventoService(
		servizio.prenotazione.aule.servizi.mef.service.StrumEventoService strumEventoService) {
		this.strumEventoService = strumEventoService;
	}

	/**
	 * Returns the strum evento persistence.
	 *
	 * @return the strum evento persistence
	 */
	public StrumEventoPersistence getStrumEventoPersistence() {
		return strumEventoPersistence;
	}

	/**
	 * Sets the strum evento persistence.
	 *
	 * @param strumEventoPersistence the strum evento persistence
	 */
	public void setStrumEventoPersistence(
		StrumEventoPersistence strumEventoPersistence) {
		this.strumEventoPersistence = strumEventoPersistence;
	}

	/**
	 * Returns the strum tec local service.
	 *
	 * @return the strum tec local service
	 */
	public servizio.prenotazione.aule.servizi.mef.service.StrumTecLocalService getStrumTecLocalService() {
		return strumTecLocalService;
	}

	/**
	 * Sets the strum tec local service.
	 *
	 * @param strumTecLocalService the strum tec local service
	 */
	public void setStrumTecLocalService(
		servizio.prenotazione.aule.servizi.mef.service.StrumTecLocalService strumTecLocalService) {
		this.strumTecLocalService = strumTecLocalService;
	}

	/**
	 * Returns the strum tec remote service.
	 *
	 * @return the strum tec remote service
	 */
	public servizio.prenotazione.aule.servizi.mef.service.StrumTecService getStrumTecService() {
		return strumTecService;
	}

	/**
	 * Sets the strum tec remote service.
	 *
	 * @param strumTecService the strum tec remote service
	 */
	public void setStrumTecService(
		servizio.prenotazione.aule.servizi.mef.service.StrumTecService strumTecService) {
		this.strumTecService = strumTecService;
	}

	/**
	 * Returns the strum tec persistence.
	 *
	 * @return the strum tec persistence
	 */
	public StrumTecPersistence getStrumTecPersistence() {
		return strumTecPersistence;
	}

	/**
	 * Sets the strum tec persistence.
	 *
	 * @param strumTecPersistence the strum tec persistence
	 */
	public void setStrumTecPersistence(StrumTecPersistence strumTecPersistence) {
		this.strumTecPersistence = strumTecPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name remote service.
	 *
	 * @return the class name remote service
	 */
	public com.liferay.portal.kernel.service.ClassNameService getClassNameService() {
		return classNameService;
	}

	/**
	 * Sets the class name remote service.
	 *
	 * @param classNameService the class name remote service
	 */
	public void setClassNameService(
		com.liferay.portal.kernel.service.ClassNameService classNameService) {
		this.classNameService = classNameService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user remote service.
	 *
	 * @return the user remote service
	 */
	public com.liferay.portal.kernel.service.UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(
		com.liferay.portal.kernel.service.UserService userService) {
		this.userService = userService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
	}

	public void destroy() {
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ServLogService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ServLog.class;
	}

	protected String getModelClassName() {
		return ServLog.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = servLogPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = servizio.prenotazione.aule.servizi.mef.service.ServLogLocalService.class)
	protected servizio.prenotazione.aule.servizi.mef.service.ServLogLocalService servLogLocalService;
	@BeanReference(type = ServLogService.class)
	protected ServLogService servLogService;
	@BeanReference(type = ServLogPersistence.class)
	protected ServLogPersistence servLogPersistence;
	@BeanReference(type = servizio.prenotazione.aule.servizi.mef.service.StrumEventoLocalService.class)
	protected servizio.prenotazione.aule.servizi.mef.service.StrumEventoLocalService strumEventoLocalService;
	@BeanReference(type = servizio.prenotazione.aule.servizi.mef.service.StrumEventoService.class)
	protected servizio.prenotazione.aule.servizi.mef.service.StrumEventoService strumEventoService;
	@BeanReference(type = StrumEventoPersistence.class)
	protected StrumEventoPersistence strumEventoPersistence;
	@BeanReference(type = servizio.prenotazione.aule.servizi.mef.service.StrumTecLocalService.class)
	protected servizio.prenotazione.aule.servizi.mef.service.StrumTecLocalService strumTecLocalService;
	@BeanReference(type = servizio.prenotazione.aule.servizi.mef.service.StrumTecService.class)
	protected servizio.prenotazione.aule.servizi.mef.service.StrumTecService strumTecService;
	@BeanReference(type = StrumTecPersistence.class)
	protected StrumTecPersistence strumTecPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameService.class)
	protected com.liferay.portal.kernel.service.ClassNameService classNameService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserService.class)
	protected com.liferay.portal.kernel.service.UserService userService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}