/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.prenotazione.aule.servizi.mef.service.base;

import aQute.bnd.annotation.ProviderType;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import servizio.prenotazione.aule.servizi.mef.model.StrumEvento;
import servizio.prenotazione.aule.servizi.mef.service.StrumEventoLocalService;
import servizio.prenotazione.aule.servizi.mef.service.persistence.ServLogPersistence;
import servizio.prenotazione.aule.servizi.mef.service.persistence.StrumEventoPK;
import servizio.prenotazione.aule.servizi.mef.service.persistence.StrumEventoPersistence;
import servizio.prenotazione.aule.servizi.mef.service.persistence.StrumTecPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the strum evento local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link servizio.prenotazione.aule.servizi.mef.service.impl.StrumEventoLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see servizio.prenotazione.aule.servizi.mef.service.impl.StrumEventoLocalServiceImpl
 * @see servizio.prenotazione.aule.servizi.mef.service.StrumEventoLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class StrumEventoLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements StrumEventoLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link servizio.prenotazione.aule.servizi.mef.service.StrumEventoLocalServiceUtil} to access the strum evento local service.
	 */

	/**
	 * Adds the strum evento to the database. Also notifies the appropriate model listeners.
	 *
	 * @param strumEvento the strum evento
	 * @return the strum evento that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public StrumEvento addStrumEvento(StrumEvento strumEvento) {
		strumEvento.setNew(true);

		return strumEventoPersistence.update(strumEvento);
	}

	/**
	 * Creates a new strum evento with the primary key. Does not add the strum evento to the database.
	 *
	 * @param strumEventoPK the primary key for the new strum evento
	 * @return the new strum evento
	 */
	@Override
	public StrumEvento createStrumEvento(StrumEventoPK strumEventoPK) {
		return strumEventoPersistence.create(strumEventoPK);
	}

	/**
	 * Deletes the strum evento with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param strumEventoPK the primary key of the strum evento
	 * @return the strum evento that was removed
	 * @throws PortalException if a strum evento with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public StrumEvento deleteStrumEvento(StrumEventoPK strumEventoPK)
		throws PortalException {
		return strumEventoPersistence.remove(strumEventoPK);
	}

	/**
	 * Deletes the strum evento from the database. Also notifies the appropriate model listeners.
	 *
	 * @param strumEvento the strum evento
	 * @return the strum evento that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public StrumEvento deleteStrumEvento(StrumEvento strumEvento) {
		return strumEventoPersistence.remove(strumEvento);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(StrumEvento.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return strumEventoPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link servizio.prenotazione.aule.servizi.mef.model.impl.StrumEventoModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return strumEventoPersistence.findWithDynamicQuery(dynamicQuery, start,
			end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link servizio.prenotazione.aule.servizi.mef.model.impl.StrumEventoModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return strumEventoPersistence.findWithDynamicQuery(dynamicQuery, start,
			end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return strumEventoPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return strumEventoPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public StrumEvento fetchStrumEvento(StrumEventoPK strumEventoPK) {
		return strumEventoPersistence.fetchByPrimaryKey(strumEventoPK);
	}

	/**
	 * Returns the strum evento with the primary key.
	 *
	 * @param strumEventoPK the primary key of the strum evento
	 * @return the strum evento
	 * @throws PortalException if a strum evento with the primary key could not be found
	 */
	@Override
	public StrumEvento getStrumEvento(StrumEventoPK strumEventoPK)
		throws PortalException {
		return strumEventoPersistence.findByPrimaryKey(strumEventoPK);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(strumEventoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(StrumEvento.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("primaryKey.id_strum");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(strumEventoLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(StrumEvento.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"primaryKey.id_strum");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(strumEventoLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(StrumEvento.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("primaryKey.id_strum");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return strumEventoLocalService.deleteStrumEvento((StrumEvento)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return strumEventoPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the strum eventos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link servizio.prenotazione.aule.servizi.mef.model.impl.StrumEventoModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of strum eventos
	 * @param end the upper bound of the range of strum eventos (not inclusive)
	 * @return the range of strum eventos
	 */
	@Override
	public List<StrumEvento> getStrumEventos(int start, int end) {
		return strumEventoPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of strum eventos.
	 *
	 * @return the number of strum eventos
	 */
	@Override
	public int getStrumEventosCount() {
		return strumEventoPersistence.countAll();
	}

	/**
	 * Updates the strum evento in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param strumEvento the strum evento
	 * @return the strum evento that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public StrumEvento updateStrumEvento(StrumEvento strumEvento) {
		return strumEventoPersistence.update(strumEvento);
	}

	/**
	 * Returns the serv log local service.
	 *
	 * @return the serv log local service
	 */
	public servizio.prenotazione.aule.servizi.mef.service.ServLogLocalService getServLogLocalService() {
		return servLogLocalService;
	}

	/**
	 * Sets the serv log local service.
	 *
	 * @param servLogLocalService the serv log local service
	 */
	public void setServLogLocalService(
		servizio.prenotazione.aule.servizi.mef.service.ServLogLocalService servLogLocalService) {
		this.servLogLocalService = servLogLocalService;
	}

	/**
	 * Returns the serv log persistence.
	 *
	 * @return the serv log persistence
	 */
	public ServLogPersistence getServLogPersistence() {
		return servLogPersistence;
	}

	/**
	 * Sets the serv log persistence.
	 *
	 * @param servLogPersistence the serv log persistence
	 */
	public void setServLogPersistence(ServLogPersistence servLogPersistence) {
		this.servLogPersistence = servLogPersistence;
	}

	/**
	 * Returns the strum evento local service.
	 *
	 * @return the strum evento local service
	 */
	public StrumEventoLocalService getStrumEventoLocalService() {
		return strumEventoLocalService;
	}

	/**
	 * Sets the strum evento local service.
	 *
	 * @param strumEventoLocalService the strum evento local service
	 */
	public void setStrumEventoLocalService(
		StrumEventoLocalService strumEventoLocalService) {
		this.strumEventoLocalService = strumEventoLocalService;
	}

	/**
	 * Returns the strum evento persistence.
	 *
	 * @return the strum evento persistence
	 */
	public StrumEventoPersistence getStrumEventoPersistence() {
		return strumEventoPersistence;
	}

	/**
	 * Sets the strum evento persistence.
	 *
	 * @param strumEventoPersistence the strum evento persistence
	 */
	public void setStrumEventoPersistence(
		StrumEventoPersistence strumEventoPersistence) {
		this.strumEventoPersistence = strumEventoPersistence;
	}

	/**
	 * Returns the strum tec local service.
	 *
	 * @return the strum tec local service
	 */
	public servizio.prenotazione.aule.servizi.mef.service.StrumTecLocalService getStrumTecLocalService() {
		return strumTecLocalService;
	}

	/**
	 * Sets the strum tec local service.
	 *
	 * @param strumTecLocalService the strum tec local service
	 */
	public void setStrumTecLocalService(
		servizio.prenotazione.aule.servizi.mef.service.StrumTecLocalService strumTecLocalService) {
		this.strumTecLocalService = strumTecLocalService;
	}

	/**
	 * Returns the strum tec persistence.
	 *
	 * @return the strum tec persistence
	 */
	public StrumTecPersistence getStrumTecPersistence() {
		return strumTecPersistence;
	}

	/**
	 * Sets the strum tec persistence.
	 *
	 * @param strumTecPersistence the strum tec persistence
	 */
	public void setStrumTecPersistence(StrumTecPersistence strumTecPersistence) {
		this.strumTecPersistence = strumTecPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("servizio.prenotazione.aule.servizi.mef.model.StrumEvento",
			strumEventoLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"servizio.prenotazione.aule.servizi.mef.model.StrumEvento");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return StrumEventoLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return StrumEvento.class;
	}

	protected String getModelClassName() {
		return StrumEvento.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = strumEventoPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = servizio.prenotazione.aule.servizi.mef.service.ServLogLocalService.class)
	protected servizio.prenotazione.aule.servizi.mef.service.ServLogLocalService servLogLocalService;
	@BeanReference(type = ServLogPersistence.class)
	protected ServLogPersistence servLogPersistence;
	@BeanReference(type = StrumEventoLocalService.class)
	protected StrumEventoLocalService strumEventoLocalService;
	@BeanReference(type = StrumEventoPersistence.class)
	protected StrumEventoPersistence strumEventoPersistence;
	@BeanReference(type = servizio.prenotazione.aule.servizi.mef.service.StrumTecLocalService.class)
	protected servizio.prenotazione.aule.servizi.mef.service.StrumTecLocalService strumTecLocalService;
	@BeanReference(type = StrumTecPersistence.class)
	protected StrumTecPersistence strumTecPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}