/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.accenture.istanza.interpello.service.base;

import aQute.bnd.annotation.ProviderType;

import com.accenture.istanza.interpello.model.RichInterpello;
import com.accenture.istanza.interpello.service.RichInterpelloLocalService;
import com.accenture.istanza.interpello.service.persistence.EmailPersistence;
import com.accenture.istanza.interpello.service.persistence.RichInterpelloFinder;
import com.accenture.istanza.interpello.service.persistence.RichInterpelloPersistence;
import com.accenture.istanza.interpello.service.persistence.TextRichPersistence;

import com.liferay.portal.kernel.bean.BeanReference;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalServiceRegistry;
import com.liferay.portal.kernel.service.persistence.ClassNamePersistence;
import com.liferay.portal.kernel.service.persistence.UserPersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.spring.extender.service.ServiceReference;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

/**
 * Provides the base implementation for the rich interpello local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.accenture.istanza.interpello.service.impl.RichInterpelloLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.accenture.istanza.interpello.service.impl.RichInterpelloLocalServiceImpl
 * @see com.accenture.istanza.interpello.service.RichInterpelloLocalServiceUtil
 * @generated
 */
@ProviderType
public abstract class RichInterpelloLocalServiceBaseImpl
	extends BaseLocalServiceImpl implements RichInterpelloLocalService,
		IdentifiableOSGiService {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Always use {@link com.accenture.istanza.interpello.service.RichInterpelloLocalServiceUtil} to access the rich interpello local service.
	 */

	/**
	 * Adds the rich interpello to the database. Also notifies the appropriate model listeners.
	 *
	 * @param richInterpello the rich interpello
	 * @return the rich interpello that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RichInterpello addRichInterpello(RichInterpello richInterpello) {
		richInterpello.setNew(true);

		return richInterpelloPersistence.update(richInterpello);
	}

	/**
	 * Creates a new rich interpello with the primary key. Does not add the rich interpello to the database.
	 *
	 * @param id the primary key for the new rich interpello
	 * @return the new rich interpello
	 */
	@Override
	@Transactional(enabled = false)
	public RichInterpello createRichInterpello(long id) {
		return richInterpelloPersistence.create(id);
	}

	/**
	 * Deletes the rich interpello with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param id the primary key of the rich interpello
	 * @return the rich interpello that was removed
	 * @throws PortalException if a rich interpello with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RichInterpello deleteRichInterpello(long id)
		throws PortalException {
		return richInterpelloPersistence.remove(id);
	}

	/**
	 * Deletes the rich interpello from the database. Also notifies the appropriate model listeners.
	 *
	 * @param richInterpello the rich interpello
	 * @return the rich interpello that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public RichInterpello deleteRichInterpello(RichInterpello richInterpello) {
		return richInterpelloPersistence.remove(richInterpello);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(RichInterpello.class,
			clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return richInterpelloPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.accenture.istanza.interpello.model.impl.RichInterpelloModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end) {
		return richInterpelloPersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.accenture.istanza.interpello.model.impl.RichInterpelloModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery, int start,
		int end, OrderByComparator<T> orderByComparator) {
		return richInterpelloPersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return richInterpelloPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery,
		Projection projection) {
		return richInterpelloPersistence.countWithDynamicQuery(dynamicQuery,
			projection);
	}

	@Override
	public RichInterpello fetchRichInterpello(long id) {
		return richInterpelloPersistence.fetchByPrimaryKey(id);
	}

	/**
	 * Returns the rich interpello with the primary key.
	 *
	 * @param id the primary key of the rich interpello
	 * @return the rich interpello
	 * @throws PortalException if a rich interpello with the primary key could not be found
	 */
	@Override
	public RichInterpello getRichInterpello(long id) throws PortalException {
		return richInterpelloPersistence.findByPrimaryKey(id);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery = new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(richInterpelloLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RichInterpello.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery getIndexableActionableDynamicQuery() {
		IndexableActionableDynamicQuery indexableActionableDynamicQuery = new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(richInterpelloLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(RichInterpello.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("id");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {
		actionableDynamicQuery.setBaseLocalService(richInterpelloLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(RichInterpello.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("id");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {
		return richInterpelloLocalService.deleteRichInterpello((RichInterpello)persistedModel);
	}

	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {
		return richInterpelloPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the rich interpellos.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent and pagination is required (<code>start</code> and <code>end</code> are not {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS}), then the query will include the default ORDER BY logic from {@link com.accenture.istanza.interpello.model.impl.RichInterpelloModelImpl}. If both <code>orderByComparator</code> and pagination are absent, for performance reasons, the query will not have an ORDER BY clause and the returned result set will be sorted on by the primary key in an ascending order.
	 * </p>
	 *
	 * @param start the lower bound of the range of rich interpellos
	 * @param end the upper bound of the range of rich interpellos (not inclusive)
	 * @return the range of rich interpellos
	 */
	@Override
	public List<RichInterpello> getRichInterpellos(int start, int end) {
		return richInterpelloPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of rich interpellos.
	 *
	 * @return the number of rich interpellos
	 */
	@Override
	public int getRichInterpellosCount() {
		return richInterpelloPersistence.countAll();
	}

	/**
	 * Updates the rich interpello in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param richInterpello the rich interpello
	 * @return the rich interpello that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public RichInterpello updateRichInterpello(RichInterpello richInterpello) {
		return richInterpelloPersistence.update(richInterpello);
	}

	/**
	 * Returns the email local service.
	 *
	 * @return the email local service
	 */
	public com.accenture.istanza.interpello.service.EmailLocalService getEmailLocalService() {
		return emailLocalService;
	}

	/**
	 * Sets the email local service.
	 *
	 * @param emailLocalService the email local service
	 */
	public void setEmailLocalService(
		com.accenture.istanza.interpello.service.EmailLocalService emailLocalService) {
		this.emailLocalService = emailLocalService;
	}

	/**
	 * Returns the email persistence.
	 *
	 * @return the email persistence
	 */
	public EmailPersistence getEmailPersistence() {
		return emailPersistence;
	}

	/**
	 * Sets the email persistence.
	 *
	 * @param emailPersistence the email persistence
	 */
	public void setEmailPersistence(EmailPersistence emailPersistence) {
		this.emailPersistence = emailPersistence;
	}

	/**
	 * Returns the rich interpello local service.
	 *
	 * @return the rich interpello local service
	 */
	public RichInterpelloLocalService getRichInterpelloLocalService() {
		return richInterpelloLocalService;
	}

	/**
	 * Sets the rich interpello local service.
	 *
	 * @param richInterpelloLocalService the rich interpello local service
	 */
	public void setRichInterpelloLocalService(
		RichInterpelloLocalService richInterpelloLocalService) {
		this.richInterpelloLocalService = richInterpelloLocalService;
	}

	/**
	 * Returns the rich interpello persistence.
	 *
	 * @return the rich interpello persistence
	 */
	public RichInterpelloPersistence getRichInterpelloPersistence() {
		return richInterpelloPersistence;
	}

	/**
	 * Sets the rich interpello persistence.
	 *
	 * @param richInterpelloPersistence the rich interpello persistence
	 */
	public void setRichInterpelloPersistence(
		RichInterpelloPersistence richInterpelloPersistence) {
		this.richInterpelloPersistence = richInterpelloPersistence;
	}

	/**
	 * Returns the rich interpello finder.
	 *
	 * @return the rich interpello finder
	 */
	public RichInterpelloFinder getRichInterpelloFinder() {
		return richInterpelloFinder;
	}

	/**
	 * Sets the rich interpello finder.
	 *
	 * @param richInterpelloFinder the rich interpello finder
	 */
	public void setRichInterpelloFinder(
		RichInterpelloFinder richInterpelloFinder) {
		this.richInterpelloFinder = richInterpelloFinder;
	}

	/**
	 * Returns the text rich local service.
	 *
	 * @return the text rich local service
	 */
	public com.accenture.istanza.interpello.service.TextRichLocalService getTextRichLocalService() {
		return textRichLocalService;
	}

	/**
	 * Sets the text rich local service.
	 *
	 * @param textRichLocalService the text rich local service
	 */
	public void setTextRichLocalService(
		com.accenture.istanza.interpello.service.TextRichLocalService textRichLocalService) {
		this.textRichLocalService = textRichLocalService;
	}

	/**
	 * Returns the text rich persistence.
	 *
	 * @return the text rich persistence
	 */
	public TextRichPersistence getTextRichPersistence() {
		return textRichPersistence;
	}

	/**
	 * Sets the text rich persistence.
	 *
	 * @param textRichPersistence the text rich persistence
	 */
	public void setTextRichPersistence(TextRichPersistence textRichPersistence) {
		this.textRichPersistence = textRichPersistence;
	}

	/**
	 * Returns the counter local service.
	 *
	 * @return the counter local service
	 */
	public com.liferay.counter.kernel.service.CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(
		com.liferay.counter.kernel.service.CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Returns the class name local service.
	 *
	 * @return the class name local service
	 */
	public com.liferay.portal.kernel.service.ClassNameLocalService getClassNameLocalService() {
		return classNameLocalService;
	}

	/**
	 * Sets the class name local service.
	 *
	 * @param classNameLocalService the class name local service
	 */
	public void setClassNameLocalService(
		com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService) {
		this.classNameLocalService = classNameLocalService;
	}

	/**
	 * Returns the class name persistence.
	 *
	 * @return the class name persistence
	 */
	public ClassNamePersistence getClassNamePersistence() {
		return classNamePersistence;
	}

	/**
	 * Sets the class name persistence.
	 *
	 * @param classNamePersistence the class name persistence
	 */
	public void setClassNamePersistence(
		ClassNamePersistence classNamePersistence) {
		this.classNamePersistence = classNamePersistence;
	}

	/**
	 * Returns the resource local service.
	 *
	 * @return the resource local service
	 */
	public com.liferay.portal.kernel.service.ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Returns the user local service.
	 *
	 * @return the user local service
	 */
	public com.liferay.portal.kernel.service.UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(
		com.liferay.portal.kernel.service.UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Returns the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	public void afterPropertiesSet() {
		persistedModelLocalServiceRegistry.register("com.accenture.istanza.interpello.model.RichInterpello",
			richInterpelloLocalService);
	}

	public void destroy() {
		persistedModelLocalServiceRegistry.unregister(
			"com.accenture.istanza.interpello.model.RichInterpello");
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return RichInterpelloLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return RichInterpello.class;
	}

	protected String getModelClassName() {
		return RichInterpello.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = richInterpelloPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = com.accenture.istanza.interpello.service.EmailLocalService.class)
	protected com.accenture.istanza.interpello.service.EmailLocalService emailLocalService;
	@BeanReference(type = EmailPersistence.class)
	protected EmailPersistence emailPersistence;
	@BeanReference(type = RichInterpelloLocalService.class)
	protected RichInterpelloLocalService richInterpelloLocalService;
	@BeanReference(type = RichInterpelloPersistence.class)
	protected RichInterpelloPersistence richInterpelloPersistence;
	@BeanReference(type = RichInterpelloFinder.class)
	protected RichInterpelloFinder richInterpelloFinder;
	@BeanReference(type = com.accenture.istanza.interpello.service.TextRichLocalService.class)
	protected com.accenture.istanza.interpello.service.TextRichLocalService textRichLocalService;
	@BeanReference(type = TextRichPersistence.class)
	protected TextRichPersistence textRichPersistence;
	@ServiceReference(type = com.liferay.counter.kernel.service.CounterLocalService.class)
	protected com.liferay.counter.kernel.service.CounterLocalService counterLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.ClassNameLocalService.class)
	protected com.liferay.portal.kernel.service.ClassNameLocalService classNameLocalService;
	@ServiceReference(type = ClassNamePersistence.class)
	protected ClassNamePersistence classNamePersistence;
	@ServiceReference(type = com.liferay.portal.kernel.service.ResourceLocalService.class)
	protected com.liferay.portal.kernel.service.ResourceLocalService resourceLocalService;
	@ServiceReference(type = com.liferay.portal.kernel.service.UserLocalService.class)
	protected com.liferay.portal.kernel.service.UserLocalService userLocalService;
	@ServiceReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
	@ServiceReference(type = PersistedModelLocalServiceRegistry.class)
	protected PersistedModelLocalServiceRegistry persistedModelLocalServiceRegistry;
}