/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.gestione.riunioni.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.intranet.mef.gestione.riunioni.model.Luogo;
import com.intranet.mef.gestione.riunioni.model.LuogoModel;
import com.intranet.mef.gestione.riunioni.model.LuogoSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the Luogo service. Represents a row in the &quot;MEF_Luogo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link LuogoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link LuogoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see LuogoImpl
 * @see Luogo
 * @see LuogoModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class LuogoModelImpl extends BaseModelImpl<Luogo> implements LuogoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a luogo model instance should use the {@link Luogo} interface instead.
	 */
	public static final String TABLE_NAME = "MEF_Luogo";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_luogo", Types.BIGINT },
			{ "nome", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_luogo", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nome", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MEF_Luogo (id_luogo LONG not null primary key,nome VARCHAR(250) null)";
	public static final String TABLE_SQL_DROP = "drop table MEF_Luogo";
	public static final String ORDER_BY_JPQL = " ORDER BY luogo.id_luogo ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MEF_Luogo.id_luogo ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.intranet.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.intranet.mef.gestione.riunioni.model.Luogo"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.intranet.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.intranet.mef.gestione.riunioni.model.Luogo"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Luogo toModel(LuogoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Luogo model = new LuogoImpl();

		model.setId_luogo(soapModel.getId_luogo());
		model.setNome(soapModel.getNome());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Luogo> toModels(LuogoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Luogo> models = new ArrayList<Luogo>(soapModels.length);

		for (LuogoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.intranet.mef.service.util.PropsUtil.get(
				"lock.expiration.time.com.intranet.mef.gestione.riunioni.model.Luogo"));

	public LuogoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_luogo;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_luogo(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_luogo;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Luogo.class;
	}

	@Override
	public String getModelClassName() {
		return Luogo.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_luogo", getId_luogo());
		attributes.put("nome", getNome());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_luogo = (Long)attributes.get("id_luogo");

		if (id_luogo != null) {
			setId_luogo(id_luogo);
		}

		String nome = (String)attributes.get("nome");

		if (nome != null) {
			setNome(nome);
		}
	}

	@JSON
	@Override
	public long getId_luogo() {
		return _id_luogo;
	}

	@Override
	public void setId_luogo(long id_luogo) {
		_id_luogo = id_luogo;
	}

	@JSON
	@Override
	public String getNome() {
		if (_nome == null) {
			return StringPool.BLANK;
		}
		else {
			return _nome;
		}
	}

	@Override
	public void setNome(String nome) {
		_nome = nome;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			Luogo.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Luogo toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (Luogo)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		LuogoImpl luogoImpl = new LuogoImpl();

		luogoImpl.setId_luogo(getId_luogo());
		luogoImpl.setNome(getNome());

		luogoImpl.resetOriginalValues();

		return luogoImpl;
	}

	@Override
	public int compareTo(Luogo luogo) {
		long primaryKey = luogo.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Luogo)) {
			return false;
		}

		Luogo luogo = (Luogo)obj;

		long primaryKey = luogo.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<Luogo> toCacheModel() {
		LuogoCacheModel luogoCacheModel = new LuogoCacheModel();

		luogoCacheModel.id_luogo = getId_luogo();

		luogoCacheModel.nome = getNome();

		String nome = luogoCacheModel.nome;

		if ((nome != null) && (nome.length() == 0)) {
			luogoCacheModel.nome = null;
		}

		return luogoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id_luogo=");
		sb.append(getId_luogo());
		sb.append(", nome=");
		sb.append(getNome());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.intranet.mef.gestione.riunioni.model.Luogo");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_luogo</column-name><column-value><![CDATA[");
		sb.append(getId_luogo());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nome</column-name><column-value><![CDATA[");
		sb.append(getNome());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = Luogo.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			Luogo.class
		};
	private long _id_luogo;
	private String _nome;
	private Luogo _escapedModel;
}