/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.gestione.riunioni.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.intranet.mef.gestione.riunioni.model.StatoInvitato;
import com.intranet.mef.gestione.riunioni.model.StatoInvitatoModel;
import com.intranet.mef.gestione.riunioni.model.StatoInvitatoSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the StatoInvitato service. Represents a row in the &quot;MEF_StatoInvitato&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link StatoInvitatoModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link StatoInvitatoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StatoInvitatoImpl
 * @see StatoInvitato
 * @see StatoInvitatoModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class StatoInvitatoModelImpl extends BaseModelImpl<StatoInvitato>
	implements StatoInvitatoModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a stato invitato model instance should use the {@link StatoInvitato} interface instead.
	 */
	public static final String TABLE_NAME = "MEF_StatoInvitato";
	public static final Object[][] TABLE_COLUMNS = {
			{ "id_stato_invitato", Types.BIGINT },
			{ "nome_stato", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("id_stato_invitato", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nome_stato", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table MEF_StatoInvitato (id_stato_invitato LONG not null primary key,nome_stato VARCHAR(50) null)";
	public static final String TABLE_SQL_DROP = "drop table MEF_StatoInvitato";
	public static final String ORDER_BY_JPQL = " ORDER BY statoInvitato.id_stato_invitato ASC";
	public static final String ORDER_BY_SQL = " ORDER BY MEF_StatoInvitato.id_stato_invitato ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.intranet.mef.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.intranet.mef.gestione.riunioni.model.StatoInvitato"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.intranet.mef.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.intranet.mef.gestione.riunioni.model.StatoInvitato"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static StatoInvitato toModel(StatoInvitatoSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		StatoInvitato model = new StatoInvitatoImpl();

		model.setId_stato_invitato(soapModel.getId_stato_invitato());
		model.setNome_stato(soapModel.getNome_stato());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<StatoInvitato> toModels(StatoInvitatoSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<StatoInvitato> models = new ArrayList<StatoInvitato>(soapModels.length);

		for (StatoInvitatoSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.intranet.mef.service.util.PropsUtil.get(
				"lock.expiration.time.com.intranet.mef.gestione.riunioni.model.StatoInvitato"));

	public StatoInvitatoModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _id_stato_invitato;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_stato_invitato(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _id_stato_invitato;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return StatoInvitato.class;
	}

	@Override
	public String getModelClassName() {
		return StatoInvitato.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("id_stato_invitato", getId_stato_invitato());
		attributes.put("nome_stato", getNome_stato());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long id_stato_invitato = (Long)attributes.get("id_stato_invitato");

		if (id_stato_invitato != null) {
			setId_stato_invitato(id_stato_invitato);
		}

		String nome_stato = (String)attributes.get("nome_stato");

		if (nome_stato != null) {
			setNome_stato(nome_stato);
		}
	}

	@JSON
	@Override
	public long getId_stato_invitato() {
		return _id_stato_invitato;
	}

	@Override
	public void setId_stato_invitato(long id_stato_invitato) {
		_id_stato_invitato = id_stato_invitato;
	}

	@JSON
	@Override
	public String getNome_stato() {
		if (_nome_stato == null) {
			return StringPool.BLANK;
		}
		else {
			return _nome_stato;
		}
	}

	@Override
	public void setNome_stato(String nome_stato) {
		_nome_stato = nome_stato;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			StatoInvitato.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public StatoInvitato toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (StatoInvitato)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		StatoInvitatoImpl statoInvitatoImpl = new StatoInvitatoImpl();

		statoInvitatoImpl.setId_stato_invitato(getId_stato_invitato());
		statoInvitatoImpl.setNome_stato(getNome_stato());

		statoInvitatoImpl.resetOriginalValues();

		return statoInvitatoImpl;
	}

	@Override
	public int compareTo(StatoInvitato statoInvitato) {
		long primaryKey = statoInvitato.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof StatoInvitato)) {
			return false;
		}

		StatoInvitato statoInvitato = (StatoInvitato)obj;

		long primaryKey = statoInvitato.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<StatoInvitato> toCacheModel() {
		StatoInvitatoCacheModel statoInvitatoCacheModel = new StatoInvitatoCacheModel();

		statoInvitatoCacheModel.id_stato_invitato = getId_stato_invitato();

		statoInvitatoCacheModel.nome_stato = getNome_stato();

		String nome_stato = statoInvitatoCacheModel.nome_stato;

		if ((nome_stato != null) && (nome_stato.length() == 0)) {
			statoInvitatoCacheModel.nome_stato = null;
		}

		return statoInvitatoCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{id_stato_invitato=");
		sb.append(getId_stato_invitato());
		sb.append(", nome_stato=");
		sb.append(getNome_stato());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.intranet.mef.gestione.riunioni.model.StatoInvitato");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>id_stato_invitato</column-name><column-value><![CDATA[");
		sb.append(getId_stato_invitato());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nome_stato</column-name><column-value><![CDATA[");
		sb.append(getNome_stato());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = StatoInvitato.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			StatoInvitato.class
		};
	private long _id_stato_invitato;
	private String _nome_stato;
	private StatoInvitato _escapedModel;
}