/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.accenture.istanza.interpello.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TextRich service. Represents a row in the &quot;MEFINTERPELLO_TextRich&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.accenture.istanza.interpello.model.impl.TextRichModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.accenture.istanza.interpello.model.impl.TextRichImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TextRich
 * @see com.accenture.istanza.interpello.model.impl.TextRichImpl
 * @see com.accenture.istanza.interpello.model.impl.TextRichModelImpl
 * @generated
 */
@ProviderType
public interface TextRichModel extends BaseModel<TextRich> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a text rich model instance should use the {@link TextRich} interface instead.
	 */

	/**
	 * Returns the primary key of this text rich.
	 *
	 * @return the primary key of this text rich
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this text rich.
	 *
	 * @param primaryKey the primary key of this text rich
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_text of this text rich.
	 *
	 * @return the id_text of this text rich
	 */
	public long getId_text();

	/**
	 * Sets the id_text of this text rich.
	 *
	 * @param id_text the id_text of this text rich
	 */
	public void setId_text(long id_text);

	/**
	 * Returns the label_text of this text rich.
	 *
	 * @return the label_text of this text rich
	 */
	@AutoEscape
	public String getLabel_text();

	/**
	 * Sets the label_text of this text rich.
	 *
	 * @param label_text the label_text of this text rich
	 */
	public void setLabel_text(String label_text);

	/**
	 * Returns the testo_text of this text rich.
	 *
	 * @return the testo_text of this text rich
	 */
	@AutoEscape
	public String getTesto_text();

	/**
	 * Sets the testo_text of this text rich.
	 *
	 * @param testo_text the testo_text of this text rich
	 */
	public void setTesto_text(String testo_text);

	/**
	 * Returns the data_in of this text rich.
	 *
	 * @return the data_in of this text rich
	 */
	public Date getData_in();

	/**
	 * Sets the data_in of this text rich.
	 *
	 * @param data_in the data_in of this text rich
	 */
	public void setData_in(Date data_in);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TextRich textRich);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TextRich> toCacheModel();

	@Override
	public TextRich toEscapedModel();

	@Override
	public TextRich toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}