/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.central.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.intranet.mef.central.model.CentralInvoker;
import com.intranet.mef.central.model.CentralInvokerModel;
import com.intranet.mef.central.model.CentralInvokerSoap;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the CentralInvoker service. Represents a row in the &quot;CentralInvoker_CentralInvoker&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link CentralInvokerModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CentralInvokerImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see CentralInvokerImpl
 * @see CentralInvoker
 * @see CentralInvokerModel
 * @generated
 */
@JSON(strict = true)
@ProviderType
public class CentralInvokerModelImpl extends BaseModelImpl<CentralInvoker>
	implements CentralInvokerModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a central invoker model instance should use the {@link CentralInvoker} interface instead.
	 */
	public static final String TABLE_NAME = "CentralInvoker_CentralInvoker";
	public static final Object[][] TABLE_COLUMNS = {
			{ "uuid_", Types.VARCHAR },
			{ "idRecord", Types.BIGINT },
			{ "secretaryId", Types.BIGINT }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("idRecord", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("secretaryId", Types.BIGINT);
	}

	public static final String TABLE_SQL_CREATE = "create table CentralInvoker_CentralInvoker (uuid_ VARCHAR(75) null,idRecord LONG not null primary key IDENTITY,secretaryId LONG)";
	public static final String TABLE_SQL_DROP = "drop table CentralInvoker_CentralInvoker";
	public static final String ORDER_BY_JPQL = " ORDER BY centralInvoker.idRecord ASC";
	public static final String ORDER_BY_SQL = " ORDER BY CentralInvoker_CentralInvoker.idRecord ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.intranet.mef.central.service.util.PropsUtil.get(
				"value.object.entity.cache.enabled.com.intranet.mef.central.model.CentralInvoker"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.intranet.mef.central.service.util.PropsUtil.get(
				"value.object.finder.cache.enabled.com.intranet.mef.central.model.CentralInvoker"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.intranet.mef.central.service.util.PropsUtil.get(
				"value.object.column.bitmask.enabled.com.intranet.mef.central.model.CentralInvoker"),
			true);
	public static final long UUID_COLUMN_BITMASK = 1L;
	public static final long IDRECORD_COLUMN_BITMASK = 2L;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static CentralInvoker toModel(CentralInvokerSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		CentralInvoker model = new CentralInvokerImpl();

		model.setUuid(soapModel.getUuid());
		model.setIdRecord(soapModel.getIdRecord());
		model.setSecretaryId(soapModel.getSecretaryId());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<CentralInvoker> toModels(CentralInvokerSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<CentralInvoker> models = new ArrayList<CentralInvoker>(soapModels.length);

		for (CentralInvokerSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.intranet.mef.central.service.util.PropsUtil.get(
				"lock.expiration.time.com.intranet.mef.central.model.CentralInvoker"));

	public CentralInvokerModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idRecord;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdRecord(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idRecord;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CentralInvoker.class;
	}

	@Override
	public String getModelClassName() {
		return CentralInvoker.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("uuid", getUuid());
		attributes.put("idRecord", getIdRecord());
		attributes.put("secretaryId", getSecretaryId());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		String uuid = (String)attributes.get("uuid");

		if (uuid != null) {
			setUuid(uuid);
		}

		Long idRecord = (Long)attributes.get("idRecord");

		if (idRecord != null) {
			setIdRecord(idRecord);
		}

		Long secretaryId = (Long)attributes.get("secretaryId");

		if (secretaryId != null) {
			setSecretaryId(secretaryId);
		}
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return StringPool.BLANK;
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getIdRecord() {
		return _idRecord;
	}

	@Override
	public void setIdRecord(long idRecord) {
		_idRecord = idRecord;
	}

	@JSON
	@Override
	public long getSecretaryId() {
		return _secretaryId;
	}

	@Override
	public void setSecretaryId(long secretaryId) {
		_secretaryId = secretaryId;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			CentralInvoker.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CentralInvoker toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CentralInvoker)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CentralInvokerImpl centralInvokerImpl = new CentralInvokerImpl();

		centralInvokerImpl.setUuid(getUuid());
		centralInvokerImpl.setIdRecord(getIdRecord());
		centralInvokerImpl.setSecretaryId(getSecretaryId());

		centralInvokerImpl.resetOriginalValues();

		return centralInvokerImpl;
	}

	@Override
	public int compareTo(CentralInvoker centralInvoker) {
		long primaryKey = centralInvoker.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CentralInvoker)) {
			return false;
		}

		CentralInvoker centralInvoker = (CentralInvoker)obj;

		long primaryKey = centralInvoker.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
		CentralInvokerModelImpl centralInvokerModelImpl = this;

		centralInvokerModelImpl._originalUuid = centralInvokerModelImpl._uuid;

		centralInvokerModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CentralInvoker> toCacheModel() {
		CentralInvokerCacheModel centralInvokerCacheModel = new CentralInvokerCacheModel();

		centralInvokerCacheModel.uuid = getUuid();

		String uuid = centralInvokerCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			centralInvokerCacheModel.uuid = null;
		}

		centralInvokerCacheModel.idRecord = getIdRecord();

		centralInvokerCacheModel.secretaryId = getSecretaryId();

		return centralInvokerCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{uuid=");
		sb.append(getUuid());
		sb.append(", idRecord=");
		sb.append(getIdRecord());
		sb.append(", secretaryId=");
		sb.append(getSecretaryId());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.intranet.mef.central.model.CentralInvoker");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>uuid</column-name><column-value><![CDATA[");
		sb.append(getUuid());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>idRecord</column-name><column-value><![CDATA[");
		sb.append(getIdRecord());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>secretaryId</column-name><column-value><![CDATA[");
		sb.append(getSecretaryId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = CentralInvoker.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			CentralInvoker.class
		};
	private String _uuid;
	private String _originalUuid;
	private long _idRecord;
	private long _secretaryId;
	private long _columnBitmask;
	private CentralInvoker _escapedModel;
}