/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.prenotazione.aule.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the SalaStruttura service. Represents a row in the &quot;MEFAULE_SalaStruttura&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servizio.prenotazione.aule.mef.model.impl.SalaStrutturaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servizio.prenotazione.aule.mef.model.impl.SalaStrutturaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see SalaStruttura
 * @see servizio.prenotazione.aule.mef.model.impl.SalaStrutturaImpl
 * @see servizio.prenotazione.aule.mef.model.impl.SalaStrutturaModelImpl
 * @generated
 */
@ProviderType
public interface SalaStrutturaModel extends BaseModel<SalaStruttura> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a sala struttura model instance should use the {@link SalaStruttura} interface instead.
	 */

	/**
	 * Returns the primary key of this sala struttura.
	 *
	 * @return the primary key of this sala struttura
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this sala struttura.
	 *
	 * @param primaryKey the primary key of this sala struttura
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this sala struttura.
	 *
	 * @return the ID of this sala struttura
	 */
	public long getId();

	/**
	 * Sets the ID of this sala struttura.
	 *
	 * @param id the ID of this sala struttura
	 */
	public void setId(long id);

	/**
	 * Returns the id_sala of this sala struttura.
	 *
	 * @return the id_sala of this sala struttura
	 */
	public long getId_sala();

	/**
	 * Sets the id_sala of this sala struttura.
	 *
	 * @param id_sala the id_sala of this sala struttura
	 */
	public void setId_sala(long id_sala);

	/**
	 * Returns the id_struttura of this sala struttura.
	 *
	 * @return the id_struttura of this sala struttura
	 */
	public long getId_struttura();

	/**
	 * Sets the id_struttura of this sala struttura.
	 *
	 * @param id_struttura the id_struttura of this sala struttura
	 */
	public void setId_struttura(long id_struttura);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		servizio.prenotazione.aule.mef.model.SalaStruttura salaStruttura);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servizio.prenotazione.aule.mef.model.SalaStruttura> toCacheModel();

	@Override
	public servizio.prenotazione.aule.mef.model.SalaStruttura toEscapedModel();

	@Override
	public servizio.prenotazione.aule.mef.model.SalaStruttura toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}