/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.prenotazione.aule.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the ServizioLog service. Represents a row in the &quot;MEFAULE_ServizioLog&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servizio.prenotazione.aule.mef.model.impl.ServizioLogModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servizio.prenotazione.aule.mef.model.impl.ServizioLogImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ServizioLog
 * @see servizio.prenotazione.aule.mef.model.impl.ServizioLogImpl
 * @see servizio.prenotazione.aule.mef.model.impl.ServizioLogModelImpl
 * @generated
 */
@ProviderType
public interface ServizioLogModel extends BaseModel<ServizioLog> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a servizio log model instance should use the {@link ServizioLog} interface instead.
	 */

	/**
	 * Returns the primary key of this servizio log.
	 *
	 * @return the primary key of this servizio log
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this servizio log.
	 *
	 * @param primaryKey the primary key of this servizio log
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_servizio of this servizio log.
	 *
	 * @return the id_servizio of this servizio log
	 */
	public long getId_servizio();

	/**
	 * Sets the id_servizio of this servizio log.
	 *
	 * @param id_servizio the id_servizio of this servizio log
	 */
	public void setId_servizio(long id_servizio);

	/**
	 * Returns the desc_servizio of this servizio log.
	 *
	 * @return the desc_servizio of this servizio log
	 */
	@AutoEscape
	public String getDesc_servizio();

	/**
	 * Sets the desc_servizio of this servizio log.
	 *
	 * @param desc_servizio the desc_servizio of this servizio log
	 */
	public void setDesc_servizio(String desc_servizio);

	/**
	 * Returns the email_ref of this servizio log.
	 *
	 * @return the email_ref of this servizio log
	 */
	@AutoEscape
	public String getEmail_ref();

	/**
	 * Sets the email_ref of this servizio log.
	 *
	 * @param email_ref the email_ref of this servizio log
	 */
	public void setEmail_ref(String email_ref);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		servizio.prenotazione.aule.mef.model.ServizioLog servizioLog);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servizio.prenotazione.aule.mef.model.ServizioLog> toCacheModel();

	@Override
	public servizio.prenotazione.aule.mef.model.ServizioLog toEscapedModel();

	@Override
	public servizio.prenotazione.aule.mef.model.ServizioLog toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}