/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.prenotazione.aule.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the TipoEvento service. Represents a row in the &quot;MEFAULE_TipoEvento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servizio.prenotazione.aule.mef.model.impl.TipoEventoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servizio.prenotazione.aule.mef.model.impl.TipoEventoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see TipoEvento
 * @see servizio.prenotazione.aule.mef.model.impl.TipoEventoImpl
 * @see servizio.prenotazione.aule.mef.model.impl.TipoEventoModelImpl
 * @generated
 */
@ProviderType
public interface TipoEventoModel extends BaseModel<TipoEvento> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipo evento model instance should use the {@link TipoEvento} interface instead.
	 */

	/**
	 * Returns the primary key of this tipo evento.
	 *
	 * @return the primary key of this tipo evento
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tipo evento.
	 *
	 * @param primaryKey the primary key of this tipo evento
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_evento of this tipo evento.
	 *
	 * @return the id_evento of this tipo evento
	 */
	public long getId_evento();

	/**
	 * Sets the id_evento of this tipo evento.
	 *
	 * @param id_evento the id_evento of this tipo evento
	 */
	public void setId_evento(long id_evento);

	/**
	 * Returns the desc_evento of this tipo evento.
	 *
	 * @return the desc_evento of this tipo evento
	 */
	@AutoEscape
	public String getDesc_evento();

	/**
	 * Sets the desc_evento of this tipo evento.
	 *
	 * @param desc_evento the desc_evento of this tipo evento
	 */
	public void setDesc_evento(String desc_evento);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		servizio.prenotazione.aule.mef.model.TipoEvento tipoEvento);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servizio.prenotazione.aule.mef.model.TipoEvento> toCacheModel();

	@Override
	public servizio.prenotazione.aule.mef.model.TipoEvento toEscapedModel();

	@Override
	public servizio.prenotazione.aule.mef.model.TipoEvento toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}