/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.whistleblowing.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Segnalazione service. Represents a row in the &quot;MEFWHISTLE_Segnalazione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servizio.whistleblowing.mef.model.impl.SegnalazioneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servizio.whistleblowing.mef.model.impl.SegnalazioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Segnalazione
 * @see servizio.whistleblowing.mef.model.impl.SegnalazioneImpl
 * @see servizio.whistleblowing.mef.model.impl.SegnalazioneModelImpl
 * @generated
 */
@ProviderType
public interface SegnalazioneModel extends BaseModel<Segnalazione> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a segnalazione model instance should use the {@link Segnalazione} interface instead.
	 */

	/**
	 * Returns the primary key of this segnalazione.
	 *
	 * @return the primary key of this segnalazione
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this segnalazione.
	 *
	 * @param primaryKey the primary key of this segnalazione
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_segnalazione of this segnalazione.
	 *
	 * @return the id_segnalazione of this segnalazione
	 */
	public long getId_segnalazione();

	/**
	 * Sets the id_segnalazione of this segnalazione.
	 *
	 * @param id_segnalazione the id_segnalazione of this segnalazione
	 */
	public void setId_segnalazione(long id_segnalazione);

	/**
	 * Returns the json_dati_personali of this segnalazione.
	 *
	 * @return the json_dati_personali of this segnalazione
	 */
	@AutoEscape
	public String getJson_dati_personali();

	/**
	 * Sets the json_dati_personali of this segnalazione.
	 *
	 * @param json_dati_personali the json_dati_personali of this segnalazione
	 */
	public void setJson_dati_personali(String json_dati_personali);

	/**
	 * Returns the luogo of this segnalazione.
	 *
	 * @return the luogo of this segnalazione
	 */
	@AutoEscape
	public String getLuogo();

	/**
	 * Sets the luogo of this segnalazione.
	 *
	 * @param luogo the luogo of this segnalazione
	 */
	public void setLuogo(String luogo);

	/**
	 * Returns the azioni_omissioni of this segnalazione.
	 *
	 * @return the azioni_omissioni of this segnalazione
	 */
	@AutoEscape
	public String getAzioni_omissioni();

	/**
	 * Sets the azioni_omissioni of this segnalazione.
	 *
	 * @param azioni_omissioni the azioni_omissioni of this segnalazione
	 */
	public void setAzioni_omissioni(String azioni_omissioni);

	/**
	 * Returns the descrizione of this segnalazione.
	 *
	 * @return the descrizione of this segnalazione
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this segnalazione.
	 *
	 * @param descrizione the descrizione of this segnalazione
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the autore of this segnalazione.
	 *
	 * @return the autore of this segnalazione
	 */
	@AutoEscape
	public String getAutore();

	/**
	 * Sets the autore of this segnalazione.
	 *
	 * @param autore the autore of this segnalazione
	 */
	public void setAutore(String autore);

	/**
	 * Returns the altri_testimoni of this segnalazione.
	 *
	 * @return the altri_testimoni of this segnalazione
	 */
	@AutoEscape
	public String getAltri_testimoni();

	/**
	 * Sets the altri_testimoni of this segnalazione.
	 *
	 * @param altri_testimoni the altri_testimoni of this segnalazione
	 */
	public void setAltri_testimoni(String altri_testimoni);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		servizio.whistleblowing.mef.model.Segnalazione segnalazione);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servizio.whistleblowing.mef.model.Segnalazione> toCacheModel();

	@Override
	public servizio.whistleblowing.mef.model.Segnalazione toEscapedModel();

	@Override
	public servizio.whistleblowing.mef.model.Segnalazione toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}