/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servizio.prenotazione.aule.servizi.mef.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import servizio.prenotazione.aule.servizi.mef.service.persistence.StrumEventoPK;

import java.io.Serializable;

/**
 * The base model interface for the StrumEvento service. Represents a row in the &quot;MEFAULESERV_StrumEvento&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link servizio.prenotazione.aule.servizi.mef.model.impl.StrumEventoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link servizio.prenotazione.aule.servizi.mef.model.impl.StrumEventoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StrumEvento
 * @see servizio.prenotazione.aule.servizi.mef.model.impl.StrumEventoImpl
 * @see servizio.prenotazione.aule.servizi.mef.model.impl.StrumEventoModelImpl
 * @generated
 */
@ProviderType
public interface StrumEventoModel extends BaseModel<StrumEvento> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a strum evento model instance should use the {@link StrumEvento} interface instead.
	 */

	/**
	 * Returns the primary key of this strum evento.
	 *
	 * @return the primary key of this strum evento
	 */
	public StrumEventoPK getPrimaryKey();

	/**
	 * Sets the primary key of this strum evento.
	 *
	 * @param primaryKey the primary key of this strum evento
	 */
	public void setPrimaryKey(StrumEventoPK primaryKey);

	/**
	 * Returns the id_strum of this strum evento.
	 *
	 * @return the id_strum of this strum evento
	 */
	public long getId_strum();

	/**
	 * Sets the id_strum of this strum evento.
	 *
	 * @param id_strum the id_strum of this strum evento
	 */
	public void setId_strum(long id_strum);

	/**
	 * Returns the id_sala of this strum evento.
	 *
	 * @return the id_sala of this strum evento
	 */
	public long getId_sala();

	/**
	 * Sets the id_sala of this strum evento.
	 *
	 * @param id_sala the id_sala of this strum evento
	 */
	public void setId_sala(long id_sala);

	/**
	 * Returns the email_ref of this strum evento.
	 *
	 * @return the email_ref of this strum evento
	 */
	@AutoEscape
	public String getEmail_ref();

	/**
	 * Sets the email_ref of this strum evento.
	 *
	 * @param email_ref the email_ref of this strum evento
	 */
	public void setEmail_ref(String email_ref);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		servizio.prenotazione.aule.servizi.mef.model.StrumEvento strumEvento);

	@Override
	public int hashCode();

	@Override
	public CacheModel<servizio.prenotazione.aule.servizi.mef.model.StrumEvento> toCacheModel();

	@Override
	public servizio.prenotazione.aule.servizi.mef.model.StrumEvento toEscapedModel();

	@Override
	public servizio.prenotazione.aule.servizi.mef.model.StrumEvento toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}