/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package form.service.contributo.solidarieta.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Donatore service. Represents a row in the &quot;CNTB_SOLID_DONATORE_Donatore&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>form.service.contributo.solidarieta.model.impl.DonatoreModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>form.service.contributo.solidarieta.model.impl.DonatoreImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Donatore
 * @generated
 */
@ProviderType
public interface DonatoreModel extends BaseModel<Donatore> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a donatore model instance should use the {@link Donatore} interface instead.
	 */

	/**
	 * Returns the primary key of this donatore.
	 *
	 * @return the primary key of this donatore
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this donatore.
	 *
	 * @param primaryKey the primary key of this donatore
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the ID of this donatore.
	 *
	 * @return the ID of this donatore
	 */
	public long getId();

	/**
	 * Sets the ID of this donatore.
	 *
	 * @param id the ID of this donatore
	 */
	public void setId(long id);

	/**
	 * Returns the nome of this donatore.
	 *
	 * @return the nome of this donatore
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this donatore.
	 *
	 * @param nome the nome of this donatore
	 */
	public void setNome(String nome);

	/**
	 * Returns the cognome of this donatore.
	 *
	 * @return the cognome of this donatore
	 */
	@AutoEscape
	public String getCognome();

	/**
	 * Sets the cognome of this donatore.
	 *
	 * @param cognome the cognome of this donatore
	 */
	public void setCognome(String cognome);

	/**
	 * Returns the cod_fiscale of this donatore.
	 *
	 * @return the cod_fiscale of this donatore
	 */
	@AutoEscape
	public String getCod_fiscale();

	/**
	 * Sets the cod_fiscale of this donatore.
	 *
	 * @param cod_fiscale the cod_fiscale of this donatore
	 */
	public void setCod_fiscale(String cod_fiscale);

	/**
	 * Returns the email of this donatore.
	 *
	 * @return the email of this donatore
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this donatore.
	 *
	 * @param email the email of this donatore
	 */
	public void setEmail(String email);

	/**
	 * Returns the importo of this donatore.
	 *
	 * @return the importo of this donatore
	 */
	@AutoEscape
	public String getImporto();

	/**
	 * Sets the importo of this donatore.
	 *
	 * @param importo the importo of this donatore
	 */
	public void setImporto(String importo);

	/**
	 * Returns the data_inserimento of this donatore.
	 *
	 * @return the data_inserimento of this donatore
	 */
	@AutoEscape
	public String getData_inserimento();

	/**
	 * Sets the data_inserimento of this donatore.
	 *
	 * @param data_inserimento the data_inserimento of this donatore
	 */
	public void setData_inserimento(String data_inserimento);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(
		form.service.contributo.solidarieta.model.Donatore donatore);

	@Override
	public int hashCode();

	@Override
	public CacheModel<form.service.contributo.solidarieta.model.Donatore>
		toCacheModel();

	@Override
	public form.service.contributo.solidarieta.model.Donatore toEscapedModel();

	@Override
	public form.service.contributo.solidarieta.model.Donatore
		toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();

}