/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.gestione.riunioni.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the AmministrazioneConvocante service. Represents a row in the &quot;MEF_AmministrazioneConvocante&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.gestione.riunioni.model.impl.AmministrazioneConvocanteModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.gestione.riunioni.model.impl.AmministrazioneConvocanteImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AmministrazioneConvocante
 * @see com.intranet.mef.gestione.riunioni.model.impl.AmministrazioneConvocanteImpl
 * @see com.intranet.mef.gestione.riunioni.model.impl.AmministrazioneConvocanteModelImpl
 * @generated
 */
@ProviderType
public interface AmministrazioneConvocanteModel extends BaseModel<AmministrazioneConvocante> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a amministrazione convocante model instance should use the {@link AmministrazioneConvocante} interface instead.
	 */

	/**
	 * Returns the primary key of this amministrazione convocante.
	 *
	 * @return the primary key of this amministrazione convocante
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this amministrazione convocante.
	 *
	 * @param primaryKey the primary key of this amministrazione convocante
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_amministrazione_convocante of this amministrazione convocante.
	 *
	 * @return the id_amministrazione_convocante of this amministrazione convocante
	 */
	public long getId_amministrazione_convocante();

	/**
	 * Sets the id_amministrazione_convocante of this amministrazione convocante.
	 *
	 * @param id_amministrazione_convocante the id_amministrazione_convocante of this amministrazione convocante
	 */
	public void setId_amministrazione_convocante(
		long id_amministrazione_convocante);

	/**
	 * Returns the nome_amministrazione of this amministrazione convocante.
	 *
	 * @return the nome_amministrazione of this amministrazione convocante
	 */
	@AutoEscape
	public String getNome_amministrazione();

	/**
	 * Sets the nome_amministrazione of this amministrazione convocante.
	 *
	 * @param nome_amministrazione the nome_amministrazione of this amministrazione convocante
	 */
	public void setNome_amministrazione(String nome_amministrazione);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(AmministrazioneConvocante amministrazioneConvocante);

	@Override
	public int hashCode();

	@Override
	public CacheModel<AmministrazioneConvocante> toCacheModel();

	@Override
	public AmministrazioneConvocante toEscapedModel();

	@Override
	public AmministrazioneConvocante toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}