/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.gestione.riunioni.model;

import aQute.bnd.annotation.ProviderType;

import com.intranet.mef.gestione.riunioni.service.persistence.InvitatiRiunionePK;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the InvitatiRiunione service. Represents a row in the &quot;MEF_InvitatiRiunione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.gestione.riunioni.model.impl.InvitatiRiunioneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.gestione.riunioni.model.impl.InvitatiRiunioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see InvitatiRiunione
 * @see com.intranet.mef.gestione.riunioni.model.impl.InvitatiRiunioneImpl
 * @see com.intranet.mef.gestione.riunioni.model.impl.InvitatiRiunioneModelImpl
 * @generated
 */
@ProviderType
public interface InvitatiRiunioneModel extends BaseModel<InvitatiRiunione> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a invitati riunione model instance should use the {@link InvitatiRiunione} interface instead.
	 */

	/**
	 * Returns the primary key of this invitati riunione.
	 *
	 * @return the primary key of this invitati riunione
	 */
	public InvitatiRiunionePK getPrimaryKey();

	/**
	 * Sets the primary key of this invitati riunione.
	 *
	 * @param primaryKey the primary key of this invitati riunione
	 */
	public void setPrimaryKey(InvitatiRiunionePK primaryKey);

	/**
	 * Returns the id_segreteria of this invitati riunione.
	 *
	 * @return the id_segreteria of this invitati riunione
	 */
	public long getId_segreteria();

	/**
	 * Sets the id_segreteria of this invitati riunione.
	 *
	 * @param id_segreteria the id_segreteria of this invitati riunione
	 */
	public void setId_segreteria(long id_segreteria);

	/**
	 * Returns the note of this invitati riunione.
	 *
	 * @return the note of this invitati riunione
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this invitati riunione.
	 *
	 * @param note the note of this invitati riunione
	 */
	public void setNote(String note);

	/**
	 * Returns the partecipanti of this invitati riunione.
	 *
	 * @return the partecipanti of this invitati riunione
	 */
	@AutoEscape
	public String getPartecipanti();

	/**
	 * Sets the partecipanti of this invitati riunione.
	 *
	 * @param partecipanti the partecipanti of this invitati riunione
	 */
	public void setPartecipanti(String partecipanti);

	/**
	 * Returns the id_stato_invitato of this invitati riunione.
	 *
	 * @return the id_stato_invitato of this invitati riunione
	 */
	public long getId_stato_invitato();

	/**
	 * Sets the id_stato_invitato of this invitati riunione.
	 *
	 * @param id_stato_invitato the id_stato_invitato of this invitati riunione
	 */
	public void setId_stato_invitato(long id_stato_invitato);

	/**
	 * Returns the id_riunione of this invitati riunione.
	 *
	 * @return the id_riunione of this invitati riunione
	 */
	public long getId_riunione();

	/**
	 * Sets the id_riunione of this invitati riunione.
	 *
	 * @param id_riunione the id_riunione of this invitati riunione
	 */
	public void setId_riunione(long id_riunione);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(InvitatiRiunione invitatiRiunione);

	@Override
	public int hashCode();

	@Override
	public CacheModel<InvitatiRiunione> toCacheModel();

	@Override
	public InvitatiRiunione toEscapedModel();

	@Override
	public InvitatiRiunione toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}