/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.gestione.riunioni.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Luogo service. Represents a row in the &quot;MEF_Luogo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.gestione.riunioni.model.impl.LuogoModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.gestione.riunioni.model.impl.LuogoImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Luogo
 * @see com.intranet.mef.gestione.riunioni.model.impl.LuogoImpl
 * @see com.intranet.mef.gestione.riunioni.model.impl.LuogoModelImpl
 * @generated
 */
@ProviderType
public interface LuogoModel extends BaseModel<Luogo> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a luogo model instance should use the {@link Luogo} interface instead.
	 */

	/**
	 * Returns the primary key of this luogo.
	 *
	 * @return the primary key of this luogo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this luogo.
	 *
	 * @param primaryKey the primary key of this luogo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_luogo of this luogo.
	 *
	 * @return the id_luogo of this luogo
	 */
	public long getId_luogo();

	/**
	 * Sets the id_luogo of this luogo.
	 *
	 * @param id_luogo the id_luogo of this luogo
	 */
	public void setId_luogo(long id_luogo);

	/**
	 * Returns the nome of this luogo.
	 *
	 * @return the nome of this luogo
	 */
	@AutoEscape
	public String getNome();

	/**
	 * Sets the nome of this luogo.
	 *
	 * @param nome the nome of this luogo
	 */
	public void setNome(String nome);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Luogo luogo);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Luogo> toCacheModel();

	@Override
	public Luogo toEscapedModel();

	@Override
	public Luogo toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}