/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.gestione.riunioni.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Riunione service. Represents a row in the &quot;MEF_Riunione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.gestione.riunioni.model.impl.RiunioneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.gestione.riunioni.model.impl.RiunioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Riunione
 * @see com.intranet.mef.gestione.riunioni.model.impl.RiunioneImpl
 * @see com.intranet.mef.gestione.riunioni.model.impl.RiunioneModelImpl
 * @generated
 */
@ProviderType
public interface RiunioneModel extends BaseModel<Riunione> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a riunione model instance should use the {@link Riunione} interface instead.
	 */

	/**
	 * Returns the primary key of this riunione.
	 *
	 * @return the primary key of this riunione
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this riunione.
	 *
	 * @param primaryKey the primary key of this riunione
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_riunione of this riunione.
	 *
	 * @return the id_riunione of this riunione
	 */
	public long getId_riunione();

	/**
	 * Sets the id_riunione of this riunione.
	 *
	 * @param id_riunione the id_riunione of this riunione
	 */
	public void setId_riunione(long id_riunione);

	/**
	 * Returns the oggetto of this riunione.
	 *
	 * @return the oggetto of this riunione
	 */
	@AutoEscape
	public String getOggetto();

	/**
	 * Sets the oggetto of this riunione.
	 *
	 * @param oggetto the oggetto of this riunione
	 */
	public void setOggetto(String oggetto);

	/**
	 * Returns the data_inizio of this riunione.
	 *
	 * @return the data_inizio of this riunione
	 */
	public Date getData_inizio();

	/**
	 * Sets the data_inizio of this riunione.
	 *
	 * @param data_inizio the data_inizio of this riunione
	 */
	public void setData_inizio(Date data_inizio);

	/**
	 * Returns the data_fine of this riunione.
	 *
	 * @return the data_fine of this riunione
	 */
	public Date getData_fine();

	/**
	 * Sets the data_fine of this riunione.
	 *
	 * @param data_fine the data_fine of this riunione
	 */
	public void setData_fine(Date data_fine);

	/**
	 * Returns the note of this riunione.
	 *
	 * @return the note of this riunione
	 */
	@AutoEscape
	public String getNote();

	/**
	 * Sets the note of this riunione.
	 *
	 * @param note the note of this riunione
	 */
	public void setNote(String note);

	/**
	 * Returns the data_modifica of this riunione.
	 *
	 * @return the data_modifica of this riunione
	 */
	public Date getData_modifica();

	/**
	 * Sets the data_modifica of this riunione.
	 *
	 * @param data_modifica the data_modifica of this riunione
	 */
	public void setData_modifica(Date data_modifica);

	/**
	 * Returns the data_creazione of this riunione.
	 *
	 * @return the data_creazione of this riunione
	 */
	public Date getData_creazione();

	/**
	 * Sets the data_creazione of this riunione.
	 *
	 * @param data_creazione the data_creazione of this riunione
	 */
	public void setData_creazione(Date data_creazione);

	/**
	 * Returns the protocollo of this riunione.
	 *
	 * @return the protocollo of this riunione
	 */
	@AutoEscape
	public String getProtocollo();

	/**
	 * Sets the protocollo of this riunione.
	 *
	 * @param protocollo the protocollo of this riunione
	 */
	public void setProtocollo(String protocollo);

	/**
	 * Returns the id_stato_riunione of this riunione.
	 *
	 * @return the id_stato_riunione of this riunione
	 */
	public long getId_stato_riunione();

	/**
	 * Sets the id_stato_riunione of this riunione.
	 *
	 * @param id_stato_riunione the id_stato_riunione of this riunione
	 */
	public void setId_stato_riunione(long id_stato_riunione);

	/**
	 * Returns the id_tipo of this riunione.
	 *
	 * @return the id_tipo of this riunione
	 */
	public long getId_tipo();

	/**
	 * Sets the id_tipo of this riunione.
	 *
	 * @param id_tipo the id_tipo of this riunione
	 */
	public void setId_tipo(long id_tipo);

	/**
	 * Returns the id_luogo of this riunione.
	 *
	 * @return the id_luogo of this riunione
	 */
	public long getId_luogo();

	/**
	 * Sets the id_luogo of this riunione.
	 *
	 * @param id_luogo the id_luogo of this riunione
	 */
	public void setId_luogo(long id_luogo);

	/**
	 * Returns the id_amministrazione_convocante of this riunione.
	 *
	 * @return the id_amministrazione_convocante of this riunione
	 */
	public long getId_amministrazione_convocante();

	/**
	 * Sets the id_amministrazione_convocante of this riunione.
	 *
	 * @param id_amministrazione_convocante the id_amministrazione_convocante of this riunione
	 */
	public void setId_amministrazione_convocante(
		long id_amministrazione_convocante);

	/**
	 * Returns the data_ultimo_sollecito of this riunione.
	 *
	 * @return the data_ultimo_sollecito of this riunione
	 */
	public Date getData_ultimo_sollecito();

	/**
	 * Sets the data_ultimo_sollecito of this riunione.
	 *
	 * @param data_ultimo_sollecito the data_ultimo_sollecito of this riunione
	 */
	public void setData_ultimo_sollecito(Date data_ultimo_sollecito);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Riunione riunione);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Riunione> toCacheModel();

	@Override
	public Riunione toEscapedModel();

	@Override
	public Riunione toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}