/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.gestione.riunioni.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Segreteria service. Represents a row in the &quot;MEF_Segreteria&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.gestione.riunioni.model.impl.SegreteriaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.gestione.riunioni.model.impl.SegreteriaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Segreteria
 * @see com.intranet.mef.gestione.riunioni.model.impl.SegreteriaImpl
 * @see com.intranet.mef.gestione.riunioni.model.impl.SegreteriaModelImpl
 * @generated
 */
@ProviderType
public interface SegreteriaModel extends BaseModel<Segreteria> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a segreteria model instance should use the {@link Segreteria} interface instead.
	 */

	/**
	 * Returns the primary key of this segreteria.
	 *
	 * @return the primary key of this segreteria
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this segreteria.
	 *
	 * @param primaryKey the primary key of this segreteria
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_segreteria of this segreteria.
	 *
	 * @return the id_segreteria of this segreteria
	 */
	public long getId_segreteria();

	/**
	 * Sets the id_segreteria of this segreteria.
	 *
	 * @param id_segreteria the id_segreteria of this segreteria
	 */
	public void setId_segreteria(long id_segreteria);

	/**
	 * Returns the email of this segreteria.
	 *
	 * @return the email of this segreteria
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this segreteria.
	 *
	 * @param email the email of this segreteria
	 */
	public void setEmail(String email);

	/**
	 * Returns the descrizione of this segreteria.
	 *
	 * @return the descrizione of this segreteria
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this segreteria.
	 *
	 * @param descrizione the descrizione of this segreteria
	 */
	public void setDescrizione(String descrizione);

	/**
	 * Returns the acronimo of this segreteria.
	 *
	 * @return the acronimo of this segreteria
	 */
	@AutoEscape
	public String getAcronimo();

	/**
	 * Sets the acronimo of this segreteria.
	 *
	 * @param acronimo the acronimo of this segreteria
	 */
	public void setAcronimo(String acronimo);

	/**
	 * Returns the livello_gerarchia of this segreteria.
	 *
	 * @return the livello_gerarchia of this segreteria
	 */
	public long getLivello_gerarchia();

	/**
	 * Sets the livello_gerarchia of this segreteria.
	 *
	 * @param livello_gerarchia the livello_gerarchia of this segreteria
	 */
	public void setLivello_gerarchia(long livello_gerarchia);

	/**
	 * Returns the cod_padre of this segreteria.
	 *
	 * @return the cod_padre of this segreteria
	 */
	public long getCod_padre();

	/**
	 * Sets the cod_padre of this segreteria.
	 *
	 * @param cod_padre the cod_padre of this segreteria
	 */
	public void setCod_padre(long cod_padre);

	/**
	 * Returns the data_fine_esistenza of this segreteria.
	 *
	 * @return the data_fine_esistenza of this segreteria
	 */
	public Date getData_fine_esistenza();

	/**
	 * Sets the data_fine_esistenza of this segreteria.
	 *
	 * @param data_fine_esistenza the data_fine_esistenza of this segreteria
	 */
	public void setData_fine_esistenza(Date data_fine_esistenza);

	/**
	 * Returns the indirizzo of this segreteria.
	 *
	 * @return the indirizzo of this segreteria
	 */
	@AutoEscape
	public String getIndirizzo();

	/**
	 * Sets the indirizzo of this segreteria.
	 *
	 * @param indirizzo the indirizzo of this segreteria
	 */
	public void setIndirizzo(String indirizzo);

	/**
	 * Returns the cap of this segreteria.
	 *
	 * @return the cap of this segreteria
	 */
	@AutoEscape
	public String getCap();

	/**
	 * Sets the cap of this segreteria.
	 *
	 * @param cap the cap of this segreteria
	 */
	public void setCap(String cap);

	/**
	 * Returns the cod_istat_citta of this segreteria.
	 *
	 * @return the cod_istat_citta of this segreteria
	 */
	public long getCod_istat_citta();

	/**
	 * Sets the cod_istat_citta of this segreteria.
	 *
	 * @param cod_istat_citta the cod_istat_citta of this segreteria
	 */
	public void setCod_istat_citta(long cod_istat_citta);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Segreteria segreteria);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Segreteria> toCacheModel();

	@Override
	public Segreteria toEscapedModel();

	@Override
	public Segreteria toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}