/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.gestione.riunioni.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the StatoRiunione service. Represents a row in the &quot;MEF_StatoRiunione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.gestione.riunioni.model.impl.StatoRiunioneModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.gestione.riunioni.model.impl.StatoRiunioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StatoRiunione
 * @see com.intranet.mef.gestione.riunioni.model.impl.StatoRiunioneImpl
 * @see com.intranet.mef.gestione.riunioni.model.impl.StatoRiunioneModelImpl
 * @generated
 */
@ProviderType
public interface StatoRiunioneModel extends BaseModel<StatoRiunione> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a stato riunione model instance should use the {@link StatoRiunione} interface instead.
	 */

	/**
	 * Returns the primary key of this stato riunione.
	 *
	 * @return the primary key of this stato riunione
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this stato riunione.
	 *
	 * @param primaryKey the primary key of this stato riunione
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_stato_riunione of this stato riunione.
	 *
	 * @return the id_stato_riunione of this stato riunione
	 */
	public long getId_stato_riunione();

	/**
	 * Sets the id_stato_riunione of this stato riunione.
	 *
	 * @param id_stato_riunione the id_stato_riunione of this stato riunione
	 */
	public void setId_stato_riunione(long id_stato_riunione);

	/**
	 * Returns the label of this stato riunione.
	 *
	 * @return the label of this stato riunione
	 */
	@AutoEscape
	public String getLabel();

	/**
	 * Sets the label of this stato riunione.
	 *
	 * @param label the label of this stato riunione
	 */
	public void setLabel(String label);

	/**
	 * Returns the next_stato of this stato riunione.
	 *
	 * @return the next_stato of this stato riunione
	 */
	@AutoEscape
	public String getNext_stato();

	/**
	 * Sets the next_stato of this stato riunione.
	 *
	 * @param next_stato the next_stato of this stato riunione
	 */
	public void setNext_stato(String next_stato);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(StatoRiunione statoRiunione);

	@Override
	public int hashCode();

	@Override
	public CacheModel<StatoRiunione> toCacheModel();

	@Override
	public StatoRiunione toEscapedModel();

	@Override
	public StatoRiunione toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}