/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.assistance.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Area service. Represents a row in the &quot;Assistance_Area&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.assistance.model.impl.AreaModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.assistance.model.impl.AreaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Area
 * @see com.intranet.mef.assistance.model.impl.AreaImpl
 * @see com.intranet.mef.assistance.model.impl.AreaModelImpl
 * @generated
 */
@ProviderType
public interface AreaModel extends BaseModel<Area> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a area model instance should use the {@link Area} interface instead.
	 */

	/**
	 * Returns the primary key of this area.
	 *
	 * @return the primary key of this area
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this area.
	 *
	 * @param primaryKey the primary key of this area
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this area.
	 *
	 * @return the uuid of this area
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this area.
	 *
	 * @param uuid the uuid of this area
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the area ID of this area.
	 *
	 * @return the area ID of this area
	 */
	@AutoEscape
	public String getAreaId();

	/**
	 * Sets the area ID of this area.
	 *
	 * @param areaId the area ID of this area
	 */
	public void setAreaId(String areaId);

	/**
	 * Returns the area name of this area.
	 *
	 * @return the area name of this area
	 */
	@AutoEscape
	public String getAreaName();

	/**
	 * Sets the area name of this area.
	 *
	 * @param areaName the area name of this area
	 */
	public void setAreaName(String areaName);

	/**
	 * Returns the ass service ID of this area.
	 *
	 * @return the ass service ID of this area
	 */
	@AutoEscape
	public String getAssServiceId();

	/**
	 * Sets the ass service ID of this area.
	 *
	 * @param assServiceId the ass service ID of this area
	 */
	public void setAssServiceId(String assServiceId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Area area);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Area> toCacheModel();

	@Override
	public Area toEscapedModel();

	@Override
	public Area toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}