/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.assistance.model;

import aQute.bnd.annotation.ProviderType;

import com.intranet.mef.assistance.service.persistence.FaqPK;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Faq service. Represents a row in the &quot;Assistance_Faq&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.assistance.model.impl.FaqModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.assistance.model.impl.FaqImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Faq
 * @see com.intranet.mef.assistance.model.impl.FaqImpl
 * @see com.intranet.mef.assistance.model.impl.FaqModelImpl
 * @generated
 */
@ProviderType
public interface FaqModel extends BaseModel<Faq> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a faq model instance should use the {@link Faq} interface instead.
	 */

	/**
	 * Returns the primary key of this faq.
	 *
	 * @return the primary key of this faq
	 */
	public FaqPK getPrimaryKey();

	/**
	 * Sets the primary key of this faq.
	 *
	 * @param primaryKey the primary key of this faq
	 */
	public void setPrimaryKey(FaqPK primaryKey);

	/**
	 * Returns the uuid of this faq.
	 *
	 * @return the uuid of this faq
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this faq.
	 *
	 * @param uuid the uuid of this faq
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the faq ID of this faq.
	 *
	 * @return the faq ID of this faq
	 */
	@AutoEscape
	public String getFaqId();

	/**
	 * Sets the faq ID of this faq.
	 *
	 * @param faqId the faq ID of this faq
	 */
	public void setFaqId(String faqId);

	/**
	 * Returns the siebel ID of this faq.
	 *
	 * @return the siebel ID of this faq
	 */
	@AutoEscape
	public String getSiebelId();

	/**
	 * Sets the siebel ID of this faq.
	 *
	 * @param siebelId the siebel ID of this faq
	 */
	public void setSiebelId(String siebelId);

	/**
	 * Returns the questions of this faq.
	 *
	 * @return the questions of this faq
	 */
	@AutoEscape
	public String getQuestions();

	/**
	 * Sets the questions of this faq.
	 *
	 * @param questions the questions of this faq
	 */
	public void setQuestions(String questions);

	/**
	 * Returns the response of this faq.
	 *
	 * @return the response of this faq
	 */
	@AutoEscape
	public String getResponse();

	/**
	 * Sets the response of this faq.
	 *
	 * @param response the response of this faq
	 */
	public void setResponse(String response);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Faq faq);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Faq> toCacheModel();

	@Override
	public Faq toEscapedModel();

	@Override
	public Faq toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}