/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.assistance.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Servizio service. Represents a row in the &quot;Assistance_Servizio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.assistance.model.impl.ServizioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.assistance.model.impl.ServizioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Servizio
 * @see com.intranet.mef.assistance.model.impl.ServizioImpl
 * @see com.intranet.mef.assistance.model.impl.ServizioModelImpl
 * @generated
 */
@ProviderType
public interface ServizioModel extends BaseModel<Servizio> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a servizio model instance should use the {@link Servizio} interface instead.
	 */

	/**
	 * Returns the primary key of this servizio.
	 *
	 * @return the primary key of this servizio
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this servizio.
	 *
	 * @param primaryKey the primary key of this servizio
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this servizio.
	 *
	 * @return the uuid of this servizio
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this servizio.
	 *
	 * @param uuid the uuid of this servizio
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the ass service ID of this servizio.
	 *
	 * @return the ass service ID of this servizio
	 */
	@AutoEscape
	public String getAssServiceId();

	/**
	 * Sets the ass service ID of this servizio.
	 *
	 * @param assServiceId the ass service ID of this servizio
	 */
	public void setAssServiceId(String assServiceId);

	/**
	 * Returns the service name of this servizio.
	 *
	 * @return the service name of this servizio
	 */
	@AutoEscape
	public String getServiceName();

	/**
	 * Sets the service name of this servizio.
	 *
	 * @param serviceName the service name of this servizio
	 */
	public void setServiceName(String serviceName);

	/**
	 * Returns the ass scope ID of this servizio.
	 *
	 * @return the ass scope ID of this servizio
	 */
	@AutoEscape
	public String getAssScopeId();

	/**
	 * Sets the ass scope ID of this servizio.
	 *
	 * @param assScopeId the ass scope ID of this servizio
	 */
	public void setAssScopeId(String assScopeId);

	/**
	 * Returns the level assistance of this servizio.
	 *
	 * @return the level assistance of this servizio
	 */
	@AutoEscape
	public String getLevelAssistance();

	/**
	 * Sets the level assistance of this servizio.
	 *
	 * @param levelAssistance the level assistance of this servizio
	 */
	public void setLevelAssistance(String levelAssistance);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Servizio servizio);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Servizio> toCacheModel();

	@Override
	public Servizio toEscapedModel();

	@Override
	public Servizio toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}