/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.intranet.mef.assistance.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the Topic service. Represents a row in the &quot;Assistance_Topic&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.intranet.mef.assistance.model.impl.TopicModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.intranet.mef.assistance.model.impl.TopicImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Topic
 * @see com.intranet.mef.assistance.model.impl.TopicImpl
 * @see com.intranet.mef.assistance.model.impl.TopicModelImpl
 * @generated
 */
@ProviderType
public interface TopicModel extends BaseModel<Topic> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a topic model instance should use the {@link Topic} interface instead.
	 */

	/**
	 * Returns the primary key of this topic.
	 *
	 * @return the primary key of this topic
	 */
	public String getPrimaryKey();

	/**
	 * Sets the primary key of this topic.
	 *
	 * @param primaryKey the primary key of this topic
	 */
	public void setPrimaryKey(String primaryKey);

	/**
	 * Returns the uuid of this topic.
	 *
	 * @return the uuid of this topic
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this topic.
	 *
	 * @param uuid the uuid of this topic
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the topic ID of this topic.
	 *
	 * @return the topic ID of this topic
	 */
	@AutoEscape
	public String getTopicId();

	/**
	 * Sets the topic ID of this topic.
	 *
	 * @param topicId the topic ID of this topic
	 */
	public void setTopicId(String topicId);

	/**
	 * Returns the topic name of this topic.
	 *
	 * @return the topic name of this topic
	 */
	@AutoEscape
	public String getTopicName();

	/**
	 * Sets the topic name of this topic.
	 *
	 * @param topicName the topic name of this topic
	 */
	public void setTopicName(String topicName);

	/**
	 * Returns the area ID of this topic.
	 *
	 * @return the area ID of this topic
	 */
	@AutoEscape
	public String getAreaId();

	/**
	 * Sets the area ID of this topic.
	 *
	 * @param areaId the area ID of this topic
	 */
	public void setAreaId(String areaId);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(Topic topic);

	@Override
	public int hashCode();

	@Override
	public CacheModel<Topic> toCacheModel();

	@Override
	public Topic toEscapedModel();

	@Override
	public Topic toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}